### ISSUE TITLE
lldb-feedstock is not getting a PR

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#100]
version bump to 6.0.0 should happen. any idea why it doesn't?

**Comment by CJ-Wright** [comment]
Please see this run: https://travis-ci.org/regro/00-find-feedstocks/builds/357476481

**Comment by CJ-Wright** [comment]
Here is the error
```
BUILDING lldb
'environ' is undefined
Setting git attributes
```

**Comment by isuruf** [comment]
Fixed in https://github.com/regro/cf-scripts/pull/101

**Comment by CJ-Wright** [comment]
Perfect!
