### ISSUE TITLE
have bot automatically rerun PRs that end up with merge conflicts

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#1014]

**Comment by CJ-Wright** [comment]
Need to check if bot is only committer, use this: https://developer.github.com/v3/pulls/#list-commits-on-a-pull-request

**Comment by CJ-Wright** [comment]
And check if the `mergeable_state` = `dirty`.

**Comment by CJ-Wright** [comment]
Percentage of Open PRs by state:
```
{'blocked': 0.9865175928970734,
 'clean': 27.88556395922394,
 'dirty': 21.80203880302532,
 'unknown': 0.03288391976323578,
 'unstable': 49.292995725090435}
```

**Comment by beckermr** [comment]
According to @isuruf I made a bunch of aarch not mergeable due to commits from the admin bot. Not much to do about that.

**Comment by beckermr** [comment]
Though this functionality will fix that actually so that's good.
