### ISSUE TITLE
Heartbeat approach to keeping things running

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#1019]
We seem to be running into issues where the bot halts by itself.
Implementing a heartbeat could help fix this.

1. Have each job write into its own heartbeat file the current seconds since epoc and have deploy send that to cf-graph-countyfair
2. Have a new cron job run hourly and check all the heartbeats and see if any of them are out of date by more than 3 (or x) hours. For each one out of date prompt the worker to start up again and update the heartbeat timestamp.

**Comment by beckermr** [comment]
I put the heartbeats in the circle worker repo to separate the structure of how we run parts of the bot from the actual bot data. Otherwise, this should be done.
