### ISSUE TITLE
Comment and question

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#104]
I *love* the idea of the auto update but conda forge requires humans to maintain and check PRs. 

Maybe the message in the PRs could be clearer by explaining what this repo does and what the expectations are for how it’s PRs should be handled?

**Comment by CJ-Wright** [comment]
Thank you for reporting!

**Comment by CJ-Wright** [comment]
Would you be interested in putting in a PR with an updated message? If not, could you please let us know what you think is missing?

This is a sister/subish project to conda-forge. I think all the contributors thus far have been CF members, and most of us serve as CF core devs.

**Comment by beckermr** [comment]
Ahhh cool!  Yeah I’ll make a pr with more detailed language for the commit message.

**Comment by CJ-Wright** [comment]
This is where the PR message is created: https://github.com/regro/cf-scripts/blob/master/03-auto_tick.xsh#L215
