### ISSUE TITLE
Starting `pypy` migrations for packages using `matplotlib-base`

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1057]
As we now have `matplotlib-base` packaged for `pypy` ( https://github.com/conda-forge/matplotlib-feedstock/pull/247 ), it would be good to make sure packages that only require `matplotlib-base` (as opposed to `matplotlib`) can begin the `pypy` migration. Not sure if that is just automatic or if there is some manual step needed.

cc @mattip

**Comment by mattip** [comment]
awesome!

**Comment by mattip** [comment]
matplotlib-base might be useful for people who wish to use a GPL-free conda as well.

**Comment by beckermr** [comment]
This should just work. If it doesn’t, let us know.

**Comment by jakirkham** [comment]
Ok, great! Wasn't sure since it wasn't a bot PR.

**Comment by beckermr** [comment]
Ahhhh. The bot will have to get to that node. So check any deps and make sure those get migrated too.

**Comment by isuruf** [comment]
That's not possible. See the gitter chat.

**Comment by jakirkham** [comment]
Sorry I'm not following. What should we be doing?

**Comment by beckermr** [comment]
@isuruf are you saying the bot will never get to matplotlib-base?

The gitter chat just pointed out that we cannot start the bot in the middle. However matplotlib-base doesn’t depend on qt so it may not be blocked on deps.

**Comment by isuruf** [comment]
`matplotlib-base` and `matplotlib` are in the same feedstock.

**Comment by beckermr** [comment]
Ack I forgot that.

**Comment by jakirkham** [comment]
Ah so is the bot just saying the `matplotlib` feedstock is not migrated (even though `matplotlib-base` has been built), so it can't migrate anything that uses `matplotlib` or `matplotlib-base`? Or am I not understanding the issue?

**Comment by beckermr** [comment]
Yep afaik that is the issue.
