### ISSUE TITLE
Multiple `icu` PRs (to `matplotlib`)

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1059]
It looks like several PRs were submitted by the bot to update `icu` in `matplotlib`. Not sure why we are seeing so many.

xref: https://github.com/conda-forge/matplotlib-feedstock/pull/248
xref: https://github.com/conda-forge/matplotlib-feedstock/pull/249
xref: https://github.com/conda-forge/matplotlib-feedstock/pull/250
xref: https://github.com/conda-forge/matplotlib-feedstock/pull/251
xref: https://github.com/conda-forge/matplotlib-feedstock/pull/252

**Comment by jakirkham** [comment]
cc @conda-forge/matplotlib

**Comment by beckermr** [comment]
See gitter. Once it is migrated close them and then see if it happens again. We had a bug updating bot metadata.

**Comment by jakirkham** [comment]
Looks like PR ( https://github.com/conda-forge/matplotlib-feedstock/pull/251 ) has already been merged. Are we ok to close them or should we wait?

**Comment by beckermr** [comment]
Yes close the others.

**Comment by CJ-Wright** [comment]
I think this is fixed
