### ISSUE TITLE
Shogun arpack37 migration complete

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1065]
The `shogun-cpp` feedstock migrated to `arpack37` with PR ( https://github.com/conda-forge/shogun-cpp-feedstock/pull/36 ). However it shows up as "Awaiting-PR". Is there something still missing or does the graph need an update.

cc @djsutherland @vigsterkr

**Comment by beckermr** [comment]
Looks like the bot missed the pr update. We probably need to adjust the metadata by hand.

**Comment by jakirkham** [comment]
Thanks for clarifying. What is the process for updating the metadata?

**Comment by beckermr** [comment]
make a pr on cf-graph-county-fair it is a bit involved so you might need @CJ-Wright or someone on @regro/auto-tick to do it - I don't have time just this minute

**Comment by beckermr** [comment]
This is wrong. The "shogun" feedstock is awaiting PR, not "shogun-cpp".

**Comment by beckermr** [comment]
You all need to merge 6.1.4 on shogun given the pin the feedstock. Then it will move along hopefully.

**Comment by jakirkham** [comment]
Just for clarity, I'm just walking through the migrations and seeing how we can move things along across the org. This isn't something I maintain personally.

Thanks for the guidance. Looks like there have been a few attempts ( https://github.com/conda-forge/shogun-feedstock/pull/15 ) ( https://github.com/conda-forge/shogun-feedstock/pull/17 ) ( https://github.com/conda-forge/shogun-feedstock/pull/18 ) ( https://github.com/conda-forge/shogun-feedstock/pull/23 ), but things seem stuck atm.

Anyways looks like this isn't a bot issue. So will go ahead and close. Thanks for the help 🙂
