### ISSUE TITLE
PR loses sha256 filters

### ISSUE THREAD

**Issue by pkgw** [regro/cf-scripts#108]
[This PR](https://github.com/conda-forge/rust-feedstock/pull/12) filed by the bot is pretty close, but it doesn't realize that we have multiple source and SHA256 specifiers for each platform of the package. This is a fairly specialized case, but in principle the bot could figure this out and generate correct PRs.

**Comment by ocefpaf** [comment]
I think this is a duplicated of https://github.com/regro/cf-scripts/issues/33

**Comment by pkgw** [comment]
Yeah, I'd say so.
