### ISSUE TITLE
auto-tick creates perl matrix?

### ISSUE THREAD

**Issue by minrk** [regro/cf-scripts#112]
https://github.com/conda-forge/openmpi-feedstock/pull/18 on openmpi added a build matrix for perl versions. This is presumably because perl is a build dependency. But it shouldn't have because perl isn't a runtime dependency.

**Comment by dougalsutherland** [comment]
Don't think this had anything to do with the bot in particular; it was just a rerender that added it. You can pin perl to a specific version to prevent it.

**Comment by CJ-Wright** [comment]
I'm going to close this, please feel free to re-open if this ends up being a bot issue.

**Comment by jakirkham** [comment]
Yeah, this is a re-rendering problem. Please see issue ( https://github.com/conda-forge/conda-smithy/issues/415 ).
