### ISSUE TITLE
pyarrow not picked up in OSX arm64 migrator

### ISSUE THREAD

**Issue by xhochy** [regro/cf-scripts#1149]
See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/757#issuecomment-688690039

**Comment by isuruf** [comment]
probably fixed in https://github.com/regro/cf-scripts/pull/1150

**Comment by beckermr** [comment]
thanks @isuruf!

**Comment by xhochy** [comment]
Long list in awaiting-pr, so this is fixed. Thanks @isuruf !
