### ISSUE TITLE
Differentiate build/host dependencies

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1186]
Would be good for migrators to skip migration of feedstocks that list something as a `build` dependency (like `make`) as opposed to a `host` dependency (like `python`). Here's an example case ( https://github.com/conda-forge/llvmdev-feedstock/pull/102 )

Note: As some older recipes may only have `build` and not `host`, we may want to exempt them from this.

cc @CJ-Wright @isuruf

**Comment by CJ-Wright** [comment]
The problem here is that the graph thinks that `python` is a host dep: https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/llvmdev.json#L447

**Comment by beckermr** [comment]
We aggregate requirements over outputs and are picking up this entry in hist for lvvdmdev. 

https://github.com/conda-forge/llvmdev-feedstock/blob/master/recipe/meta.yaml#L157

It appears the bug here is that we are not looking at noarch for outputs when building the graph.

**Comment by jakirkham** [comment]
Fixed by PR ( https://github.com/regro/cf-scripts/pull/1188 )
