### ISSUE TITLE
Incomplete message in automatically generated PR

### ISSUE THREAD

**Issue by saraedum** [regro/cf-scripts#1206]
The last line of https://github.com/conda-forge/cppyy-feedstock/pull/33 reads:

`This PR was generated by , please use this URL for debugging`

Seems like some things are missing in this sentence.

**Comment by remram44** [comment]
Got this as well: https://github.com/conda-forge/scp-feedstock/pull/17

**Comment by beckermr** [comment]
fixed! closing!
