### ISSUE TITLE
CuPy CUDA 11.0 migration PR not reissued

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1207]
At the beginning of the CUDA 11.0 migration, we got PR ( https://github.com/conda-forge/cupy-feedstock/pull/72 ) to migrate CuPy to CUDA 11.0. However as we needed a newer version of NCCL first ( https://github.com/conda-forge/cupy-feedstock/pull/73 ), we asked the bot to rerun the CUDA 11.0 migration PR for CuPy after migrating to a newer NCCL version. However we haven't seen any CUDA 11.0 migration PR since. Could someone please take a look? 🙂

**Comment by jakirkham** [comment]
cc @leofang

**Comment by CJ-Wright** [comment]
It is currently listed as not solvable: https://conda-forge.org/status/#cuda110

**Comment by jakirkham** [comment]
The error listed shows something about `__glibc`. This seems like a red herring.

**Comment by jakirkham** [comment]
Looks like we now have a second package having this issue, [`prismatic_split`]( https://github.com/conda-forge/prismatic_split-feedstock ). Not sure how long the change takes to go into affect. So unsure whether this will clear out after some time or if the issues is not fixed.

https://conda-forge.org/status/#cuda110

**Comment by beckermr** [comment]
Yeah it should have already worked if it was going to. Well need to debug more.

**Comment by jakirkham** [comment]
Ah ok. Should we reopen then?

**Comment by beckermr** [comment]
Yeah we'll have to do something. We could make sure to run the bot on a newer glibc for now.

**Comment by beckermr** [comment]
I saw this issue with another solver option. We are using semi-internal mamba apis and these probably bypass at least some of the configuration we are used to using.

**Comment by beckermr** [comment]
I also need to put in a fix to delete any virtual packages that are explicitly listed in the requirements when checking them.

**Comment by beckermr** [comment]
We still have packages blocked. I’m gonna try a few more things. Then we should turn off mamba solver checks for this migration.

**Comment by beckermr** [comment]
So setting the override vars for glibc does not seem to help mamba. We are using internal APIs so this might be the issue. 

cc @wolfv for any tips

**Comment by beckermr** [comment]
The error we are getting is 

```
2020-10-15 10:07:21,997 WARNING  conda_forge_tick.mamba_solver || MAMBA failed to solve specs 

['gcc_linux-64 7.*', 'gxx_linux-64 7.*', 'nvcc_linux-64 11.0.*']

for channels 

['conda-forge', 'defaults', 'msys2', 'conda-forge', 'defaults']

The reported errors are:

Encountered problems while solving.
Problem: nothing provides __glibc >=2.17 needed by nvcc_linux-64-11.0-he443bbd_6

```

**Comment by mariusvniekerk** [comment]
we almost have a fix for this ready

**Comment by jakirkham** [comment]
Looks like it just came through ( https://github.com/conda-forge/cupy-feedstock/pull/75 ). Thanks all! 😄 🎉

**Comment by beckermr** [comment]
Great! Still fighting some bugs for other things but glad this one worked!

**Comment by leofang** [comment]
Looks like magic to me! Thanks for the hard work everyone!
