### ISSUE TITLE
Removing `libtike-cufft` from CUDA 11.0 migration

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1209]
Recently the maintainer asked for `libtike-cufft` to be archived ( https://github.com/conda-forge/libtike-cufft-feedstock/pull/7 ). So I think we can go ahead and remove this from the CUDA 11.0 migration. Not sure if this will automatically happen when the migration completes, in which case we could ignore this until things are cleaned up naturally.

**Comment by beckermr** [comment]
It should happen on its own. However, it might take a few hours for all of our bots to pick up this change.

**Comment by jakirkham** [comment]
Looks like this got cleared out. Closing...
