### ISSUE TITLE
parse_version does not like R recipes

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#123]
```python
import networkx as nx
g = nx.read_gpickle('graph.pkl')
a = g.node['r-rprojroot']
print(a['version'])
'1.3_2'
print(a['new_version'])
'1.2'
print(parse_version(a['version']) <= parse_version(a['new_version']))
True
```
It seems that `parse_version` thinks that underscores do something odd.
However, I can replace `_` by `.` in the version and it seems to work.

**Comment by justcalamari** [comment]
`parse_version` checks for valid PEP 440 versions, which `1.3_2` is not, so it treats it as a legacy version, which will always be less than a valid PEP 440 version.

**Comment by CJ-Wright** [comment]
Maybe we should be using a conda version parser? Hopefully it would handle the underscore properly.
