### ISSUE TITLE
r-corpor breaks things

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#124]
It seems that there are to urls with `Archive` in them. I guess we could just take the first one then.
https://github.com/conda-forge/r-corpcor-feedstock/blob/master/recipe/meta.yaml

**Comment by justcalamari** [comment]
How exactly are things breaking?

**Comment by CJ-Wright** [comment]
We get out a list of urls where we were expecting a string. Note that this just causes problems with that recipe, the rest of the bot is fine.

**Comment by CJ-Wright** [comment]
Attn: @ocefpaf

**Comment by ocefpaf** [comment]
> It seems that there are to urls with Archive in them. I guess we could just take the first one then.

These are the URLs in the ``meta.yaml``.

```yaml
  url:
    - https://cran.r-project.org/src/contrib/corpcor_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/corpcor/corpcor_{{ version }}.tar.gz
```

This seems OK to me and I guess that the `Archive` URL will be invalid for all new versions, right?

https://cran.r-project.org/src/contrib/Archive/corpcor/corpcor_1.6.9.tar.gz should return an 404 until a new version exists and 1.6.9 is archived.

**Comment by CJ-Wright** [comment]
This was updated 6 days ago to fix the meta.yaml after this issue went up.

**Comment by ocefpaf** [comment]
Awesome!
