### ISSUE TITLE
Security Issue. Non project maintainer merged feedstock upgrade

### ISSUE THREAD

**Issue by rlizzo** [regro/cf-scripts#1243]
Hi all, 

I'm the maintainer of the hangar condo-forge feedstock. I just received the notification that the upgrade bot created a PR for package version upgrade to python 3.9, and then a few hours later someone who is not on the maintainer list merged this PR? 

https://github.com/conda-forge/hangar-feedstock/pull/16

Is this an authorized member? And why was it merged without the permission of the maintainers? I have not reviewed the change or tested the installation yet. If there are any issues or security concerns, the upgrade / package needs to be pulled.

**Comment by ocefpaf** [comment]
I merged it. Core conda-forge member can merge in any feedstock. That is not a security risk. That is probably your first Python migration, we do that every year :stuck_out_tongue_closed_eyes:

**Comment by beckermr** [comment]
I do not want to minimize your legitimate concerns, however. We have struggled with how quickly core should merge PRs.

cc @regro/auto-tick

**Comment by rlizzo** [comment]
Thanks for the quick reply. So long as there is no security issues I'm all good. Maybe make a note as to not freak out a new maintainer like myself? Also, 4 hours is a bit of a short window between the PR and a merge

**Comment by CJ-Wright** [comment]
@rlizzo I'm hopeful that we'll have some policy documents written down that clarifies this soon. I'm sure your input would be greatly appreciated when that policy is discussed. I think the PR will go into https://github.com/conda-forge/conda-forge.github.io and will be open for comments and suggestions.

**Comment by rlizzo** [comment]
@CJ-Wright I'll keep an eye out for it. Happy to help in any way I can!

**Comment by beckermr** [comment]
@CJ-Wright @ocefpaf Whatever policy we end up with, we should add a note to the PR text for bot PRs saying what the timeframe is and what may happen after that timeframe.
