### ISSUE TITLE
Bot opens multiple "Rebuild for python39" PRs

### ISSUE THREAD

**Issue by bsipocz** [regro/cf-scripts#1251]
This afternoon 3 of those got opened for astropy. 

https://github.com/conda-forge/astropy-feedstock/pull/80
https://github.com/conda-forge/astropy-feedstock/pull/79
https://github.com/conda-forge/astropy-feedstock/pull/78

**Comment by beckermr** [comment]
Yup. We're having a bit of trouble with it. This should be fixed now. Sorry for the trouble and thank you for the bug report!

**Comment by beckermr** [comment]
You may get one more pr.

**Comment by bsipocz** [comment]
No trouble at all, happy to see you already fixed this. Thanks!

Should we just close the n-1 of those PRs, or better to leave them all open? (I don't mind either way, whatever is more useful for you)

**Comment by beckermr** [comment]
Once any one of them is merged, close the rest.

**Comment by beckermr** [comment]
fixed! closing!
