### ISSUE TITLE
duplicate PRs for new feedstocks

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#1269]
This feedstock https://github.com/conda-forge/mcalf-feedstock/pulls

got PRs 

https://github.com/conda-forge/mcalf-feedstock/pull/2
https://github.com/conda-forge/mcalf-feedstock/pull/1

both for python 3.9. It appears the PR json was not put in the node attrs when the first one was made.

**Comment by napetrov** [comment]
Same for  daal4py 
https://github.com/conda-forge/daal4py-feedstock/pull/3
https://github.com/conda-forge/daal4py-feedstock/pull/5

**Comment by beckermr** [comment]
Thanks @napetrov!
