### ISSUE TITLE
Status of bot-rerun requests during downtime

### ISSUE THREAD

**Issue by adrianeboyd** [regro/cf-scripts#1289]
Hi, I tried to get a python39 upgrade PR to rerun when it looks like the bot was down for maintenance last week and I'm not sure what the status is right now. The original PR is here: https://github.com/conda-forge/cython-blis-feedstock/pull/28

I'm not sure if it's queued somewhere and there's just a backlog or if the request is lost. Is there somewhere I can see the status or manually request that particular PR be rerun?

Thanks!

**Comment by CJ-Wright** [comment]
It looks like the migration was marked for rerun, see here: https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/cython-blis.json#L201

It seems that it is not solvable, meaning that upstream packages haven't been created or there is some other issue with dependency resolution https://conda-forge.org/status/#python39

**Comment by adrianeboyd** [comment]
Thanks for the reply! I don't really understand why the original PR didn't run into the same issues because the only recent changes were version bumps, but after modifying things, how do I get it to rerun? Does it automatically retry if there are changes to the feedstock?

**Comment by beckermr** [comment]
We had a break on solver checking. The above PR might have been issued during the break?

**Comment by adrianeboyd** [comment]
Thanks, it seems to be working now. I updated the numpy pins and rebuilt, and then the PR was reissued, so I'm guessing that fixed the problem.
