### ISSUE TITLE
Make PRs for back tags

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#130]
It may be good to create PRs for updates to older tags (eg PostgresSQL long term support security updates).

**Comment by CJ-Wright** [comment]
Attn: @ocefpaf

**Comment by ocefpaf** [comment]
> It may be good to create PRs for updates to older tags (eg PostgresSQL long term support security updates).

We have the LTS packages in a branches, so it would be a matter of:
- make the bot read the branch;
- build the concept of updating within a version range: we want it to update django 1.9.x and not 2.x in the branch.

Makes sense?

**Comment by CJ-Wright** [comment]
Right, but we also need a way to get the new tag from the upstream. We can cache all the tags from GitHub, but for most of the other places we only get the latest tag information.

The updating in a version range may be a good application of the dedicated bot subsection of `extra`.

**Comment by beckermr** [comment]
Plan for doing this

to do:

- [ ] support opt-in via list of branches in conda-forge.yml
- [ ] have bot issue PRs against those branches
