### ISSUE TITLE
Reset arch migration status for a package

### ISSUE THREAD

**Issue by adrianeboyd** [regro/cf-scripts#1301]
How can I get the arch migration to reset its status for a package?

I closed and reopened this PR a few times to rerun the CI after dependencies were updated and now it seems to think it's done rather than in-pr (which is my best guess for why the `bot-rerun` label didn't do anything, anyway):

https://github.com/conda-forge/spacy-feedstock/pull/86

I would like it to rerun the bot for this migration, but I'm not sure what to do? (Sorry if this isn't the right place to ask!)

**Comment by beckermr** [comment]
This is the right spot to open an issue. We'll need to make a PR the underlying data and change the PR status along with possibly adding a label. @CJ-Wright can give exact instructions.

**Comment by CJ-Wright** [comment]
Please put up a PR changing the value [here](https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/spacy.json#L481) to the current timestamp

**Comment by beckermr** [comment]
It'd be nice to allow the admin bot to do this. Would you be ok giving it write permissions to the bot data @CJ-Wright?

**Comment by CJ-Wright** [comment]
I think that could be ok. I'm a little worried about conflicts, esp if the bot and admin disagree on the timestamp (eg. someone asks for rerun and an admin bot thing). Maybe it is time to let the admin bot handle all the reruns, if rerun is added on the PR after it is closed would be the same as if it was open. That would eliminate a job for us, which would be nice. We might also consider PR updating being done by the admin bot completely, since then the autotick bot would become much more responsive.

**Comment by beckermr** [comment]
Right, we need smaller PR json blobs before we can use the bot to push them.

**Comment by beckermr** [comment]
I didn't follow the worry you have with conflicts though.

**Comment by CJ-Wright** [comment]
If the autotick bot rerun system and the admin bot both try to write to the same field, will we run into git conflicts?

**Comment by beckermr** [comment]
Hmmmm. Maybe we need instead a "revive PR" command. We could have the admin bot push updates directly to the bot PR json blobs. This way the bot itself would process the labels and we can avoid anyone writing to the bot data where it might conflict.

**Comment by CJ-Wright** [comment]
That could work, especially as a transitional state to webservice handling the prs entirely.

**Comment by beckermr** [comment]
Should we have the bot add a "dead to me" label to bot PRs so people understand they are no longer under consideration?

**Comment by beckermr** [comment]
It can do this when it finds a closed one, for example.

**Comment by beckermr** [comment]
Ah actually it cannot do this. Permissions. NVM

**Comment by adrianeboyd** [comment]
What is the format of the timestamp?

**Comment by CJ-Wright** [comment]
Float time since epoc

**Comment by CJ-Wright** [comment]
`python -c print(time.time)` I think should do it

**Comment by adrianeboyd** [comment]
Issue resolved by https://github.com/regro/cf-graph-countyfair/pull/27.
