### ISSUE TITLE
Migration metadata for dependencies seems off

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#1331]
There has been some anecdotal evidence of the pypy37 migrator opening PRs before all dependencies are built (e.g. pandas was opened without numpy having been built, https://github.com/conda-forge/osqp-feedstock/pull/33 without scipy having been built).

In contrast to numpy, scipy is at least shown under "awaiting parents" on the migrator page, but looking at a "reverse search" of the listed immediate children reveals that the migrator thinks that scipy depends on:
* tbb
* psycopg2
* typed-ast
* pandas

However, the actual [recipe](https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/meta.yaml) depends on none of them!

**Comment by beckermr** [comment]
The dependents listed on the page do not have to be direct dependents. The migrator graph skips things which do not need to be rebuilt. 

Please send links for the pandas pr.

**Comment by h-vetinari** [comment]
> The dependents listed on the page do not have to be direct dependents. The migrator graph skips things which do not need to be rebuilt.

scipy does not depend (directly or indirectly) on pandas or a postgresql-adapter - in fact, I believe all scipy dependencies** have already been built for pypy37. I could try to show that with a manual PR, but wanted to wait for the migrator (and then saw how much was still pending)

** From the [recipe](https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/meta.yaml), including test-deps:
cython, numpy, pybind11, setuptools, pytest; the others are noarch (pip, mpmath, pytest-xdist)

> Please send links for the pandas pr.

https://github.com/conda-forge/pandas-feedstock/pull/106

**Comment by beckermr** [comment]
It appears that the graph is right. The hypothesis feedstock has test deps on pandas and some other downstream packages:

https://github.com/conda-forge/hypothesis-feedstock/blob/master/recipe/meta.yaml#L31

**Comment by beckermr** [comment]
When the bot finds cycles, it releases all PRs in the cycle and lets maintainers sort it out. This is why some things may appear out of order sometimes.

**Comment by h-vetinari** [comment]
> It appears that the graph is right. The hypothesis feedstock has test deps on pandas and some other downstream packages:
> 
> https://github.com/conda-forge/hypothesis-feedstock/blob/master/recipe/meta.yaml#L31

This was about the pandas one, right? That one's a bit special, because (for some reason) `numpy` was not in scope of the migrator at all.

But in the case of scipy, it doesn't depend on hypothesis, so I'm not sure how that dependency on pandas (much less psycopg2) comes about.

Finally, the osqp-[example](https://github.com/conda-forge/osqp-feedstock/pull/33) shows a different sort of problem - namely where there was a dependency on scipy (as yet unbuilt), and the PR still got raised.

**Comment by beckermr** [comment]
The bot uses the full graph. So for scipy, it depends on numpy. numpy depends on hypothesis. Finally, hypothesis depends on pandas and django. 

IDK about osqp.

**Comment by h-vetinari** [comment]
Since hypothesis is `noarch`, shouldn't the migrator skip that in determining the cycles for a python-migration? Or is something like that not implemented yet?

> IDK about osqp.

Maybe it got caught up in a very large cycle?

**Comment by beckermr** [comment]
The bot does skip noarch but IDK how that works with pypy.

**Comment by beckermr** [comment]
One detail here is that the bot won't migration noarch packages but it will look at the dependents of them, including the test dependencies.
