### ISSUE TITLE
Scipy "not solvable" in pypy37 migration

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#1338]
On the [status page](https://conda-forge.org/status/) for the pypy37 migration, `scipy` has been stuck as "unsolvable" for >1 week (actually, it has already been built in https://github.com/conda-forge/scipy-feedstock/pull/155 to break some circular dependencies at the time) - in fact, there are now two `scipy` entries in the "Not-Resolvable" section, both of which read:
```
_Error_: not solvable: master:
osx_arm64_python3.8.____cpython: Encountered problems while solving.
Problem: nothing provides requested libgfortran5 >=11.0.0.dev0
osx_arm64_python3.9.____cpython: Encountered problems while solving
Problem: nothing provides requested libgfortran5 >=11.0.0.dev0 
```

I don't understand where the `11.0.0.dev0` is coming from, because that restriction is not in the [recipe](https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/meta.yaml).

In any case, this is needlessly keeping a lot of packages from being migrated, but I don't know how it can be fixed.

**Comment by beckermr** [comment]
This needs the attention of @isuruf i think. Nobody else knows the llvm stack for OS X arm better.

**Comment by h-vetinari** [comment]
Just saw that @mattip already opened: https://github.com/conda-forge/scipy-feedstock/issues/156

**Comment by mattip** [comment]
Thanks. Is there a way to easily restart the feedstocks in the PyPy37 migration marked "not solvable" ? Or should I go through and mark them with `@conda-forge-admin, please rerun bot` ?

**Comment by beckermr** [comment]
You don't need to do anything. The bot never issues those prs so now it will. This will solve scipy but might not solve the others.
