### ISSUE TITLE
Migrate multiple outputs simultaneously

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#1346]
It can be the case that a single recipe makes multiple pkgs that are pinned (eg. gdal and libgdal) the bot should then issue a single migration that covers both those pkgs at the same time.

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/922

CC @ocefpaf (I wasn't certain if we had this as an issue already or not, if we have it please feel free to close as a dup)

**Comment by ocefpaf** [comment]
I don't think we do. Thanks for opening it.

**Comment by akrherz** [comment]
Just an annoying bump of this issue as it continues to impact GDAL for example conda-forge/conda-forge-pinning-feedstock#5916

cc: @isuruf

**Comment by isuruf** [comment]
Hopefully fixed in https://github.com/regro/cf-scripts/pull/2706.

**Comment by isuruf** [comment]
Pytorch PR works https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6015. Closing
