### ISSUE TITLE
Missing Dask 2021.2.0 update

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1347]
Noticed that a PR was added to update `distributed` to the new version, but have not seen one for `dask-core`, which it depends on. It's only been 4hrs since it was pushed to PyPI. So am a little unclear if things are just taking a bit and should be patient or if the fact that the `distributed` update PR getting submitted while the `dask-core` one is missing indicates a problem. Anyways raising here for some guidance and (if there is an issue) more info. Thanks!

cc @jrbourbeau

**Comment by CJ-Wright** [comment]
https://conda-forge.org/status/#version_updates Its in there

**Comment by CJ-Wright** [comment]
(under queued)

**Comment by jakirkham** [comment]
Ah did not know about that feature. There are all kinds of gems hiding in the status page. Thanks CJ! 😄

**Comment by jakirkham** [comment]
...and the bot has since opened it ( https://github.com/conda-forge/dask-core-feedstock/pull/90 ) 🎉 Thanks again CJ. Will go ahead and close this out

**Comment by jakirkham** [comment]
Reopening as it now appears we are missing the `dask` update PR (different from `dask-core`). Not seeing it in the queue on the status page

**Comment by jakirkham** [comment]
nvm it showed up ( https://github.com/conda-forge/dask-feedstock/pull/135 )
