### ISSUE TITLE
Put rever info into bot PR body

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#136]
It might be good to put information about `rever` into the body of the bot's PRs. The bot is based on rever's conda-forge activity and rever has the capability to automatically issue PRs into conda-forge feedstocks during the release process. If more maintainers/developers moved over to rever it may give faster turn around (and reduce bot load once #16 is finished).

Attn: @justcalamari @scopatz

**Comment by scopatz** [comment]
Yeah much agreed

**Comment by CJ-Wright** [comment]
Maybe rever should have a wizard (for standard setup). I'm not excited about writing it but it may make it a bunch more accessible, and give the "right" behavior out of the box.

**Comment by scopatz** [comment]
Sure, there are tools for building wizards in xonsh itself.  Shouldn't be super hard.
