### ISSUE TITLE
Build number not reset during version bump

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1361]
Looks like this version update PR didn't have the build number reset to `0`.

https://github.com/conda-forge/ipykernel-feedstock/pull/76#pullrequestreview-594796580

**Comment by bollwyvl** [comment]
Probably a false alarm, as I manually applied some merging https://github.com/conda-forge/ipykernel-feedstock/pull/75.

**Comment by beckermr** [comment]
Yes I think this is likely something else. The code that does this is old and hasn't seen any changes recently that I know of.

**Comment by jakirkham** [comment]
Ok feel free to close then. Just thought it was peculiar as it showed up when GitHub rendered the diff as well

**Comment by beckermr** [comment]
Let's close for now. I'll reopen if I see it again.
