### ISSUE TITLE
Handle recipes with all outputs noarch

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#1362]
Currently we don't consider pkgs with all outputs noarch to be noarch, see: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/arch.py#L98

This causes things like `black` to get hit with recompile migrators where they are not needed

**Comment by CJ-Wright** [comment]
Maybe we should make aggregate noarch values at the top level of the data model?

**Comment by beckermr** [comment]
I thought we had code to do this in other places in the bot.

**Comment by CJ-Wright** [comment]
ah yes https://github.com/regro/cf-scripts/blob/0e08eef24ff6d94aa1122685299bf9c4afde8ea4/conda_forge_tick/migrators/migration_yaml.py#L428

I guess we just need to use that in arch, I'll put up the PR
