### ISSUE TITLE
Latest PyPI version not making it to conda-forge

### ISSUE THREAD

**Issue by ma-sadeghi** [regro/cf-scripts#1375]
We've recently released openpnm-2.7.0 on PyPI, but it seems it hasn't made its way to conda-forge yet. I'd really appreciate it if you could look into this. Here's a link to the feedstock: https://github.com/conda-forge/openpnm-feedstock/

**Comment by beckermr** [comment]
It looks like upstream shipped 2.8.0 by accident maybe? The bot found this version and so was not shipping 2.7.0.

**Comment by ma-sadeghi** [comment]
@beckermr Thanks for your quick reply. Yes, indeed. We accidentally released 2.8.0, but quickly deleted it from PyPI.
