### ISSUE TITLE
Garbled comment regarding bot-rerun

### ISSUE THREAD

**Issue by rtburns-jpl** [regro/cf-scripts#1377]
I get the gist of what it's trying to say, but I think it stumbled over the words, haha.
https://github.com/conda-forge/isce2-feedstock/pull/33#issuecomment-791772990

**Comment by CJ-Wright** [comment]
What do you think it should say?

**Comment by rtburns-jpl** [comment]
> I see that this PR has conflicts and I'm the only committer I'm going to close this PR and will make another one as appropriate.

Seems to need some punctuation? Wasn't sure if this was the intended output. How about "I see that this PR has conflicts, and I'm the only committer. I'm going to close this PR and will make another one as appropriate."

> This was generated by

...?

**Comment by rtburns-jpl** [comment]
Here's what an older comment looked like: https://github.com/conda-forge/isce2-feedstock/pull/25#issuecomment-711431165

It still has the "This was generated by" [...] though

**Comment by CJ-Wright** [comment]
The this was generated is a bug, we lost track of the url somewhere.

The version you have above with punctuation seems good, any interested in putting up a PR?
