### ISSUE TITLE
Bot not progressing on migrations with build-deps of r-base/osx-arm64

### ISSUE THREAD

**Issue by xhochy** [regro/cf-scripts#1379]
Normally, we happily progress with migrations past any non-existing build dependencies on cross-compiled projects. Somehow that bot had issues with `r-base` in the `pcre2` migration:

```
r-base (2) Error: not solvable (bot CI job): master: ['osx_arm64_: Encountered problems while solving.\nProblem: nothing provides requested texlive-core\nProblem: nothing provides requested openjdk\n']
```

**Comment by beckermr** [comment]
We may need to adjust the logic here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/mamba_solver.py#L759

We need to run the solver for the build env to get the run exports, but for cross-compiling, we should ignore the solvable result. Does anyone know which attribute on the conda-build metadata indicates that something is cross-compiling across subdirs?

**Comment by xhochy** [comment]
> Can you post the link to the github actions CI job?

https://github.com/regro/autotick-bot/runs/2067156860?check_suite_focus=true

**Comment by xhochy** [comment]
> We may need to adjust the logic here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/mamba_solver.py#L759
> 
> We need to run the solver for the build env to get the run exports, but for cross-compiling, we should ignore the solvable result. Does anyone know which attribute on the conda-build metadata indicates that something is cross-compiling across subdirs?

`target_platform != build_platform`

**Comment by beckermr** [comment]
We wouldn't have that info around when doing the tests. Maybe we can pull the config info from the feedstock conda-forge.yml and use that.
