### ISSUE TITLE
Allow PyPy to be skipped

### ISSUE THREAD

**Issue by henryiii** [regro/cf-scripts#1386]
Some packages (like Numba) do not support PyPy and have no immediate intentions of doing so (to the best of my knowledge). This causes an issue with the PyPy migration - a PR left open (and resubmitted every so often on code changes). If the package adds a skip for PyPy, as recommended in the [docs](https://conda-forge.org/docs/maintainer/knowledge_base.html#pypy-builds), then the incoming PR will just rename some CI files (and bump NumPy to 1.17) and "pass", making it inviting to merge. Currently, I believe (also from @isuruf's comments on gitter) this will set off PRs to all downstream recipes (58 of them in the case of Numba; https://github.com/conda-forge/numba-feedstock/pull/76 inspired this issue). Unlike a Python migration, not all packages will support PyPy; this is similar (IMO) to Windows support; not all packages support windows, but there are not open PRs trying to add Windows support on all those recipes.

Some ideas: There should be some way to either respect the PyPy skip for a parent package the migration, or to add a list of packages that do not support PyPy. I think the migration should be "adding the ability to support PyPy", just like there's an ability to support Windows.

PS, slighly more general: If the migration could respect the PyPy skip, then it could still open the 58 PRs, but add a pypy skip to those too. Then whenever a parent "unskips" something, a mini-migration could open PRs to dependents to unskip the same thing.

**Comment by jakirkham** [comment]
Yeah I think this is a particular case of generally opting out of migrations ( https://github.com/regro/cf-scripts/issues/1044 )

**Comment by beckermr** [comment]
We have not come up with a good solution for declining a PR but we do have two ideas to solve this issue. 

1. We can add a config variable to the `bot` section of the `conda-forge.yml` that would opt-out a feedstock of getting any remade PRs.
2. We can change the bot to never remake a PR marked as a draft. We could support both a draft label and the draft status in the GitHub API.

**Comment by jakirkham** [comment]
I think another piece (and please correct me if I'm misunderstanding this) is the bot stops issuing PRs if a certain number (I believe 3) have been opened on the feedstock and not addressed. Would it be possible to exclude draft PRs from that count?

**Comment by beckermr** [comment]
That is only for version bumps. Separate thing.
