### ISSUE TITLE
Reset version bot after spurious upstream tag

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#1392]
For allennlp-optuna, the package was at 0.1.3, then a spurious tag 1.4.0 got created and deleted (but [picked up](https://github.com/conda-forge/allennlp-optuna-feedstock/pull/1) by the bot in that time), then 0.1.4 got done [manually](https://github.com/conda-forge/allennlp-optuna-feedstock/pull/2), but it seems that the bot cannot "forget" the spurious tag, and the error persists under https://conda-forge.org/status/#version_updates.

It would be nice to make the bot forget this spurious tag, so we don't have to manually do all the releases, cf. https://github.com/conda-forge/allennlp-optuna-feedstock/issues/3.

Also xref #1341

**Comment by beckermr** [comment]
If you make a PR removing the metadata entries for 1.4.0 here, https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/allennlp-optuna.json#L146, it should work.

**Comment by h-vetinari** [comment]
Thanks a lot for the quick response! :)

**Comment by h-vetinari** [comment]
Ran into a problem: https://github.com/regro/cf-graph-countyfair/issues/33
