### ISSUE TITLE
Bot does not discover and bump new versions of neptune-client

### ISSUE THREAD

**Issue by PiotrJander** [regro/cf-scripts#1395]
Creating an issue here as requested:

>We may need to change some of the bot metadata to get it going again. Please make an issue on regro/cf-scripts and I will try and get to it today.

https://github.com/conda-forge/neptune-client-feedstock/issues/42

**Comment by beckermr** [comment]
solved by https://github.com/regro/cf-graph-countyfair/pull/35 hopefully. Closing for now.

**Comment by PiotrJander** [comment]
Just reposting from the source issue:

>Thanks for your help, but just letting you know that the bot has not opened a new PR in neptune-client-feedstock, so it doesn't seem like this solved the problem.

**Comment by beckermr** [comment]
Closing as this appears to be an error in the recipe.
