### ISSUE TITLE
hash error on r-fomula

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#140]
It seems that the bot thought that the correct url for `r-formula` is hash failed at https://cran.r-project.org/src/contrib/Formula_1.2_3.tar.gz

The actual url is https://cran.r-project.org/src/contrib/Formula_1.2-3.tar.gz

**Comment by justcalamari** [comment]
I think this is fixed. @CJ-Wright

**Comment by CJ-Wright** [comment]
great!
