### ISSUE TITLE
How to add regro-cf-autotick-bot to feedstock?

### ISSUE THREAD

**Issue by zzhengnan** [regro/cf-scripts#1408]
Hi team. I'm looking to add `regro-cf-autotick-bot` to the [feedstock for my package](https://github.com/conda-forge/iscan-feedstock) but couldn't find instructions for doing so. Below are the resources I've consulted, to no avail
- The section in the conda-forge documentation that talks about the bot: https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#pushing-to-regro-cf-autotick-bot-branch
- Documentation for `cf-scripts`: https://regro.github.io/cf-scripts/index.html

Please advise. Thanks!

**Comment by beckermr** [comment]
The bot is added to all feedstocks automatically. If you are not getting PRs you think you should be getting, check the status page for any errors for your feedstock or comment on this issue and we can help!

**Comment by zzhengnan** [comment]
Thanks for the quick response, Matthew! Can you clarify what you mean by the "status page"?

For my feedstock, all the PRs to date have been opened manually by myself, as seen [here](https://github.com/conda-forge/iscan-feedstock/pulls?q=is%3Apr+is%3Aclosed).

**Comment by beckermr** [comment]
https://conda-forge.org/status/

Scroll down to the version section and see if your feedstock is there. 

Note that it takes ~4 hours for the bot to pickup new versions, so if your waiting less than that, you won't see a PR.

**Comment by zzhengnan** [comment]
Ahh I didn't know about the 4-hour lag. That must've been the reason, as I typically open a PR immediately after a new release of my package is published on PyPI.

Closing this issue for now. Will reopen if I run into anything unexpected during the next release. Thanks again for the help!
