### ISSUE TITLE
2 update PRs for same version?

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1418]
Recently 2 update PRs were issued for the same package version. Also they were submitted to the same branch. They were submitted ~1hr apart. Unclear as to why 2 PRs were created. Have linked them below:

* https://github.com/conda-forge/arrow-cpp-feedstock/pull/481
* https://github.com/conda-forge/arrow-cpp-feedstock/pull/482

As a side note, the tag appears to have been created 6 days ago ( https://github.com/apache/arrow/releases/tag/apache-arrow-5.0.0 )

cc @xhochy (for awarenesses)

**Comment by beckermr** [comment]
Not sure on this one.

**Comment by beckermr** [comment]
We somehow had two bot jobs going at once. No idea how that happened, but I killed one. We likely issued some duplicate PRs but that's fine.

**Comment by beckermr** [comment]
closing for now. if you see more, feel free to reopen!

**Comment by jakirkham** [comment]
Hmm...ok. So probably this is wrong, but will share this thought anyways...

Wonder if it was just because it choked on the Jinja syntax issues ( https://github.com/regro/cf-scripts/issues/1419 ) and resubmitted (thinking the previous PR failed?). Really just a guess. Maybe we can let this sit here and just keep an eye and see if it reoccurs?

**Comment by beckermr** [comment]
Literally, two copies of the bot were running at the same time, both making the same PRs. I don't think the jinja2 thing was related at all.
