### ISSUE TITLE
Inlining of `track_features` with Jinja breaks re-rendering

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1419]
Below is a diff of the change made. Also a link to the particular change in the PR for more details

```diff
-      track_features:
-        {{ "- arrow-cuda" if cuda_enabled else "" }}
+      track_features: {{ "- arrow-cuda" if cuda_enabled else "" }}
```

https://github.com/conda-forge/arrow-cpp-feedstock/pull/482#pullrequestreview-717488444

**Comment by beckermr** [comment]
This cannot be fixed. Using jinja2 in this way is clearly fragile since different valid expressions of the yaml result in different recipes. You'll have to change the recipe. 

I suggest

```
track_features: {{ "[arrow-cuda]" if cuda_enabled else "" }}
```

**Comment by jakirkham** [comment]
Hehe was just about to say we may be doing a weird thing and ask for suggestions. Agree that looks better :)

**Comment by beckermr** [comment]
I am going to close this issue for now since we cannot fix this. Feel free to reopen.
