### ISSUE TITLE
Speed up bot

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#142]
It might be possible to speed up the bot with multithreading/futures. It seems that many of the operations the bot does (especially for 0-2) are IO driven, mostly reading webpages via `requests`. This seems like something that could be sped up by multithreading. 

https://docs.python.org/3/library/concurrent.futures.html#threadpoolexecutor-example

**Comment by CJ-Wright** [comment]
As a side note it would be nice to track the execution time for each part of the bot so we can know if we actually helped things or not.

**Comment by dougalsutherland** [comment]
https://github.com/ross/requests-futures might be useful.

**Comment by isuruf** [comment]
https://github.com/regro/cf-scripts/issues/143 will make things a lot faster

**Comment by CJ-Wright** [comment]
I think things are reasonably fast at this point.
