### ISSUE TITLE
Environment variable CONDA_BUILD_CROSS_COMPILATION is unbound

### ISSUE THREAD

**Issue by bencomp** [regro/cf-scripts#1424]
In several feedstocks I noticed that build pipelines started by PRs fail with the message `/Users/runner/miniforge3/conda-bld/libgsf_1627916042774/work/conda_build.sh: line 14: CONDA_BUILD_CROSS_COMPILATION: unbound variable`. I'm mostly interested in the OSX ARM migration and looked at [how e.g. libexif failed](https://github.com/conda-forge/libexif-feedstock/pull/1#issuecomment-893270267).

@isuruf fixed this error for `libexif`: https://github.com/conda-forge/libexif-feedstock/pull/1/commits/9c4ab47f286b3d8e3d9de492bc857bb9424b320d – but other feedstocks are still failing. I wonder if the migration script needs to be adjusted near:
https://github.com/regro/cf-scripts/blob/2db24a30003867fbf4d19b2bdf4ce792a51a6f00/conda_forge_tick/migrators/cross_compile.py#L130

I'm not sure what the relationship is between `[[ "${CONDA_BUILD_CROSS_COMPILATION}" != "1" ]]` (note `!=`, sometimes changed to `==` I think) and `[[ "${HOST_PLATFORM}" != "${BUILD_PLATFORM}" ]]`.
But it seems that if the former is used, changing to `[[ "${CONDA_BUILD_CROSS_COMPILATION:-}" != "1" ]]` prevents the build error.

Again, this is still very outside my comfort zone, so I may be completely off here.

**Comment by isuruf** [comment]
`"${CONDA_BUILD_CROSS_COMPILATION:-}"` sounds good. Can you send a PR?

> I'm not sure what the relationship is between [[ "${CONDA_BUILD_CROSS_COMPILATION}" != "1" ]] (note !=, sometimes changed to == I think) and [[ "${HOST_PLATFORM}" != "${BUILD_PLATFORM}" ]].

`build_platform` was added to conda-build recently and `CONDA_BUILD_CROSS_COMPILATION` predates that
