### ISSUE TITLE
Almost identical results in wildly different CI

### ISSUE THREAD

**Issue by tdegeus** [regro/cf-scripts#1430]
I have two almost identical multi-output feedstocks: 
* https://github.com/conda-forge/goosefem-feedstock
* https://github.com/conda-forge/qpot-feedstock

Yet, the CI output is widely different: 
* https://github.com/conda-forge/goosefem-feedstock has just four runners
* https://github.com/conda-forge/qpot-feedstock has many runners, one per Python version

Although things work, this seems all a bit arbitrary to me...

**Comment by beckermr** [comment]
This issue needs to be made on conda-forge/conda-smithy

**Comment by beckermr** [comment]
I am going to close for now. Please reopen on conda-smithy.
