### ISSUE TITLE
matplotlib marked "waiting for parents" on the pypy windows migration, but the package is merged

### ISSUE THREAD

**Issue by mattip** [regro/cf-scripts#1434]
On the [status page for windows pypy migration](https://conda-forge.org/status/#pypy37-windows), matplotlib is still found as the top package under "Awaiting parents". A PR to merge the package manually was accepted, so actually matplotlib is "done". I asked on gitter how to solve this, and made a PR https://github.com/regro/cf-graph-countyfair/pull/38 following that suggestion. Was this the correct thing to do?

**Comment by beckermr** [comment]
Thanks for the note! I will check into it.

**Comment by beckermr** [comment]
The bot internally says that matploitlib depends on pyqt and this PR is still open: https://github.com/conda-forge/pyqt-feedstock/pull/102

What is going on here?

**Comment by beckermr** [comment]
OHHHH. https://github.com/conda-forge/matplotlib-feedstock/pull/298/files#diff-f3725a55bf339595bf865fec73bda8ac99f283b0810c205442021f29c06eea9aR84

@CJ-Wright any ideas on how to deal with this correctly?

**Comment by mattip** [comment]
Thanks. The good news is that matplotlib has moved off of "awaiting parents". The bad news is that it has moved to "awaiting PR".

**Comment by beckermr** [comment]
Awesome! This means it is working. Wait a few more hours for the bot to complete its latest run and it should get one or be marked as done. The bot has to try it before it can say it is done.

**Comment by beckermr** [comment]
This appears to have worked! Let us know if you find any more things like this @mattip!

**Comment by mattip** [comment]
Thanks

**Comment by mattip** [comment]
Is there a way to figure out what the "parents" of h5py are? In the [windows pypy migration](https://conda-forge.org/status/#pypy37-windows) it is the top "awating parents" feedstock, but I don't see it anywhere on the children of the "in-pr" feedstocks.

**Comment by beckermr** [comment]
We'll have to inspect the graph by hand.

**Comment by mattip** [comment]
> We'll have to inspect the graph by hand.

Where is the graph?

**Comment by beckermr** [comment]
The graph the bot produces which tells it what to do. I am sorry this has been delayed. There is a notebook here:

https://github.com/regro/cf-graph-countyfair/blob/master/example.ipynb

but I don't have a ton of time to look.

**Comment by beckermr** [comment]
Ahhhh. PRs for windows are only issued if the earlier pypy37 PR was merged. It appears it was not for h5py: https://github.com/conda-forge/h5py-feedstock/pull/95

**Comment by mattip** [comment]
Thanks. So the "parent" it is waiting for is actually pypy-linux. Good to know.
