### ISSUE TITLE
bot not picking up an RC tag

### ISSUE THREAD

**Issue by adrinjalali** [regro/cf-scripts#1437]
I had to open this PR (https://github.com/conda-forge/scikit-learn-feedstock/pull/160) because the bot didn't pick up the RC tag (1.0.rc1) on a release branch (1.0.X).

@jakirkham said (https://github.com/conda-forge/scikit-learn-feedstock/pull/160#issuecomment-915010734) it may be a good idea to open an issue here for it to be checked. Please note that the RC branch was enabled already in another PR (https://github.com/conda-forge/scikit-learn-feedstock/pull/139)

**Comment by beckermr** [comment]
The bot ignores these tags on purpose iirc.

**Comment by adrinjalali** [comment]
I know that's the default behavior, but isn't this supposed to enable RCs?

https://github.com/conda-forge/scikit-learn-feedstock/blob/6e33bb1256bda46c7ea4dba15b320c43551b9afb/conda-forge.yml#L5-L8

**Comment by beckermr** [comment]
No it is not.

**Comment by beckermr** [comment]
That has the bot send abi migration prs to branches. It doesn't have the bot find rc releases.

**Comment by jakirkham** [comment]
Ah right. Sorry for the confusion here. Thanks for clearing this up Matt!

Was thrown by the same thing Adrin was.
