### ISSUE TITLE
Bot to pick up pre releases

### ISSUE THREAD

**Issue by bsipocz** [regro/cf-scripts#147]
We've just started continuously deploy astroquery to pypi. We however kept the `dev` tag in the version number for the automated releases, so they are now only picked up with ``pip install --pre``. 

Is there any plan to make the bot pick up these releases? Otherwise I probably need to set up a nightly cron job to check on the latest release and update the recipe (maybe that's the better approach as that case doesn't require merging the update PR and the CI is only runs once?)

**Comment by CJ-Wright** [comment]
Please see https://github.com/regro/cf-scripts/issues/87
and
https://github.com/regro/cf-scripts/issues/86

If you aren't already if highly suggest putting these dev releases into a separate label.

**Comment by bsipocz** [comment]
Thanks, I indeed haven't seen those issues.
In the meantime we agreed that having a PR is not a bad thing after all as they give us a bit more control, so direct pushes are not crucial for us any more. 
However using a separate dev label is not practical in this specific case, as the motivation behind switching to continuous deployment was to ease it for users to install the latest version. 

Anyway, I'm closing this as a duplicate of the issues you mentioned.
