### ISSUE TITLE
Merged PR of torchquad feedstock not appearing on conda

### ISSUE THREAD

**Issue by gomezzz** [regro/cf-scripts#1481]
Hi, 

I have merged the PR for version 0.2.3 of torchquad https://github.com/conda-forge/torchquad-feedstock/pull/2 here.

However, it does not appear on [conda](https://anaconda.org/conda-forge/torchquad).

Any hints what might be causing this?

Thanks!

**Comment by beckermr** [comment]
Make sure the jobs on master ran ok. Also there is usually a delay in packages being available.

**Comment by gomezzz** [comment]
Make sure the jobs on master ran ok.

(All checks)[https://github.com/conda-forge/torchquad-feedstock/pull/2/checks] and actions on master ran successfully and I could also run it locally.

> Also there is usually a delay in packages being available.

I merged over a month ago. :)

Could this be because 0.2.2 was not merged and we instead moved directly to 0.2.3?

**Comment by gomezzz** [comment]
Turns out, the azure pipelines on the merge had failed due to an HTTP 500. Rerunning it  [here](https://github.com/conda-forge/torchquad-feedstock/runs/4162524031) solved it. Thanks!
