### ISSUE TITLE
Problem downloading a patch

### ISSUE THREAD

**Issue by akhmerov** [regro/cf-scripts#1494]
I'm facing a CI failure in a place that previously used to work: conda-build fails to render a bot PR with the error message claiming that the patch source can'd be downloaded.

- PR in question: https://github.com/conda-forge/tinyarray-feedstock/pull/28
- Example [failing job](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=430458&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=464)

**Comment by beckermr** [comment]
Thanks for the issue! However, this error is not due to the bot.

The problem here is that the patch cannot be applied to the source. Please check the patch against the upstream source to ensure that it is still needed. If the patch should apply, but didn't, please open an issue on conda-build.

**Comment by akhmerov** [comment]
Ah! I misread, it's "failed to download **or patch** source"! Sorry for the noise :)

**Comment by beckermr** [comment]
No worries! Good luck with the error!
