### ISSUE TITLE
Writing to Graph is not Atomic

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#15]
@justcalamari commented on [Fri Mar 02 2018](https://github.com/regro/cf-graph/issues/52)

We can run into problems when multiple jobs update the graph at the same time. We do not pull before pushing with doctr, so if the repo has been updated the push will fail. If we do pull, we can also have merge conflicts when the graph is updated by multiple people/bots, so we need a way to either prevent such merge conflicts or resolve them correctly.

**Comment by asmeurer** [comment]
I'm not fully sure what this issue is about, but doctr does pull before it pushes automatically. https://github.com/drdoctr/doctr/blob/a11fa6508ce2ea379c84c08ab1543a76ba1750b3/doctr/travis.py#L522

**Comment by CJ-Wright** [comment]
Awesome! Thank you very much @asmeurer. That fixes the first part, but we still need a way to merge the graphs if we hit a conflict. We currently use pickled graphs because they are easy to load, but they don't git merge well.

**Comment by asmeurer** [comment]
I see. The only way to have git do the merges for you is if you split the data into a file/directory structure (git assumes changes to different files are unrelated to each other), or at the very least, in a human readable format where unrelated (i.e., mergeable) changes aren't right next to each other. I don't know your format but pretty printed JSON could potentially work.

**Comment by CJ-Wright** [comment]
We tried `yaml` in the past (which should have been git friendly) but the load times were really bad. We should shop around though, `networkx` has a ton of file formats that we could potentially use.
We could also load both graphs and troubleshoot in python (maybe using update timestamps?)

**Comment by CJ-Wright** [comment]
I think with the move of the nodes to their own files (and the PRs for that matter) this is done.
