### ISSUE TITLE
Status of osx arm64 migration for spacy-alignments

### ISSUE THREAD

**Issue by adrianeboyd** [regro/cf-scripts#1512]
Hi, one of our users noticed that there's no `spacy-alignments` package for osx arm64 yet although it was published a few months ago. I looked through the status info and couldn't find it in any of the obvious categories where the migration might have stalled. Is there anywhere I can figure out the status or ask for the migration to be triggered again if necessary? Thanks!

**Comment by beckermr** [comment]
I'd check the feedstock. Did it get a PR? If it did get a PR, is that PR merged? Did the build on master/main run correctly for the merged PR?

**Comment by adrianeboyd** [comment]
There was never a PR as far as I can tell, only the python 3.10 migration so far.

**Comment by adrianeboyd** [comment]
Hi, is it possible to get this migration triggered again? I can probably manage to piece it together manually based on similar PRs in other repos, but that's probably a bit error-prone.

**Comment by adrianeboyd** [comment]
Hi again, is there anything we can do to get the arch migration triggered here?

**Comment by adrianeboyd** [comment]
I gave up on the migration process and got it working manually after a few attempts.
