### ISSUE TITLE
Bot not updating petsc-feedstock

### ISSUE THREAD

**Issue by dalcinl** [regro/cf-scripts#1520]
The bot has issues processing updates for `petsc-feedstock`. I asked for help on Gitter, @chrisburr figured out what's going on, his own words below:

The bot is getting confused by: https://github.com/conda-forge/petsc-feedstock/blob/ca09ddd96e7f2f3da1dd9d3e715bc4afb789153e/recipe/conda_build_config.yaml#L22-L24

If you look at the raw log from https://github.com/regro/autotick-bot/runs/5811795906?check_suite_focus=true and search for petsc-feedstock you can see the error.

Is this something we should fix on the `petsc-feedstock` side?

**Comment by beckermr** [comment]
it will take a while for the bot to try the jobs again
