### ISSUE TITLE
bot not auto-updating pandera-feedstock

### ISSUE THREAD

**Issue by cosmicBboy** [regro/cf-scripts#1522]
not sure how to debug this, but https://github.com/regro-cf-autotick-bot/pandera-feedstock is no longer automatically creating PRs when new pypi versions of `pandera` are created. Not sure if it's a recipe issue or something else... would appreciate any help!

**Comment by beckermr** [comment]
Please check the conda forge status page under the versions section.

**Comment by cosmicBboy** [comment]
thanks!

**Comment by beckermr** [comment]
I'm going to close this for now. If you find an error you think is the bot, feel free to reopen!
