### ISSUE TITLE
Missing `openexr31` migrator for `vigra`

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1523]
Previously PR ( https://github.com/conda-forge/vigra-feedstock/pull/88 ) was opened to handle migration. The bot was asked to rerun this, but it appears it never did. Would it be possible to get a new migration PR? Also do we know why the migration PR was not resubmitted?

**Comment by beckermr** [comment]
What does the status page say?

**Comment by jakirkham** [comment]
Looks like a bot error

**Comment by beckermr** [comment]
Cool. What's in the log that should be linked there?

**Comment by jakirkham** [comment]
This looks like [the relevant bit]( https://github.com/regro/autotick-bot/runs/5840105346?check_suite_focus=true#step:12:10225 ). Think I see what's going on

**Comment by jakirkham** [comment]
PR ( https://github.com/conda-forge/vigra-feedstock/pull/90 ) should fix it.

**Comment by jakirkham** [comment]
Might help to lint these kinds of things ( https://github.com/conda-forge/conda-smithy/issues/1616 )

**Comment by jakirkham** [comment]
Now have the migration PR ( https://github.com/conda-forge/vigra-feedstock/pull/91 ) 🎉

Thanks for the help Matt! 😄
