### ISSUE TITLE
Bot not updating alibi-detect feedstock

### ISSUE THREAD

**Issue by ascillitoe** [regro/cf-scripts#1541]
Hi all, many thanks for maintaining `conda-forge` and `cf-scripts`!

We released a new version of our `alibi-detect` library yesterday, however `regro-cf-autotick-bot` doesn't appear to be opening a new PR in our feedstock. Could this be because we already had an open failing PR (for a previous version) in our feedstock when we opened the new version? (there was only one open PR, failing due a missing licence file in our sdist, which I have now closed).

I've checked the JSON log file but couldn't see any issues, and have been monitoring the `autotick-bot` github actions but can't see any recent mention of `alibi-detect`. There's also no mention of `alibi-detect` in the Queued or Errored lists here: https://conda-forge.org/status/#version_updates.

### Related links
- [Alibi Detect repo](https://github.com/SeldonIO/alibi-detect)
- [Alibi Detect feedstock](https://github.com/conda-forge/alibi-detect-feedstock)
- [Alibi Detect PyPI](https://pypi.org/project/alibi-detect/)
- [JSON log file](https://github.com/regro/cf-graph-countyfair/blob/93188c9ef22347b9c1cec2dccd83194f7fb02edb/node_attrs/alibi-detect.json)

**Comment by ascillitoe** [comment]
Closing this as the PR was eventually opened. I don't know why it took over 24 hours as it is usually much faster, but all good now!

**Comment by beckermr** [comment]
no worries! thanks for following up!
