### ISSUE TITLE
PyPy 3.8 migration failed because of a failure to find a supported SciPy version.

### ISSUE THREAD

**Issue by hodgestar** [regro/cf-scripts#1542]
The rebuild for PyPy 3.8 at https://github.com/conda-forge/qutip-feedstock/pull/79 failed because no support version of SciPy could be found. Is there a way I can adjust the qutip recipe to allow a supported SciPy to be found, or just wait an rerun the build when a supported SciPy is available?

**Comment by beckermr** [comment]
This question is not really bot related, but yes wait.

**Comment by hodgestar** [comment]
Thanks!
