### ISSUE TITLE
Issue with openmpi build

### ISSUE THREAD

**Issue by sblauth** [regro/cf-scripts#1547]
I have encountered an issue with openmpi when building my package cashocs for conda-forge. The package can either use the `mpich` or `openmpi` implementation for parallelism, but the conda-forge build fails, when `openmpi` is used (see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=564717&view=results)
The error message is 

```
--------------------------------------------------------------------------
The value of the MCA parameter "plm_rsh_agent" was set to a path
that could not be found:

  plm_rsh_agent: ssh : rsh

Please either unset the parameter, or check that the path is correct
--------------------------------------------------------------------------
```

Either specifying `mpich` as dependency (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=564951&view=results) or adding `openssh` as dependency (see https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=564963&view=results) works. To me, it seems that `ssh` is missing in the docker container for building the recipe. Is there any way to resolve this?

Thanks and best regards,
Sebastian

**Comment by beckermr** [comment]
This issue is in the wrong place. Please post it to the feedstock of the package. I am closing it for now.
