### ISSUE TITLE
`onednn` missing update PRs

### ISSUE THREAD

**Issue by igorsafo** [regro/cf-scripts#1550]
Affected oneDNN versions:
- v2.6.2
- v2.7

Tagging @xhochy

**Comment by isuruf** [comment]
That 2.7-p2 PR was the issue. Fixed in https://github.com/regro/cf-graph-countyfair/commit/756045334f1b0610bc3062a5a81b18886592f138

**Comment by igorsafo** [comment]
Hi @isuruf , thanks for the fix! In future we might have similar RC (release candidate) releases. We mark them as `Pre-release`. Is it possible to skip such releases automatically since we don't really want to have them in conda, because they are for integration/application teams to try before a final release.

**Comment by isuruf** [comment]
We do skip pre-releases like `rc, dev, pre`, but `pc` was not something we've encountered before.

**Comment by igorsafo** [comment]
@isuruf Thanks for the information. Is it something that can be added to a feedstock configuration? Something like extended list of ignored releases in case a product has custom release names.
