### ISSUE TITLE
arm ta-lib

### ISSUE THREAD

**Issue by bl4val** [regro/cf-scripts#1557]
Hello, I saw that there is arm support for ta-lib as a [pull request](https://github.com/conda-forge/ta-lib-feedstock/pull/18), but it is not merged (also there are some unmerged version updates). How long do you think it will take until I can install ta-lib on arm through conda-forge (it's for GCPs new t2a machines)?

**Comment by beckermr** [comment]
Please ping the feedstock maintainers on the pr or conda forge core. The bot team itself has no special permissions to merge prs.

**Comment by beckermr** [comment]
I'm going to close this one for now but feel free to reopen if you have more comments or questions!
