### ISSUE TITLE
automerge stopped working (error=API error in POST to merge)

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#1562]
I've seen this on more than three PRs today:

> Hi! This is the friendly conda-forge automerge bot!
> 
> I considered the following status checks when analyzing this PR:
>  * **linter**: passed
>  * **azure**: passed
> 
> Thus the PR was passing, but could not be merged (error=API error in POST to merge).

Example: https://github.com/conda-forge/aws-c-http-feedstock/pull/87 (can provide more, I think it's happening everywhere).

Status page shows "All Systems Operational", so this doesn't appear to be on someone's radar yet.

CC @beckermr

**Comment by beckermr** [comment]
Cc @isuruf 

He is fixing it now but the fix will take time to go through.
