### ISSUE TITLE
No-op bot PR to `libboost-mpi`

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1569]
As part of the Boost migration, the bot tried to update `libboost-mpi` with PR ( https://github.com/conda-forge/libboost-mpi-feedstock/pull/5 ). However as [`libboost-mpi`'s version of `boost-cpp` is tightly pinned]( https://github.com/conda-forge/libboost-mpi-feedstock/blob/cb9daf1e093be922572d9efa15db9fcc6de90f7d/recipe/meta.yaml#L26 ), the bot PR doesn't really do anything. Is there any way to either prevent the bot from making this sort of PR or include a version update\* as part of the bot PR?

\* Note that `libboost-mpi` is just the MPI components of Boost split out

**Comment by jakirkham** [comment]
cc @sdebionne

**Comment by beckermr** [comment]
Unfortunately there's no good way to prevent this. The bot issues a pr if the feedstock changes upon rerendering. It's really hard to know for a given set of changes if the pr is a no-op or not.

**Comment by jakirkham** [comment]
That's fair. Are there things that can be done over at the feedstock to help avoid this (no worries if not)?

**Comment by beckermr** [comment]
Right. Generally, fewer local pins that override the global ones will help.

**Comment by jakirkham** [comment]
Hmm ok. Trying to understand how to leverage this

For context `libboost-mpi` is just a piece of Boost. Similar to how `boost-cpp` and `boost` contain C++ & Python components, `libboost-mpi` contains the MPI components. All of them just different pieces of the same Boost release

**Comment by beckermr** [comment]
Right, so this line (https://github.com/conda-forge/libboost-mpi-feedstock/blob/main/recipe/meta.yaml#L22) is the issue. By having the version pinned in host, the global pin is ignored. This means the bot's rerender, which is supposed to insert a new global pin via the migration, does nothing. 

The options to fix are, as I see it,

1) merge the various boost parts into a single recipe (i.e., add this package as an output on boost-cpp)

2) Try to inject the global pin into the recipe by adding boost-cpp without a version to host and then doing something to ensure builds where there is a version mismatch are not done. Generally, this option will create an error in the migration and cause the feedstock to appear as not solvable.

**Comment by jakirkham** [comment]
Based on the discussion in issue ( https://github.com/conda-forge/boost-cpp-feedstock/issues/116 ), think merging the recipes back together is already off the table.

Good point. Think we did something similarly clever with with `nvcc_linux-64` ( https://github.com/conda-forge/nvcc-feedstock/pull/19 )

**Comment by jakirkham** [comment]
Trying with PR ( https://github.com/conda-forge/libboost-mpi-feedstock/pull/8 ). Though this may affect the feedstock's ability to get version updates. Other suggestions would be welcome.

**Comment by beckermr** [comment]
Right. No version updates come by with the PR above. OTOH you may not want to move versions until boost-cpp does in a migration so this might be ok.

**Comment by jakirkham** [comment]
Yeah am not sure that is what we want. Hence raising this particular issue.

**Comment by jakirkham** [comment]
Thinking about this more, maybe what we want is two branches:

* A global pinned release branch (`stable`?) with ABI migrations enabled
* A `main` (or `latest`) that gets version updates and has ABI migrations disabled

**Comment by beckermr** [comment]
We can't (I think) disable ABI migrations on main but for sure the stable branch could get them which could be useful. 

The issue with more than one branch is recipe updates outside of the versions become a pain. 

I don't personally think you need version updates for this feedstock. Don't you always want it to match the other boost versions in use? Your runtime pinnings sure indicate that

```
  run:
    - boost-cpp {{ version }}.*
    - {{ mpi }}
```

I think it is simpler to simply tie the version to the global pinnings and let the bot do its thing.

**Comment by jakirkham** [comment]
Interesting so maybe it is just a naming issue with the 2 branch proposal above? Are we able to redirect version updates to a different branch? Perhaps that is a different solution.

Understood (and agreed), but given the needs/constraints perhaps 2 branches is reasonable. If we could disable ABI migrations on `main`, maybe that would also work here.

It is using [the same source]( https://github.com/conda-forge/libboost-mpi-feedstock/blob/cb9daf1e093be922572d9efa15db9fcc6de90f7d/recipe/meta.yaml#L9 ) as [`boost-cpp`]( https://github.com/conda-forge/boost-cpp-feedstock/blob/54205be53367139c84b2b44ac4f0618a48506a12/recipe/meta.yaml#L9 ) and [`boost`]( https://github.com/conda-forge/boost-feedstock/blob/fc72cb426ca718cab735a5944c6926a49130ceee/recipe/meta.yaml#L10 ). They will all get version updates at the same time. One will need to merge and restart CI a bit, but having them all get release PRs around the same time seems reasonable. It is also consistent with how we have done things with other feedstocks in a similar boat (Python/C++ splits, etc.).

C++ users of conda-forge don't necessarily care where conda-forge is in Boost migrations. They may just use Boost and a handful of other things (often not dependent on Boost). Increasingly Boost acts like a backports package for C++ developers targeting older compilers/C++ standards. For those users, Boost version updates are more important than migrations.

**Comment by beckermr** [comment]
Version updates always go to main.

**Comment by sdebionne** [comment]
Interesting discussion, I was not aware of [Boost migrations happening](https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3402) and the need to migrate `boost-cpp` as well.

> For those users, Boost version updates are more important than migrations.

As a C++ user of conda-forge, I fully agree. Note that the current recipe does no build the Python binding of Boost.MPI (`mpi4py` being a much better package).

**Comment by beckermr** [comment]
Then  a main branch and an abi branch per @jakirkham's idea seems best. The bot will issue ABI migrations to the main branch. Simply ignore them/close them.

**Comment by jakirkham** [comment]
Sounds good. Thank you both! 🙏

Have configured PR ( https://github.com/conda-forge/libboost-mpi-feedstock/pull/8 ) to target a new branch, `abi`, which should do this. Additionally sent PR ( https://github.com/conda-forge/libboost-mpi-feedstock/pull/10 ) to enable migrations on the `abi` branch.

Once we are happy with those and they are in, we should be able to close this out.

**Comment by jakirkham** [comment]
Resolved by making the aforementioned changes to the feedstock
