### ISSUE TITLE
Migrator for `orc` version `1.8.1` not created?

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1576]
There was a new release of `orc` recently ( https://github.com/conda-forge/orc-feedstock/pull/52 ), `1.8.1`. As [`orc` has a very tight pinning]( https://github.com/conda-forge/orc-feedstock/blob/3c86c65081c75d92f21c038e72ff08991205bbbc/recipe/meta.yaml#L19-L20 ), this needs a migrator. However there does not appear to be a PR to add the migrator to `conda-forge-pinning` like there has been in the past ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3373 ). Not sure why this is missing.

**Comment by jakirkham** [comment]
cc @kkraus14 @galipremsagar @noirello

**Comment by beckermr** [comment]
The bot's metadata has not internally picked up the 1.8.1 as the current version which means something is going wrong in the feedstock parsing. I am seeing a lot of errors there so I suspect this is not related to orc per say but is likely related to a change in conda build or something.

**Comment by jakirkham** [comment]
Is there a link to the log?

**Comment by beckermr** [comment]
update of orc works locally

**Comment by beckermr** [comment]
yeah here it is: 

```
2022-12-09 21:29:00,058 ERROR    conda_forge_tick.make_graph || itr  9505 - eta   743s: Error adding orc to the graph: BrokenProcessPool('A process in the process pool was terminated abruptly while the future was running or pending.')
```

Let's turn down the parallelism

**Comment by beckermr** [comment]
See this issue: https://github.com/regro/cf-scripts/issues/1578

I think the latest commits will fix this.

**Comment by jakirkham** [comment]
Looks like it got created now ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3829 )

**Comment by jakirkham** [comment]
Thanks Matt! 🙏
