### ISSUE TITLE
`bot-automerge` not added in PR title with `bot.automerge` set to `true`

### ISSUE THREAD

**Issue by messense** [regro/cf-scripts#1577]
conda-forge.yml:

https://github.com/conda-forge/ruff-feedstock/blob/f6d3ecf5fca3585b334d671f0d7524b47c0fcff8/conda-forge.yml#L1-L2

bot update PR: https://github.com/conda-forge/ruff-feedstock/pull/34

https://github.com/regro/cf-scripts/blob/b638aed304559d5a46f5ba5b01143c89a7138d39/conda_forge_tick/migrators/version.py#L764-L768

Judging from the code it should add `[bot-automerge] ` to PR title but it did not.

**Comment by beckermr** [comment]
See this issue: https://github.com/regro/cf-scripts/issues/1578

I think the latest commits will fix this.

**Comment by messense** [comment]
https://github.com/conda-forge/ruff-feedstock/pull/35 indeed, thanks!
