### ISSUE TITLE
Mark yanked PyPI packages as broken

### ISSUE THREAD

**Issue by maresb** [regro/cf-scripts#1581]
According to @ocefpaf in https://github.com/conda-forge/admin-requests/pull/529#issuecomment-1346965959,

> We need some automated service to watch PyPI yanked packages. Having folks report them is not sustainable. Sure the solver will ensure that a newer versions is picked up but it would be nice to have a 1-1 match with broken and yanked.

This repo seems like the logical location to deploy such a service, perhaps integrated with the autotick-bot?

**Comment by beckermr** [comment]
That'd work for sure.

**Comment by maresb** [comment]
Closed as a duplicate of #1397. (Almost exactly the same title! :joy:)
