### ISSUE TITLE
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app

### ISSUE THREAD

**Issue by nicrie** [regro/cf-scripts#1587]
Thanks for this cool bot! 

Trying to update my package on `conda-forge` after I changed some dependencies of the package, I run into the following problem after updating the PR opened by the `rego-bot`:

When running the checks the CircleCI Pipeline fails with the following message:

```
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.
```
I am a bit lost on where/how I have to sign out and log back in? I am rather new to the `conda-forge` environment so I'm struggling to understand the meaning. Would be glad if anyone could point me in the right direction.

URL for debugging: https://github.com/regro/autotick-bot/actions/runs/3870024457

Thanks for helping!

**Comment by beckermr** [comment]
Thanks for the ping! Please post a link to the feedstock and I will fix it there.

**Comment by nicrie** [comment]
Thanks Matthew for getting back so quickly!

Here's the PR for the feedstock: https://github.com/conda-forge/xeofs-feedstock/pull/3

However,  it seems I just "solved" it by re-cloning the feedstock and making an empty commit re-triggering the checks. Not sure why that worked though..

As to the deprecating of CircleCI - does that require any action from my side to comply with newer versions in the future?

**Comment by beckermr** [comment]
nope nothing for you to do for circle ci

**Comment by beckermr** [comment]
closing!
