### ISSUE TITLE
Missing PETSc migrations

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1600]
It seems the bot is missing these migrations due to a bug. Though it is unclear how to fix this atm. Filing this issue to track.

cc @minrk @beckermr

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4086#issuecomment-1424214155

**Comment by beckermr** [comment]
This is a duplicate: https://github.com/regro/cf-scripts/issues/1560

going to close this in favor of the other one above!

**Comment by jakirkham** [comment]
Ah sorry. Thought we didn't have an issue and wanted to make sure this didn't get lost. Thanks for clearing that up!
