### ISSUE TITLE
Dep analysis appears broken; reports all meta.yml deps as missing on multiple feedstocks

### ISSUE THREAD

**Issue by CAM-Gerlach** [regro/cf-scripts#1617]
The dependency analysis on autotick PRs appears to be broken, per my observations on multiple new autotick PRs in the past 24 hours, as it is suddenly listing all the deps listed in the `meta.yml` as missing, despite them still being present in the source code with no major changes. Moreover, it is also apparently not listing "missing" deps in the `meta.yml` that were imported (in non-package code) that were detected before.

I've observed this on both autotick bot PRs I reviewed and merged today, conda-forge/pyroma-feedstock#18 and conda-forge/praw-feedstock#24 . The URLs for those runs are https://github.com/regro/cf-scripts/actions/runs/4270734559 and https://github.com/regro/cf-scripts/actions/runs/4273594672 respectively.

As I haven't reviewed/merged a similar PR in at least several weeks, I can't confirm when this started, but it seems to be more than a one-off. Could you investigate? Thanks!

**Comment by beckermr** [comment]
> Packages found in the meta.yaml but not found by source code inspection:

The analysis is saying these packages are in the meta.yaml but not in the source code. 

It could be wrong, but the fact that they are in the meta.yaml is not in and of itself the issue. Instead if they are actually in the source code, then that's an issue.

**Comment by CAM-Gerlach** [comment]
@beckermr Sorry, I was unclear above—I edited my post to clarify. The issue is that the bot is suddenly listing _every_ package from the `meta.yml` as not being imported, all 3 for `praw` and all but a couple of the 7 deps for `pyroma` are still imported in the source code, some numerous times, and there aren't any substantial source or packaging changes that seem plausible to cause the bot to start missing every import, particularly not for two completely different packages.

Also, it appears it may not be detecting packages missing from the `meta.yml` that are imported, as it detected `requests` previously for `praw` ((albeit in test and tools scripts, not actual package code, so I'd not added it), and it is not detecting `zope.event` as being missing from `pyroma`, which is used in release automation scripting but not package code. Not sure if the false positive filtering heuristics have been significantly improved and this is expected, or this is also due to the same problem of it missing all the imports, but I figured I'd point that out too.

**Comment by beckermr** [comment]
Thank you! We might turn this off since it is getting hard to maintain.

**Comment by CAM-Gerlach** [comment]
It has been pretty helpful in the past at catching mistakes and when the upstream is not explicitly specifying all direct dependencies, and I'm sure making it quicker for some folks to check for requirements changes, so that would be too bad. But if its not an easy fix for whatever reason, and there isn't the bandwidth to maintain it, then I guess it's better to turn it off than give spurious results. I always carefully check the upstream anyway, and I can just whip out some regexes to detect missing imported deps, I guess.

**Comment by beckermr** [comment]
I see a very odd bug where it works locally but not in CI in #1619. I cannot figure it out so I've turned them off.

**Comment by CAM-Gerlach** [comment]
That's too bad, but thanks for the quick response and taking care of it!
