### ISSUE TITLE
Issue PRs changing toolchain over to jinja2 compiler syntax

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#162]
As a prelude to #44 it may be helpful to first issue a bunch of PRs into recipes currently using the `toolchain` syntax to move them over to the compiler syntax. Note that this will not move them over to the new compilers, the new syntax does the same thing as toolchain under the hood (I think? @msarahan?). This is needed for the new to the new compilers.

I think the main issues here are:
1. Flagging everything that uses toolchain (not particularly hard)
1. Figuring out what compilers a package needs. `toolchain` was an omnibus system everything was under toolchain (c, c++, fortran, etc.). The new syntax is more specific and specifies the exact compiler needed. One approach could be to get the code from the tarball and inspect the extensions of all the code? I don't know how reliable that would be, but it might be a good first guess.

**Comment by dougalsutherland** [comment]
Related: https://github.com/conda-forge/conda-smithy/pull/781

**Comment by jakirkham** [comment]
This is really a question of whether we want transient migration scripts as part of the bot. While the bot is a very cool thing that could push such changes with, wouldn't want to unnecessarily burden the bot with things needed for such scripts. Ultimately think it is up to you to make that decision.

**Comment by scopatz** [comment]
I think we have run into the migration issue (or "rebuild-the-world") a couple of times with conda-forge. The bot seems like a good place to put this capability and to manage these kinds of issues in the future.

**Comment by isuruf** [comment]
It would be hellpful to know how many recipes need to be rebuilt. https://github.com/regro/cf-scripts/issues/44#issuecomment-392952424 gives all descendants of toolchain, but we only need those recipes with toolchain as a build dep.

**Comment by CJ-Wright** [comment]
This is in progress, we need to get #197 in, manually fix the graph, and then restart the bot and we should be good to go.

**Comment by CJ-Wright** [comment]
I think this is done!

**Comment by CJ-Wright** [comment]
(I closed this because we are PRing things, not because all the PRs have be done)
I have 467 left to do from the travis output.
