### ISSUE TITLE
Autotick bot failing

### ISSUE THREAD

**Issue by kukushking** [regro/cf-scripts#1629]
Hi! We've released 2.20.0 version of awswrangler yesterday but the bot still didn't open a PR for https://github.com/conda-forge/awswrangler-feedstock/pulls 

Looking at https://conda-forge.org/status/#version_updates bot status is failing

Just opening to make sure this is on the radar. Is it worth to wait for the bot fix or update the feedstock manually?

**Comment by beckermr** [comment]
Thanks! We've been doing maintenance, and so the bot is behind. The status page is now green, and the bot is alive and well!

With the maintenance we just finished, we should be able to cut about 40 minutes out of the bot's nearly 3-hour latency right now, which is a big win!

I am going to close this one for now, but if you don't get a version PR eventually, please feel free to reopen it. Also, note that you can always bump the version by hand if you need it on a short timescale.

**Comment by kukushking** [comment]
Understood, thanks!
