### ISSUE TITLE
PRs not being created for new PyPI releases

### ISSUE THREAD

**Issue by jwodder** [regro/cf-scripts#1631]
We released two new versions of our package (dandi) on PyPI on Wednesday and Friday last week, yet no PRs have yet been created for the new versions in [the feedstock repo](https://github.com/conda-forge/dandi-feedstock).

According to Matthew R. Becker on gitter, "there was an internal error but the bot is not retrying; this appears to be a bug."

**Comment by beckermr** [comment]
Woops. Let's wait until we see a PR before closing this one!

**Comment by jwodder** [comment]
Our feedstock finally got a PR for Friday's release: https://github.com/conda-forge/dandi-feedstock/pull/93

**Comment by beckermr** [comment]
Great! Closing!
