### ISSUE TITLE
migrator spuriously failing to open PR due to cudatoolkit constraint

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#1661]
I've seen this for the aws-crt-cpp migration, and now for libgrpc, that the migrator will not open a PR on main because:
```
linux_64_cuda_compiler_version10.2: Encountered problems while solving:
 - package ucx-1.14.0-h0aa22dc_1 has constraint cudatoolkit 10.2 conflicting with cudatoolkit-10.2.89-hfd86e86_0
```

When I open the PR manually, it runs through fine though (see https://github.com/conda-forge/arrow-cpp-feedstock/pull/1023 & https://github.com/conda-forge/arrow-cpp-feedstock/pull/1027)

Not sure why this fails at all, but the bot should issue a PR IMO. Interestingly, all the maintenance branches worked right away...

CC @conda-forge/ucx-split

**Comment by beckermr** [comment]
Cc @mariusvniekerk @wolfv maybe we misspecified something in the solver checks?

Thanks @h-vetinari !

**Comment by beckermr** [comment]
closed via a change to the ucx feedstock for an incorrect constraint.

see https://github.com/conda-forge/ucx-split-feedstock/issues/120#event-9150932954 and https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/445#event-9150932885

**Comment by h-vetinari** [comment]
Cool thanks!
