### ISSUE TITLE
Plugin/hot swappable migration interface

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#169]
It seems that the autoticking bot may be a good platform for running migrations for CF. It has access to the complete graph, the power to PR into repos, and self updates.

It might be nice to have a generalized interface to this so that running these would be easier.
The API could look like this `migrate(filter, migrator)`. In this case filter is a callable which would be called to check if the node meets needed criteria. Then migrator (also a callable) would be run to mutate the `meta.yaml` into the new format.

We could put a list of these somewhere in a xonsh script which 03 (or another script) could then run on the graph.

Note that this make the current operation of the bot a special case of this more general case. In the current case our "migration" is to a new version number and checksum and the "filter" is if the node needs a version bump.

**Comment by jakirkham** [comment]
Have thought about this as well in the context of `conda-smithy`. However it appears we never opened an issue on it. So have opened issue ( https://github.com/conda-forge/conda-smithy/issues/793 ). Thoughts on this would be welcome.

**Comment by CJ-Wright** [comment]
xref: https://github.com/regro/cf-scripts/pull/171#discussion_r193194033
