### ISSUE TITLE
version missed

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#17]
@CJ-Wright commented on [Thu Mar 01 2018](https://github.com/regro/cf-graph/issues/50)

https://github.com/conda-forge/plumpy-feedstock/pull/2
https://github.com/conda-forge/plumpy-feedstock/blob/master/recipe/meta.yaml#L2

---

@CJ-Wright commented on [Thu Mar 01 2018](https://github.com/regro/cf-graph/issues/50#issuecomment-369804383)

At this point we should have a matrix of find and replaces which also includes some good regex matches (arb number of spaces) and a correcting system (normalize the output)

---

@jakirkham commented on [Fri Mar 02 2018](https://github.com/regro/cf-graph/issues/50#issuecomment-370085888)

This becomes more important when we start to consider downstream packages that have tight version constraints on upstream packages. Admittedly that can get into a whole other can of worms finding the dependencies (w/version constraints) and using them to solve how best to update the graph.

---

@CJ-Wright commented on [Fri Mar 02 2018](https://github.com/regro/cf-graph/issues/50#issuecomment-370089116)

I meant just normalizing the jinja2 variables.  Yes, optimal bumping on the graph would be awesome. It may even be possible as soon as we get rid of the cycles in our otherwise perfect DAG (although maybe we can excise the cycles from the DAG and handle them separately?)

**Comment by jakirkham** [comment]
Yeah `conda-build` and/or `conda-smithy` could help here.

Might be worth generating a list of cycles. Am hoping they are mostly small cycles and few in number.

**Comment by CJ-Wright** [comment]
Here are the cycles: 
https://github.com/regro/cf-graph/blob/master/cycles.txt
And the generating script:
https://github.com/regro/cf-graph/blob/master/find_cycles.py

(One of these days someone will get around to rebuilding the cycles via bot so we can keep them up to date (along with the other graph introspections))

**Comment by CJ-Wright** [comment]
The multi package recipes are a bit worrying for the bot (I'm sure we can figure something out, it may take some cleverness).

I guess we should really start to delineate between run and build requirements in the graph (although I'm not certain how to do this in `networkx`) which should help with the cycles. I presume that build/build cycles shouldn't exist. If that is the case then we can have the ticker run in a topological sort on the build dependencies, which should be a proper DAG. Should we worry about run dep bump order?

**Comment by jakirkham** [comment]
Yeah maybe we should move that to a new issue (if there isn’t one already).

Would also mention multiple sources are a thing in cb3.

With both of these things, it goes a long way to have good policy. Also as with all things packaging one must think about naming. Probably worth raising an issue upstream at cf to discuss how we want to handle these.

**Comment by CJ-Wright** [comment]
Multi source/package issue: https://github.com/regro/cf-scripts/issues/45

**Comment by CJ-Wright** [comment]
I think this is done for the most part.
