### ISSUE TITLE
Maintainer can not merge feedstock PRs

### ISSUE THREAD

**Issue by glenn-jocher** [regro/cf-scripts#1720]
Hi! I'm a maintainer for https://github.com/conda-forge/ultralytics-feedstock/ but I can not merge bot-created PRs like https://github.com/conda-forge/ultralytics-feedstock/pull/2. My screen looks like this for the PR:

<img width="1526" alt="Screenshot 2023-06-25 at 00 44 51" src="https://github.com/regro/cf-scripts/assets/26833433/2a604fcc-75fd-422a-b2c4-0aa046bc4845">

Please help! Thank you.

**Comment by beckermr** [comment]
You need to accept the GitHub org invite you got.

**Comment by beckermr** [comment]
If it is stale, put @conda-forge-admin refresh team in the title of a pr.

**Comment by glenn-jocher** [comment]
@beckermr thank you! I've written a message to [@]conda-forge-admin directly in my PR https://github.com/conda-forge/ultralytics-feedstock/pull/2 that I can't merge, will that do the trick?

**Comment by beckermr** [comment]
It should but you have to accept the org invite GitHub sends. Check your email.

**Comment by glenn-jocher** [comment]
@beckermr yes myself and the other maintainers have checked our emails but we have not received any invites recently (last checked today).

**Comment by beckermr** [comment]
Check your spam. GitHub sends these emails.

**Comment by glenn-jocher** [comment]
@beckermr got the email! All set, thanks!
