### ISSUE TITLE
regro-cf-autotick-bot should not remove quotes from yaml lines

### ISSUE THREAD

**Issue by jni** [regro/cf-scripts#1786]
In this commit:

[conda-forge/affinder-feedstock@`4a3deda` (#4)](https://github.com/conda-forge/affinder-feedstock/pull/4/commits/4a3dedadd5a819d1cd6256631563ea4d7a85c830)

changed the following lines in `meta.yml`:

```
    - "DISPLAY=localhost:1.0 xvfb-run -a affinder --help"  # [linux]
    - "DISPLAY=localhost:1.0 xvfb-run -a python -c 'import affinder'"  # [linux]
```

to:

```
    - DISPLAY=localhost: 1.0 xvfb-run -a affinder --help  # [linux]
    - DISPLAY=localhost: 1.0 xvfb-run -a python -c 'import affinder'  # [linux]
```

This caused the lines to be interpreted as key: value entries rather than strings, which are needed for the CI to run the appropriate commands. (The resulting error [wasn't easy to parse, either](https://github.com/conda-forge/affinder-feedstock/pull/4#issuecomment-1667578838), though it makes sense in retrospect. 😅)

Ideally, if the bot finds lines that are in quotes, the quotes should be preserved, especially if those lines are not related to the version change.

Thank you for all your work! I love the bot very much in general. 😊

**Comment by beckermr** [comment]
Ohhhh weird! I think this is related to our yaml parsing. I'll see if there is a way to fix it.

**Comment by jni** [comment]
Yeah I can see how reading in the yaml then writing it out would get rid of the formatting! 😬

**Comment by beckermr** [comment]
Are the quotes needed for the recipe to run correctly, or are they just to make things clear?

**Comment by jni** [comment]
Removing the quotes causes an error in conda-mambabuild, [full traceback shown here](https://github.com/conda-forge/affinder-feedstock/pull/4#issuecomment-1667578838):

```pytb
TypeError: write() argument must be str, not dict
```

I think without the quotes this yaml:

```yaml
    - DISPLAY=localhost: 1.0 xvfb-run -a affinder --help  # [linux]
```

gets parsed as a dictionary entry with:

key: `DISPLAY=localhost`
value: `1.0 xvfb-run -a affinder --help  # [linux]`

(the gh syntax highlighting seems to confirm this!)

and then the command is not a string anymore which causes the error.

Setting the display is indeed required or the test cannot run. Of course one can simply remove the tests a-la Volkswagen. 😜 But one would rather not! 😅 Perhaps I can set the env vars some other way?

**Comment by jni** [comment]
(But either way this bug would probably be good to fix or keep open for future reference!)

**Comment by beckermr** [comment]
I meant in the original recipe, not the messed up one.
