### ISSUE TITLE
Mismatch between PyPy version 3.8 in PR title, PR description and branch name

### ISSUE THREAD

**Issue by tetov** [regro/cf-scripts#1844]
Hi!

https://github.com/conda-forge/openvdb-feedstock/pull/6

- PR title references 3.9
- actual file changes: 3.9
- PR description 3.8
- branch name 3.8

This is only a cosmetic issue to me but reporting it since it might point to something more serious.

**Comment by beckermr** [comment]
pypy is not on conda-forge any more - closing this!
