### ISSUE TITLE
Missing `fastparquet` Python 3.12 migration

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1850]
It looks like the bot is running into an error when trying to migrate `fastparquet` for Python 3.12. However the error it produces seems to refer to Python 2.7, which is perplexing. Here's a screenshot from the status page

<img width="759" alt="Screenshot 2023-10-03 at 6 59 50 PM" src="https://github.com/regro/cf-scripts/assets/3019665/991ff25f-03cb-47e5-9e89-0eb7b30783fc">

Here's the relevant lines in [the log]( https://github.com/regro/cf-scripts/actions/runs/6361343194/job/17275696818#step:9:12930 ):

```
  Encountered problems while solving:
    - nothing provides openssl >=1.0.2p,<1.0.3a needed by python-2.7.15-hb75cb16_1006
```

Not sure where the old `openssl` pin comes from (`fastparquet` doesn't depend on `openssl`) or why `python` version `2.7.15` is relevant (again not used by `fastparquet`)

**Comment by beckermr** [comment]
Usually this kind of error means something else is not around and the solver finally error at some weird spot. You'll have to debug by hand to find the issue.

**Comment by jakirkham** [comment]
Yeah was wondering if that might be the case

Not sure, but this may help: https://github.com/conda-forge/fastparquet-feedstock/pull/68

**Comment by beckermr** [comment]
I fixed this BTW. The key is to look at the filenames, not the contents. 

```
% git ls-files fastparquet.json '**/fastparquet.json'
node_attrs/7/7/7/3/f/fastparquet.json
pr_info/7/7/7/3/f/fastparquet.json
version_pr_info/7/7/7/3/f/fastparquet.json
versions/7/7/7/3/f/fastparquet.json
```

Inside the pr_info file, there is a number of attempts for fastparquet for python 3.12. I reset those to zero.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏

**Comment by jakirkham** [comment]
Also linking the migrator PR for reference

https://github.com/conda-forge/fastparquet-feedstock/pull/69
