### ISSUE TITLE
bug: Cannot push to new bot PR as a maintainer

### ISSUE THREAD

**Issue by dlqqq** [regro/cf-scripts#1885]
I'm trying to push a commit to update the dependencies on this PR: https://github.com/conda-forge/jupyter-ai-magics-feedstock/pull/1. [The documentation indicates](https://conda-forge.org/docs/maintainer/updating_pkgs.html) that I should be able to push to this branch directly as a maintainer:

> As feedstock maintainer, you don’t have to create a new PR for that but can simply push to the branch the bot created.

However, when I push to this branch, I am met with the following error:

```
% git push -u bot
ERROR: Permission to regro-cf-autotick-bot/jupyter-ai-magics-feedstock.git denied to dlqqq.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I am listed as a maintainer on that feedstock. I also verified that I am not using a `git://` URL in my remote and that my remote URL is correct via the below command:

```
% git remote show bot
* remote bot
  Fetch URL: git@github.com:regro-cf-autotick-bot/jupyter-ai-magics-feedstock.git
  Push  URL: git@github.com:regro-cf-autotick-bot/jupyter-ai-magics-feedstock.git
  HEAD branch: main
  Remote branches:
    2.3.0_h412aed tracked
    main          tracked
  Local branch configured for 'git pull':
    2.3.0_h412aed merges with remote 2.3.0_h412aed
  Local refs configured for 'git push':
    2.3.0_h412aed pushes to 2.3.0_h412aed (fast-forwardable)
    main          pushes to main          (up to date)
```

My colleague @andrii-i is encountering the same error. I understand that as a workaround, it is possible for me to just push directly to a new branch on my fork rather than the bot's PR branch, but it would be nice if we could keep changes in a single PR.

**Comment by beckermr** [comment]
Thanks for the issue! This is not a permissions issue we can solve, but is instead either a github outage or a subtle thing in how git is being used here. Did you try to edit the files in UI?

**Comment by dlqqq** [comment]
Update: I just received this email, and I was able to push to the branch afterwards. If this was due to manual intervention, thank you.

<img width="1122" alt="Screenshot 2023-10-10 at 8 36 25 AM" src="https://github.com/regro/cf-scripts/assets/44106031/5b941750-0a3f-4b7a-8807-cdc97d3411ba">

Interestingly, I received similar emails for `jupyter-ai` and `jupyter-scheduler` on Sept 26, but I did not receive one for `jupyter-ai-magics`. Perhaps the conda-forge-webservices bot is overloaded and dropping a few requests?

Also worth noting that our colleague @3coins is still missing from these 3 CF teams:

- https://github.com/orgs/conda-forge/teams/jupyter-ai-magics
- https://github.com/orgs/conda-forge/teams/jupyter-ai
- https://github.com/orgs/conda-forge/teams/jupyter_scheduler

**Comment by beckermr** [comment]
Ahhhh ok. I bumped our webservices to refresh the permissions in the github api. They must have gotten out of sync. The other collaborators likely need to accept invites to conda-forge. 

Sorry for the trouble here and indeed this was not a github issue! Thank you for pushing on it and being patient!

**Comment by dlqqq** [comment]
@beckermr Likewise, thank you for taking the time to help fix this for us! I'll close the issue as it is resolved.
