### ISSUE TITLE
`pigz` shown in migrator errors, but is already done

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1888]
Seeing `pigz` in the bot errors for the arch migrator and macOS ARM.

<details>
<summary>arch migrator</summary>

<img width="789" alt="Screenshot 2023-10-12 at 1 49 30 PM" src="https://github.com/regro/cf-scripts/assets/3019665/335596a7-e713-4537-9a75-803824740a2c">

</details>

<details>
<summary>macOS ARM migrator</summary>

<img width="792" alt="Screenshot 2023-10-12 at 1 49 55 PM" src="https://github.com/regro/cf-scripts/assets/3019665/c94fbc1e-1853-4d36-9faf-121e25b2c397">

</details>

However arch migration already happened in PR ( https://github.com/conda-forge/pigz-feedstock/pull/18 ) and macOS ARM migration happened in PR ( https://github.com/conda-forge/pigz-feedstock/pull/20 )

Is there a way to clear the error status on these?

**Comment by beckermr** [comment]
yes - edit the same prepr migrator status files as we did last time.

**Comment by jakirkham** [comment]
Don't recall work on this sort of issue before, but maybe I'm misremembering

In any event, would this work? https://github.com/regro/cf-graph-countyfair/pull/7

**Comment by jakirkham** [comment]
The bot made one minor change with PR: https://github.com/conda-forge/pigz-feedstock/pull/22

Now it should both migrations as complete

Thanks Matt! 🙏
