### ISSUE TITLE
Output of conda-smithy update-cb3 is not in the PR body

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#192]
See https://github.com/conda-forge/boost-cpp-feedstock/pull/30

**Comment by jakirkham** [comment]
Also https://github.com/conda-forge/boost-feedstock/pull/56

**Comment by CJ-Wright** [comment]
Yep it seems that the `{}` is still in there. I will produce a new set of PRs soon.

**Comment by jakirkham** [comment]
Should they be getting build number bumps as well?

**Comment by scopatz** [comment]
Yeah they probably should get build numbers for tracking purposes. However, since nothing should be different about the compiled code, maybe they don't need it.

**Comment by jakirkham** [comment]
Not sure. This adds extra compiler flags to the build that were not previously present.

**Comment by CJ-Wright** [comment]
Would this be possible to fix on the conda-smithy side? Currently the only migration we do is call conda-smithy.
Attn: @isuruf

**Comment by isuruf** [comment]
Note that even without a build number bump, the new package will be uploaded because the hash changes due to presence of the compilers.

**Comment by jakirkham** [comment]
So we do upload things where the hash changes? Sorry was unsure of this detail as there was a lot of discussion on this point a while back and I thought we disabled uploads that were hash changes only.

**Comment by isuruf** [comment]
Yes, we do upload if the hash changes.

**Comment by jakirkham** [comment]
Thanks for clarifying :)
