### ISSUE TITLE
Don't run the compiler migrator twice

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#193]
See https://github.com/conda-forge/arrow-cpp-feedstock/pull/52/files

**Comment by isuruf** [comment]
Yeah. It should run from the master. Running update-cb3 on a branch that has already run update-cb3 will not work properly

**Comment by CJ-Wright** [comment]
I could produce another independent PR

**Comment by isuruf** [comment]
Or force push to the PR starting from master

**Comment by CJ-Wright** [comment]
I think generating a new PR would be easier.

**Comment by isuruf** [comment]
Will the 4 workers produce 4 PRs?

**Comment by CJ-Wright** [comment]
What do you mean? We are only running one travis worker for this.

**Comment by isuruf** [comment]
Okay, thanks.
