### ISSUE TITLE
Move to circleci

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#196]
Circle has hourly cron jobs which seems even speedier.

**Comment by asmeurer** [comment]
doctr doesn't support Circle yet https://github.com/drdoctr/doctr/issues/189

**Comment by CJ-Wright** [comment]
@asmeurer If I upload a token into `GH_TOKEN` for circle CI would that work? (I'm guessing the part that is not supported for Circle is the adding secrets part)

**Comment by asmeurer** [comment]
No, there is a lot of code that extracts things from TRAVIS_... environment variables.

**Comment by CJ-Wright** [comment]
`run_command_hiding_token` should work properly though, right?

**Comment by asmeurer** [comment]
Yeah isolated it would work (it's just a wrapper around subprocess.run). But the whole point of doctr is to automate the encrypting of the token/deploy key using Travis's public key. You would need to do that manually right now using whatever Circle's equivalent is. 

But I would suggest just adding Circle support to doctr, if you can.

**Comment by CJ-Wright** [comment]
Right, I can try to take a look at adding Circle support, although for this project it is a bit moot since we use the bot's own token for everything.

**Comment by CJ-Wright** [comment]
The move is mostly done just a few things to clean up.

1. It would be good to break up the central script into each piece as a separate run command
1. We could run the various pieces in their own cron jobs (at least 0, 1, 2 together) and have the jobs be dependent (or not) on each other. This would mean we could run 3 more frequently.
