### ISSUE TITLE
update-grayskull appending `optionaltrue` to dependencies that should be omitted

### ISSUE THREAD

**Issue by xylar** [regro/cf-scripts#1980]
We're seeing:
https://github.com/conda-forge/wetterdienst-feedstock/pull/115/commits/a22fa2b0a36be509fe061a2016e6da67d95130b7
in which a bunch of entries are being added like:
```
- crate >=0.30.1,<1optionaltrue
```
These entries should be omitted, as they are optional.  As I'm not able to reproduce this locally with grayskull [2.5.2](https://github.com/conda/grayskull/releases/tag/v2.5.2), the latest release, I think this is likely a bot issue rather than a grayskull issue.

**Comment by xylar** [comment]
This happened again in https://github.com/conda-forge/wetterdienst-feedstock/pull/116/commits/9b50adab2e4db8555888ac94498fee80bd2fd3c0

**Comment by beckermr** [comment]
this is a grayskull bug - the bot doesn't do much of anything to the outputs from grayskull

**Comment by xylar** [comment]
@beckermr, hmm, I'm not able to reproduce the issue with grayskull on its own myself.  But I will revive my bug report there.

**Comment by xylar** [comment]
Closing for now, on the assumption that this is a grayskull problem.
