### ISSUE TITLE
Missing compiler updates

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#204]
Compiling a list of things that don't to appear to have gotten updated.

* [x] https://github.com/conda-forge/clblast-feedstock
* [x] https://github.com/conda-forge/clblas-feedstock
* [x] https://github.com/conda-forge/clfft-feedstock
* [ ] https://github.com/conda-forge/clrng-feedstock
* [x] https://github.com/conda-forge/clsparse-feedstock
* [x] https://github.com/conda-forge/libprotobuf-feedstock

**Comment by justcalamari** [comment]
The bot did not skip these feedstocks, they are just later in the order the bot visits feedstocks. They should be updated eventually, but we can leave this issue up until the updates happen.

**Comment by CJ-Wright** [comment]
Awesome! Here I was getting worried.

**Comment by CJ-Wright** [comment]
@jakirkham I think clrng may be too complex for the `update-cb3` command with all the extra jinja2 formatting. I think that one may need to be done by hand.
I'm going to close, please feel free to re-open.
