### ISSUE TITLE
Black Bot

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#206]
It might be nice to have a `black` like thing for conda-forge. We could have a migrator which piggy packs on other migrators, or runs by itself. If the linter fails on a recipe we try our best to fix things (eg. remove "license" from the license, remove bad spaces, etc.)

**Comment by SylvainCorlay** [comment]
A blacksmithy?

**Comment by CJ-Wright** [comment]
This might be good to put into the `conda-smithy` package, since that has the linter and we can call it from the migrator or the webservice.

**Comment by CJ-Wright** [comment]
This could be a mini migrator.

**Comment by viniciusdc** [comment]
> This could be a mini migrator.

We could work on with `Grayskull` here ?

**Comment by CJ-Wright** [comment]
Maybe, to some extent this is done via the pip and jinja2 migration systems.

**Comment by CJ-Wright** [comment]
I think this is mostly done at this point, we do fix stylistic issues via our current migrators, and update some of the metadata with the mini migrators
