### ISSUE TITLE
null host requirements doesn't quite work

### ISSUE THREAD

**Issue by minrk** [regro/cf-scripts#212]
[this commit](https://github.com/conda-forge/mpich-feedstock/pull/21/commits/87dd223828acc7e935abd391222e7d35c59810c1) failed to build mpich on mac because it added an empty `requirements.host: None`. As a result, conda-build failed to inject the host requirements. [Setting `host: []`](https://github.com/conda-forge/mpich-feedstock/pull/21/commits/9cde1338d06a6db05712c77eba53fc37836f3f3a) when there are no host requirements seems to work, though.

I'm pretty sure this is a conda-build bug, where `host:` and `host: []` probably are meant to either behave the same or raise a TypeError on non-list host requirements. Will report upstream in a bit.

**Comment by CJ-Wright** [comment]
I think this is fixed in conda-build? Feel free to reopen.
