### ISSUE TITLE
Python 3.12 migration SVG is blank

### ISSUE THREAD

**Issue by jaimergp** [regro/cf-scripts#2121]
https://raw.githubusercontent.com/regro/cf-graph-countyfair/master/status/migration_svg/python312.svg?sanitize=true

According to the git history, it's been like that for three weeks. Is this a known bug, or intentional?

**Comment by beckermr** [comment]
Sometimes we don't write the SVGs since they get too big. Maybe this is what happened?

**Comment by isuruf** [comment]
We used a conda-forge logo for big migrations and I guess the recent website overhaul broke that link?

**Comment by beckermr** [comment]
Ahhhhh yes @isuruf. You are likely right that it is something like this.

**Comment by jaimergp** [comment]
Oh, I see. I'll take a look then, thanks!

**Comment by jaimergp** [comment]
Added https://github.com/regro/cf-scripts/pull/2125
