### ISSUE TITLE
Migration libprotobuf4251 not being performed for abi_migration_branches ?

### ISSUE THREAD

**Issue by traversaro** [regro/cf-scripts#2126]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

During libprotobuf4251  migration, we noticed that for some reason the migration is not performed for non-main branches specified in `abi_migration_branches` . 

For example, see how the `tinyxml210` migration opened two PRs in the following repos:

* https://github.com/conda-forge/libignition-msgs1-feedstock/pull/99
* https://github.com/conda-forge/libignition-msgs1-feedstock/pull/100
* https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/82
* https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/81

However, in the same repos the `libprotobuf4251` migration opened only a single PR:

* https://github.com/conda-forge/libignition-msgs1-feedstock/pull/101
* https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/83

This eventually resulted in a migration failure in a leaf feedstock that depends on older version of the dependency:
* https://github.com/conda-forge/gazebo-feedstock/pull/201

I would investigate the issue myself but I am a bit out of pointers or clues of where to start.

Originally opened in https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/5435

**Comment by traversaro** [comment]
Now the migration for gz-sim is failing with:
~~~
               linux_64_python3.10.____cpythonpython_implcpython: Could not solve for environment specs
The following packages are incompatible
├─ libabseil 20230802.*  is requested and can be installed;
├─ libgz-sensors7 is installable with the potential options
│  ├─ libgz-sensors7 7.0.0 would require
│  │  └─ libprotobuf >=3.20.1,<3.21.0a0 , which can be installed;
│  ├─ libgz-sensors7 7.0.0 would require
│  │  └─ libprotobuf >=3.21.7,<3.22.0a0 , which can be installed;
│  ├─ libgz-sensors7 7.0.0 would require
│  │  └─ libprotobuf >=3.21.10,<3.22.0a0 , which can be installed;
│  ├─ libgz-sensors7 [7.0.0|7.1.0] would require
│  │  └─ libprotobuf >=3.21.12,<3.22.0a0 , which can be installed;
│  ├─ libgz-sensors7 [7.1.0|7.2.0] would require
│  │  └─ libabseil >=20230125.2,<20230126.0a0 , which conflicts with any installable versions previously reported;
│  ├─ libgz-sensors7 7.2.0 would require
│  │  └─ libabseil >=20230125.3,<20230126.0a0 , which conflicts with any installable versions previously reported;
│  ├─ libgz-sensors7 7.2.0 would require
│  │  └─ libprotobuf >=4.23.4,<4.23.5.0a0  with the potential options
│  │     ├─ libprotobuf 4.23.4 would require
│  │     │  └─ libabseil >=20230125.3,<20230126.0a0 , which conflicts with any installable versions previously reported;
│  │     └─ libprotobuf 4.23.4, which can be installed;
│  ├─ libgz-sensors7 7.3.0 would require
│  │  └─ libprotobuf >=4.24.4,<4.24.5.0a0 , which can be installed;
│  ├─ libgz-sensors7 7.3.0 would require
│  │  └─ libprotobuf >=4.24.3,<4.24.4.0a0 , which can be installed;
│  └─ libgz-sensors7 7.3.0 would require
│     ├─ libabseil >=20230802.1,<20230803.0a0 , which can be installed;
│     └─ libprotobuf >=4.23.4,<4.23.5.0a0  with the potential options
│        ├─ libprotobuf 4.23.4, which cannot be installed (as previously explained);
│        └─ libprotobuf 4.23.4, which can be installed;
└─ libprotobuf 4.25.1.*  is not installable because it requires
   └─ libabseil >=20230802.1,<20230803.0a0 , which can be installed.
~~~

but the main branch of gz-sim actually depends on gz-sensors8, so I guess something changed w.r.t. to this. I am trying to manually migrate gz-msgs and gz-transport, let's see then what happens with that.

**Comment by traversaro** [comment]
Ok, we have a fresh example: 
* PR for gz-msgs main branch opened at https://github.com/conda-forge/gz-msgs-feedstock/pull/27
* No PR done in v9 branch (see https://github.com/conda-forge/gz-msgs-feedstock/blob/0e9a95b88da9d360bff7933f3905d00d1290bc48/conda-forge.yml#L3)

I guess the bot that opened the gz-msgs PR is https://github.com/regro/cf-scripts/actions/runs/8017507565 .

**Comment by beckermr** [comment]
We'll have to inspect the logs to see what happened. Thanks for finding this!

**Comment by traversaro** [comment]
> I guess the bot that opened the gz-msgs PR is https://github.com/regro/cf-scripts/actions/runs/8017507565 .

Ok, I am actually not sure that is the case, I was just kind of guessing.

**Comment by beckermr** [comment]
yes it is this one: https://github.com/regro/cf-scripts/actions/runs/8016339336/job/21898096473

**Comment by traversaro** [comment]
Actually I was trying to understand the code, and I noticed `abi_migration_branches`. Perhaps an `abi_` is missing in https://github.com/regro/cf-scripts/blob/49da25ca2e8f3e1e26fa17c60edfe2898e2a7c0b/conda_forge_tick/migrators/core.py#L236 ? See https://github.com/regro/cf-scripts/pull/2061 .

**Comment by traversaro** [comment]
> Actually I was trying to understand the code, and I noticed `abi_migration_branches` is never used in the code base. Perhaps an `abi_` is missing in
> 
> https://github.com/regro/cf-scripts/blob/49da25ca2e8f3e1e26fa17c60edfe2898e2a7c0b/conda_forge_tick/migrators/core.py#L236
> ? See #2061 and in particular https://github.com/regro/cf-scripts/pull/2061/files#diff-d086989bef97d201dc5b0a71e66fa9b913efbbd080f58b2185cea7f42968d5daL245 .

I think it is just easier to open a PR with the proposed fix: https://github.com/regro/cf-scripts/pull/2154 .

**Comment by h-vetinari** [comment]
Nice! Now I know why I got flooded with PRs to maintenance branches over several feedstocks 😆 

Can we write a test that would catch the chopping off of "abi_" (happened in e0c0f9524da4bd796e03e72d0198de82ae2b49f0)?

**Comment by h-vetinari** [comment]
One thing that I've been thinking about for a long time that - among other things - would make this easier to catch, would be to show the migration branches on the migrator status page as well.

Like say, with the following abi_migration_branches [spec](https://github.com/conda-forge/arrow-cpp-feedstock/blob/161d0c0ef5259f93699c4c9d0b63816a872c6d1f/conda-forge.yml#L4-L8), to have the status page show all of: 
```
* arrow-cpp                 # main
* arrow-cpp [14.x branch]
* arrow-cpp [13.x branch]
* arrow-cpp [12.x branch]
```

Then it would be easy to catch the cases where the rerender failed on a migration branch, which is currently invisible unless one directly goes to the bot log.

**Comment by traversaro** [comment]
Fixed by https://github.com/regro/cf-scripts/pull/2154, now we have the missing migrations: https://github.com/conda-forge/gz-msgs-feedstock/pull/28/files .
