### ISSUE TITLE
Migrator webpage

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#213]
It might be very helpful to list which things need migration (per migrator) and the status: pending, PRed, bad, accepted.
Accepted is provisional since that would require us to either know 
1. that the PR got merged
1. that the recipe no longer passes the conditional excluding the existing "don't PR on things we PRed" condition. (on a related note we may want/need the filter mechanic to be a list/dict so we can pop things off it that we don't want/need)

**Comment by scopatz** [comment]
This would be great to have and pretty easy to build via the REST API if the data was put into the database.

**Comment by CJ-Wright** [comment]
I think this is mostly done by the status page
