### ISSUE TITLE
Duplicate macOS ARM migrator PRs for `deltalake`

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#2138]
After adding `deltalake` to the macOS ARM migration ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5483 ), the bot opened a migration PR and then ~1hr later opened another one. Here are the PRs

* https://github.com/conda-forge/deltalake-feedstock/pull/25
* https://github.com/conda-forge/deltalake-feedstock/pull/26

Some things to note:

* The feedstock has only one branch
* Both PRs target `main`
* Both PRs were opened today ~1hr apart
* No other changes occurred to `main` today

Was there some kind of hiccup in the bot?

**Comment by jaimergp** [comment]
I observed this today but with a version update:

* https://github.com/conda-forge/constructor-feedstock/pull/74
* https://github.com/conda-forge/constructor-feedstock/pull/75

**Comment by beckermr** [comment]
Yes I think I know the cause. GHA is killing some bot jobs due to disk usage and so they are not deploying their changes to the graph. 

If you all know of a way to delete some data on the runners, that'd be cool. We should also figure out what is taking so much space.

**Comment by jakirkham** [comment]
The conda-smithy [GHA purge logic]( https://github.com/conda-forge/conda-smithy/blob/63ae4123df0a8b8ae035b0694a3f1e00d47d9ad0/conda_smithy/templates/github-actions.yml.tmpl#L59-L84 ) works pretty well

**Comment by jakirkham** [comment]
Should add have seen the same issue Jaime has in a few places. For example:

* https://github.com/conda-forge/google-cloud-orchestration-airflow-feedstock/pull/22
* https://github.com/conda-forge/google-cloud-orchestration-airflow-feedstock/pull/23
