### ISSUE TITLE
Run compiler syntax migration in topo order

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#214]
This way we can start moving the compilers proper ASAP.

**Comment by isuruf** [comment]
> This way we can start moving the compilers proper ASAP.

Can you elaborate a bit more?

**Comment by justcalamari** [comment]
I think what he means is if we PR syntax updates in topo order, we can start rebuilding

**Comment by CJ-Wright** [comment]
Yep. To expand a little bit, if we want to start trying out the new compilers in their own channel and everything we need to have the syntax moved. Currently we are moving the syntax in the order that networkx puts out, but this could cause roadblocks if a critical package was at the end. If we do the syntax migrations in topo order then the first things to be migrated would be those which would also be first for the actual compiler migration.

**Comment by justcalamari** [comment]
Solved by #225
