### ISSUE TITLE
Blacklist ci_test from upstreams

### ISSUE THREAD

**Issue by rmax** [regro/cf-scripts#220]
Example: https://github.com/conda-forge/python-confluent-kafka-feedstock/pull/8

The version in the PR is not publicly available in PyPI: https://pypi.org/project/confluent-kafka/#history

![confluent-kafka_ _pypi](https://user-images.githubusercontent.com/26015/42009835-6b492622-7a62-11e8-8a90-4c70633f1aa4.jpg)

**Comment by CJ-Wright** [comment]
The current upstream URL is pointing at github. We pull the upstreams based on the URL listed in `source`.
I think the best answer to this is to blacklist `ci_test` at this point.

**Comment by isuruf** [comment]
It would be good to switch the url to PyPI

**Comment by rmax** [comment]
That's right. In [this commit](https://github.com/conda-forge/python-confluent-kafka-feedstock/commit/98e5d66fe9e4bad62bb38fa897affe2da22d77bb#diff-e178b687b10a71a3348107ae3154e44c) the source was changed from pypi to github.

@jvansanten by any chance do you remember why was the case?

Probably we should go back to the pypi source in the recipe.

**Comment by CJ-Wright** [comment]
Would you mind if I closed this issue, this seems like a feedstock specific issue and not a bot one.
If you'd like to discuss this more, please open an issue against the feedstock itself.

**Comment by rmax** [comment]
@CJ-Wright sounds good to me, thanks.
