### ISSUE TITLE
Missing version update with sqlite

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#222]
Transferring from PR ( https://github.com/conda-forge/sqlite-feedstock/pull/28 ).

It appears the bot knew an update was needed and issued a PR, but that PR did not include a version bump.

**Comment by justcalamari** [comment]
That PR was from 25 days ago, so I'm not sure if that is a current issue or something that has been fixed. Please let us know if this problem comes up again in new PRs to help us debug.

**Comment by jakirkham** [comment]
That's true. Though suspect this issue is still live. The version needs some [massaging]( https://github.com/conda-forge/sqlite-feedstock/blob/master/recipe/meta.yaml#L2-L6 ) to fit it into the [URL]( https://github.com/conda-forge/sqlite-feedstock/blob/master/recipe/meta.yaml#L13 ). Would imagine this causes some challenges for the autoupdate bot unless there have been specific changes to address this.

**Comment by jakirkham** [comment]
Agree that it should, but it did not. Hence the suspicion. Have not confirmed it yet.

**Comment by CJ-Wright** [comment]
The bot seems to be able to handle this now
