### ISSUE TITLE
duplicate PRs opened by bot

### ISSUE THREAD

**Issue by braingram** [regro/cf-scripts#2237]
I'm not sure if this is a re-occurance of https://github.com/regro/cf-scripts/issues/1586
but asdf-standard recently made a pypi release which triggered 2 PRs for asdf-standard-feedstock:
https://github.com/conda-forge/asdf-standard-feedstock/pull/4
https://github.com/conda-forge/asdf-standard-feedstock/pull/5
These PRs appear identical and use the same sha256 hash for the source in `meta.yml`.

Should I just close the old PR or is it helpful to look at logs, etc? Also, please let me know if I'm overlooking something different between the two PRs.

Thanks!

**Comment by beckermr** [comment]
duplicate of #2138 - closing in favor of that issue
