### ISSUE TITLE
Version bump bot opens multipe PRs

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#2238]
Seen across the LLVM stack today - some (though not all) feedstocks get 2 or even 3 identical PRs (all targeting `main`):
* https://github.com/conda-forge/llvmdev-feedstock/pull/254
* https://github.com/conda-forge/llvmdev-feedstock/pull/255
* https://github.com/conda-forge/llvmdev-feedstock/pull/256
* https://github.com/conda-forge/openmp-feedstock/pull/115
* https://github.com/conda-forge/openmp-feedstock/pull/116
* https://github.com/conda-forge/flang-feedstock/pull/40
* https://github.com/conda-forge/flang-feedstock/pull/41
* https://github.com/conda-forge/lldb-feedstock/pull/58
* https://github.com/conda-forge/lldb-feedstock/pull/59
* https://github.com/conda-forge/lldb-feedstock/pull/60

**Comment by beckermr** [comment]
Probably the bot job issues we've had per #2138

**Comment by xylar** [comment]
This issue does not appear to be fixed:
https://github.com/conda-forge/google-cloud-dlp-feedstock/pull/47
https://github.com/conda-forge/google-cloud-dlp-feedstock/pull/48

**Comment by beckermr** [comment]
See my comment on the PR.
