### ISSUE TITLE
broken `pyscal_dev::pyscal` package

### ISSUE THREAD

**Issue by ytausch** [regro/cf-scripts#2262]
We tried to delete invalid files referring to a `pascal_dev::pyscal` package in https://github.com/regro/cf-graph-countyfair/pull/18, however the bot keeps creating files referring to this ghost package.

See
- https://github.com/regro/cf-graph-countyfair/blob/master/pr_info/4/d/1/c/6/pyscal_dev%3A%3Apyscal.json
- https://github.com/regro/cf-graph-countyfair/blob/master/version_pr_info/4/d/1/c/6/pyscal_dev%3A%3Apyscal.json

There certainly is something weird about the `pyscal` package, there are yanked versions of it: [pyscal](https://prefix.dev/channels/conda-forge/packages/pyscal)

Do you have any ideas here @beckermr? This issue is a bit annoying because it breaks the automatic schema validation code.

**Comment by beckermr** [comment]
Yes I know how to fix. We have to remove in the mongodb backend.

**Comment by beckermr** [comment]
This should be fixed now. With the new backend stuff we need to provide interfaces for deleting / adjusting files that respect the mongodb backend. Or I can swap them so the file is the primary and mongo gets synced.

**Comment by beckermr** [comment]
this file has not come back so I am going to close this.

**Comment by beckermr** [comment]
I think that will work yes. I'll make the change in a pr.
