### ISSUE TITLE
Merging PR "Migrate to Jinja2 compiler syntax" failed some CI

### ISSUE THREAD

**Issue by MSeifert04** [regro/cf-scripts#233]
The tests for the PR actually all passed (https://github.com/conda-forge/iteration_utilities-feedstock/pull/21) but when I merged it a lot of tests turned red:

CircleCI (https://circleci.com/gh/conda-forge/iteration_utilities-feedstock/55):
```
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"libgcc-ng[version='>=4.9']"}
Exited with code 1
```

Travis (https://travis-ci.org/conda-forge/iteration_utilities-feedstock/jobs/398433547):
```
conda.CondaMultiError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/conda-forge/osx-64/tk-8.6.7-0.tar.bz2>
```

Unfortunately I don't have time to investigate these failures currently but is it possible that these errors are because of the PR?

**Comment by CJ-Wright** [comment]
I'm restarting the travis job to see if the URL just did something odd. I'm not certain about the `libgcc-ng` error. Will follow up with core.

**Comment by isuruf** [comment]
It was just a network error

**Comment by MSeifert04** [comment]
Thank you!
