### ISSUE TITLE
Transparent Profile Icon Background

### ISSUE THREAD

**Issue by ytausch** [regro/cf-scripts#2388]
This is really a minor issue bot just FYI: The [bot user](https://github.com/regro-cf-autotick-bot)'s profile icon is black on a transparent background, which makes it invisible when using the dark GitHub theme.

**Comment by beckermr** [comment]
I have the SVG file if you know how to fix this.

**Comment by beckermr** [comment]
I think I fixed this, but I am not seeing picture update.

**Comment by beckermr** [comment]
fixed!

**Comment by ytausch** [comment]
Amazing, thanks!
