### ISSUE TITLE
Noarch python migrator should check for post-link/activate scripts

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#240]
This is easy enough to do and should skip 60 jupyter-nbextension packages.

**Comment by CJ-Wright** [comment]
Currently we don't capture that information in the graph but we could do it. Are all post-link/activate script feedstocks not noarch?

**Comment by CJ-Wright** [comment]
What do you mean "has access to `recipe_dir`"? I was thinking of compiling a list of known files that could live in the "recipe_dir" and try poking each one when running the `make_graph` stage. Then we could tabulate which feedstocks have which extra files. Then we would have enough info to start skipping things, maybe?

**Comment by isuruf** [comment]
I was thinking of skipping here, https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L447

**Comment by CJ-Wright** [comment]
@scopatz thoughts? Should we catch this when making the graph or during the migration?

**Comment by CJ-Wright** [comment]
We aren't currently keeping the list of files in the feedstocks graph, although we could.

**Comment by scopatz** [comment]
> We aren't currently keeping the list of files in the feedstocks graph, although we could.

Do you want to? Would this have other uses outside of this issue?

**Comment by CJ-Wright** [comment]
It might be useful to know if a recipe is using a config file so we can load it during the parsing although we could also handle this another way.
