### ISSUE TITLE
Noarch todo list format off

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#241]
This may already be fixed. In any event, the todo list is incorrectly formatted here (missing a space between `[]`). So it doesn't render as a todo list.

xref: https://github.com/conda-forge/dask-ndmeasure-feedstock/pull/4

**Comment by CJ-Wright** [comment]
Yep, this has been taken care of.

**Comment by jakirkham** [comment]
Happened again today with compiler migration.

xref: https://github.com/conda-forge/gtk2-feedstock/pull/1

**Comment by CJ-Wright** [comment]
I don't think we have a checklist for the compiler migration. Could you clarify what you mean?

**Comment by jakirkham** [comment]
See screenshot of linked PR OP below.

Is it suppose to be bullet points? There's also no line break after introducing the list.

<hr>

<img width="1013" alt="screen shot 2018-07-05 at 18 59 07" src="https://user-images.githubusercontent.com/3019665/42351935-94f2e804-8085-11e8-828f-f67c73b8b0ee.png">

**Comment by justcalamari** [comment]
It wasn't intended to be bullet points, this is just the output from conda smithy that is supposed to go to stdout. We could change it to be a bullet point list, though.
