### ISSUE TITLE
Fortran compiler incorrectly assumed

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#242]
Appears the migration script assumed Fortran was required for `fftw`. While an option, we don't currently support this. This wound up causing a build issue on Windows.

ref: https://github.com/conda-forge/fftw-feedstock/pull/43#pullrequestreview-134069677

**Comment by CJ-Wright** [comment]
Could you take this up with conda-smithy? The majority of the running migration code for this migration is there.

**Comment by jakirkham** [comment]
This issue was moved to conda-forge/conda-smithy#826

**Comment by CJ-Wright** [comment]
Thank you!
