### ISSUE TITLE
Compiler added to build and host

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#243]
Seem to have the `compiler` added to `build` and `host` in this case despite `toolchain` only being used in `build`. Also an empty `host` section is added in addition to the one with the `compiler`.

xref: https://github.com/conda-forge/libgpuarray-feedstock/pull/18#pullrequestreview-134081161

**Comment by CJ-Wright** [comment]
Could you take this up with conda-smithy? The majority of the running migration code for this migration is there.

**Comment by jakirkham** [comment]
This issue was moved to conda-forge/conda-smithy#827

**Comment by CJ-Wright** [comment]
Thank you!
