### ISSUE TITLE
Migrate to CB3 strange adding two "host" sections

### ISSUE THREAD

**Issue by sodre** [regro/cf-scripts#245]
In conda-forge/python-pkcs11-feedstock#2 the migration script ended up adding two `host` sections and bumped up the build number from `0` to `2` instead of 1.

cf: [meta.yaml](https://github.com/regro-cf-autotick-bot/python-pkcs11-feedstock/blob/524ad11c4987175147f368b4d376ac64fdd8d16c/recipe/meta.yaml)

**Comment by CJ-Wright** [comment]
Would you mind opening an issue at conda-smithy? We're just providing the PRing engine in the CB3 migrator, conda-smithy is doing the heavy lifting.

**Comment by isuruf** [comment]
This is an issue with the bot running the conda-smithy script twice

**Comment by CJ-Wright** [comment]
Ah, oh sorry. :sheep: @sodre would it be possible to revert the most recent commit? (I thought I had caught all the PRs which had slipped the net, grrrrr)
