### ISSUE TITLE
Local tests now need docker

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#2460]
This is probably a by-product of @beckermr's recent work on hardening security (e.g. in [`conda_forge_tick/utils.py`](https://github.com/regro/cf-scripts/blame/master/conda_forge_tick/utils.py)), but is it really necessary that even the testing of a migrator now needs a docker daemon to run?

I was trying to add a new test for a corner case of the stdlib migration, but cannot run the tests locally on my windows machine anymore, which makes this much harder to do.

**Comment by beckermr** [comment]
I'll edit the setup to ensure if docker is not found they still run. Sorry for the trouble.
