### ISSUE TITLE
Piggyback migrator to drop `{{ pin_compatible("numpy") }}`

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#2469]
As `numpy` already [contains a `run_exports`]( https://github.com/conda-forge/numpy-feedstock/blob/b60684fab0eae8c1d9f51ba30adcd03c8691bf87/recipe/meta.yaml#L29-L30 ), which has been present since `numpy` version `1.22.3` number `1` ( https://github.com/conda-forge/numpy-feedstock/pull/262 ), and conda-forge is using [`numpy` version `1.22` or newer]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/f3a458a625609f36daaa4cad5ddc6a69615a9fab/recipe/conda_build_config.yaml#L701-L706 ), we can just rely on `run_exports` from `numpy` and drop `pin_compatible` from recipes

This is also important to prepare for building with `numpy` version `2.0`, which builds packages with `numpy` version `1.x` and `2.x` support. As such `pin_compatible` would be unnecessarily strict by restricting packages built with it  to `numpy` version `2.x` when `1.x` could have also been supported

As a result (based on discussion at the core meeting), we decided to add a piggyback migrator that would remove `{{ pin_compatible("numpy") }}`. This would help prepare for the NumPy 2 migrator. It also could couple with that migrator to upgrade to NumPy 2 and clean this pinning out at the same time

**Comment by jakirkham** [comment]
cc @h-vetinari @isuruf @rgommers (please feel free to add or correct anything here)

**Comment by jakirkham** [comment]
cc @beckermr (for awareness)

**Comment by beckermr** [comment]
We need doc changes and possibly adjustments to the linter as well. Not sure if those were covered.

**Comment by jakirkham** [comment]
Please see issue: https://github.com/conda-forge/conda-forge.github.io/issues/2156

Feel free to add anything else there
