### ISSUE TITLE
Handle build variants in conda_build_config.yaml

### ISSUE THREAD

**Issue by justcalamari** [regro/cf-scripts#247]
make_graph is failing on many recipes that have a conda_build_config.yaml since it doesn't know how to replace some jinja variables.

**Comment by CJ-Wright** [comment]
Hmm, are we not providing a default dict thing during the parsing or do we need the variables to properly run our operations?

**Comment by justcalamari** [comment]
What do you mean by default dict thing?

The requirements that are unknown jinja variables (like `{{ mpi }}`) are read as `None`, and then we do `x.split()` on all the requirements. We could just remove `None` from the list of reqs before split, but we should be tracking all the requirement, though maybe that's something switching to libcf will take care of.
