### ISSUE TITLE
Multithreading causes problems in parse

### ISSUE THREAD

**Issue by justcalamari** [regro/cf-scripts#249]
When we call parse from conda-build, it uses the context manager `stringify_numbers` which solves the problem of dropping trailing zeros in version numbers. The problem is this context manager uses a shared variable (`yaml.Resolver.yaml_implicit_resolvers`). Entering the context manager removes keys from the `yaml.Resolver.yaml_implicit_resolvers` dict, but they may have already been deleted in another thread, raising an error. This can be solved on the conda-build side by making `stringify_numbers` an asynchronous context manager, if there is interest. This could also be solved on the cf-scripts side, but we may need to parse without using conda-build.

CC @msarahan

**Comment by CJ-Wright** [comment]
We could also separate the async request part from the parse part.

**Comment by mariusvniekerk** [comment]
Or we could just use multiprocessing (or dask distributed)

**Comment by CJ-Wright** [comment]
Would multiprocessing have the correct await/async request behavior?

**Comment by justcalamari** [comment]
Solved by #250

**Comment by CJ-Wright** [comment]
It turns out this would be nice to have, since adding things to a dict with async threads is nice.
