### ISSUE TITLE
re-syntax cython?

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#255]
Do we need to also provide a new syntax to cython?

**Comment by CJ-Wright** [comment]
@isuruf

**Comment by isuruf** [comment]
What do you mean?

**Comment by CJ-Wright** [comment]
Do we need to run the `update-cb3` scrip for things that use cython (currently we only check for `toolchain` or `gcc`)

**Comment by mariusvniekerk** [comment]
probably we can get the tail end by looking at the output of libcflib's artifact info and seeing what produces shared objects
