### ISSUE TITLE
missed edge case in check solvable forced PRs

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#2627]
So we missed an edge case in the check solvable stuff we just did. Sometimes a feedstock will get rerendered and have no `.ci_support` files. This can happen for many reasons, from bugs in skips (https://github.com/conda-forge/wstools-feedstock/blob/main/recipe/meta.yaml#L17) to feedstocks that never updated to python 3. We used to report solver failures for these feedstocks, but now we are issuing PRs for them that turn off all builds. 

I don't feel too badly about either solution here, but we may want to do something in the PR we issue to give notice to the maintainer that something weird happened. Otherwise, the PR will be all green and they may not notice there are no builds. 

I think the simplest solution would be to have the linter fail in this case. Thoughts?

cc @h-vetinari @jakirkham @jaimergp

**Comment by h-vetinari** [comment]
I agree that this is a tricky case, but I'm actually glad that we're opening PRs for this, because it's usually easy to just remove the offending skips.

> I think the simplest solution would be to have the linter fail in this case. Thoughts?

Fully agreed, we should complain through the linter if there are no outputs/configs left.
