### ISSUE TITLE
Version update for SPIRV-Headers does not find new versions

### ISSUE THREAD

**Issue by ZzEeKkAa** [regro/cf-scripts#2648]
Latest version could not be found for SPIRV-Headers repo.

https://github.com/KhronosGroup/SPIRV-Headers/tags:

- [vulkan-sdk-1.3.283.0](https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/vulkan-sdk-1.3.283.0)
- [vulkan-sdk-1.3.280.0](https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/vulkan-sdk-1.3.280.0)
- [vulkan-sdk-1.3.275.0](https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/vulkan-sdk-1.3.275.0)
- [vulkan-sdk-1.3.268.0](https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/vulkan-sdk-1.3.268.0)
- [sdk-1.3.261.1](https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/sdk-1.3.261.1)
- ...

The output log:
https://github.com/conda-forge/spirv-headers-feedstock/actions/runs/9194155960/job/25286899521
```
2024-05-22 15:27:35,598 INFO     webservices_dispatch_action.version_updater || getting latest version
2024-05-22 15:27:46,677 INFO     webservices_dispatch_action.version_updater || curr version|latest version: 1.3.268.0|1.3.261.1
```

**Comment by ZzEeKkAa** [comment]
After digging into the issue, it is because `vulkan-sdk-` prefix contains `a` and it is treated as alpha version:
https://github.com/regro/cf-scripts/blob/main/conda_forge_tick/update_sources.py#L147

**Comment by isuruf** [comment]
I think you can add
```
bot:
  version_updates:
    sources:
      - rawurl
```
to https://github.com/conda-forge/spirv-headers-feedstock/blob/main/conda-forge.yml
and this should work.

**Comment by isuruf** [comment]
Hmm, maybe not since the versions are not consecutive
