### ISSUE TITLE
pysmb - new version - 1.2.7 (with a bug) -> 1.2.9.1

### ISSUE THREAD

**Issue by RJBrower** [regro/cf-scripts#2654]
pysmb-feedstock/recipe/meta.yaml is set for version 1.2.7 and is now outdated. pysmb versions before 1.2.8 contain a bug in the underlying md4.py file. This is fixed in 1.2.8, and 1.2.9.1 is already available. Please update the version for conda-forge.

**Comment by beckermr** [comment]
Anyone is free to make a pr directly on the feedstock to update the version. This repo / tracker is for bugs in the automation. Please direct your issue to the appropriate feedstock.

**Comment by beckermr** [comment]
I am going to close this one for now. If you need more help, please feel free to reach out in our element / gitter channel.
