### ISSUE TITLE
"internal error in the bot, depfinder, or grayskull" on nearly all feedstocks

### ISSUE THREAD

**Issue by xylar** [regro/cf-scripts#2656]
I'm seeing:
```
We couldn't run dependency analysis due to an internal error in the bot, depfinder, or grayskull.
```
on nearly all feedstocks I maintain and have for several weeks.  Examples include:
https://github.com/conda-forge/validators-feedstock/pull/30
https://github.com/conda-forge/yandex-query-client-feedstock/pull/1
https://github.com/conda-forge/geometric_features-feedstock/pull/31
https://github.com/conda-forge/google-cloud-bigquery-feedstock/pull/157
https://github.com/conda-forge/flask-limiter-feedstock/pull/9

I can post many more if it is helpful.

**Comment by beckermr** [comment]
I added some extra logging to see what the error is. Hopefully the next time we see one we can figure this out. Sorry for the trouble!

**Comment by xylar** [comment]
@beckermr, thanks so much for the quick response!  I'll keep you posted on what I see.

**Comment by xylar** [comment]
@beckermr, how soon should I expect the new error message to appear?  I'm seeing the same issue with:
https://github.com/conda-forge/alibabacloud-credentials-feedstock/pull/1
I didn't see the error message in the bot logs linked from there but I have to admit that I don't really know my way around.

**Comment by beckermr** [comment]
It takes at least a few hours. I'd check again tomorrow.

**Comment by xylar** [comment]
Perfect thanks!  I'll be away over the weekend so will see how things look early next week.
