### ISSUE TITLE
openmpi5 migration failed to make PRs for libnetcdf and libpnetcdf

### ISSUE THREAD

**Issue by akrherz** [regro/cf-scripts#2694]
My sincere apologies if this is not the appropriate place/repo to report this issue, but @xylar and I noticed that the on-going `openmpi5` migration missed `libnetcdf` and `libpnetcdf`.  I can't see these on the [status page](https://conda-forge.org/status/migration/openmpi5) and I checked a recent bot-bot run without any logs that I could see.

manual migrations made here:
conda-forge/libnetcdf-feedstock#192
conda-forge/libpnetcdf-feedstock#7

PS, the new conda-forge status page is so great, I cried with joy when I first saw it.

**Comment by jaimergp** [comment]
I found these two files:

- [node_attrs](https://github.com/regro/cf-graph-countyfair/blob/953e199d21f0374683d1a2ecb1b04ddd7e9918c2/node_attrs/5/d/9/3/7/libnetcdf.json#L482)
- [pr_info](https://github.com/regro/cf-graph-countyfair/blob/953e199d21f0374683d1a2ecb1b04ddd7e9918c2/pr_info/5/d/9/3/7/libnetcdf.json#L4)

node_attrs has no matches for openmpi (just a selector). It does have mpich.

pr_info mentiones the openmpi variants in the curl8 unsolvable errors...

Maybe a bug processing variants?

**Comment by minrk** [comment]
fftw was also skipped, and doesn't show openmpi (or mpich) in its [dependencies](https://github.com/regro/cf-graph-countyfair/blob/f2bcafdf5f04bcd5107ebcf0e94842c704fe55c7/node_attrs/f/2/3/9/8/fftw.json)

**Comment by beckermr** [comment]
yep indeed looks like a bug when the bot parses the feedstock. :/

**Comment by beckermr** [comment]
So the bug is due to this change here: https://github.com/regro/cf-scripts/pull/1579/files

For reasons that are hard to reconstruct, we place the `conda_build_config.yml` next to the recipe while parsing. This was needed to fix other things, but now the code is picking up more variants than it should and it looses the mpi ones when it collapses them back down. I'm working on a fix.

**Comment by beckermr** [comment]
I merged a fix that produces the correct metadata. This won't propagate into the bot metadata for several hours at least.

**Comment by beckermr** [comment]
The PR for fftw was issued so I think we solved this. The bot may not get back to libnetcdf and libpnetcdf or might mark them as done manually. I am going to close for now. Feel free to reopen if you find issues.
