### ISSUE TITLE
regro-cf-autotick-bot tags C extension with noarch

### ISSUE THREAD

**Issue by amueller** [regro/cf-scripts#270]
the regro-cf-autotick-bot suggested to tag wordcloud with noarch even though it has a C extension:
https://github.com/conda-forge/wordcloud-feedstock/pull/10

Not sure what the bot is supposed to do, or if it's supposed to detect that (I haven't written the recipe and I didn't see the extension showing up at a quick glance).

**Comment by CJ-Wright** [comment]
This is part of the reason why we have the checklist for the maintainers and why the PR is marked as a suggestion. The bot currently doesn't have the needed levels of information (or automagic) to know if there are compiled extensions. However, usually if there is a compiled extension then it needs a compiler either via `toolchain` or the new `{{ compiler('c') }}` syntax. Is it possible that that recipe is missing a compiler?

**Comment by CJ-Wright** [comment]
(although we are interested in adding this kind of automagic, we just haven't had the time)

**Comment by amueller** [comment]
Ok cool, feel free to close.
