### ISSUE TITLE
Dealing with non-mergeable things

### ISSUE THREAD

**Issue by mariusvniekerk** [regro/cf-scripts#271]
If a pull request is not mergeable we probably want to have a process that can use the "mergable" status flag to detect if we have conflicts.  

We can then probably just abandon that PR and recreate it.

**Comment by CJ-Wright** [comment]
Extending from side convo:
It would be good to have a label for feedstocks that would tell the bot to do a re-do of the PR, either by just re-running the migrator (if the migrator is re-run safe) which would push to the same branch and add a commit, or by scrapping the entire PR (closing it with a message as to why) and opening a new PR.

**Comment by CJ-Wright** [comment]
this exists
