### ISSUE TITLE
Bug in migrate script?

### ISSUE THREAD

**Issue by hajapy** [regro/cf-scripts#273]
Have a look at https://github.com/conda-forge/protobuf-feedstock/pull/50/files#diff-e178b687b10a71a3348107ae3154e44cR22

`- libprotobuf {{ version }}` was changed to `- libprotobuf    version }}` by the bot..

**Comment by justcalamari** [comment]
Thanks for putting this in, @hajapy. I think this is actually a [conda-smithy](https://github.com/conda-forge/conda-smithy) issue, as the bot's migration code comes from there.
