### ISSUE TITLE
404 github errors

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#275]
It seems that we have quite a few (42) 404 errors from github. I'm not certain why we're getting them. It would be good to print out the url to check it's validity.

xref: https://github.com/conda-forge/sympy-feedstock/issues/10

**Comment by justcalamari** [comment]
Maybe this is due to switching to a new version of github3.py. We used to do 
```
fork_repo = gh.repository($USERNAME, feedstock_reponame)
if fork_repo is None or (hasattr(fork_repo, 'is_null') and
                                     fork_repo.is_null()):
    print("Fork doesn't exist creating feedstock fork...")
    repo.create_fork()
```
to fork if one doesn't exist, but now the line `fork_repo = gh.repository($USERNAME, feedstock_reponame)` is giving an error.

**Comment by CJ-Wright** [comment]
Ah is that the source of the 404 errors or a different error?

**Comment by justcalamari** [comment]
Yup that's giving 404 errors.

**Comment by CJ-Wright** [comment]
Hmm ok. It seems that `create_fork()` still exists https://github3.readthedocs.io/en/develop/api-reference/repos.html#github3.repos.repo.Repository.create_fork but maybe it is an error in github3.py?
