### ISSUE TITLE
Compiler migration of Cython packages

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#276]
Would be good to also migrate anything to new compilers that is using `cython` in `build`. This is important if they weren't using the `toolchain` for some reason.

**Comment by CJ-Wright** [comment]
Is there a syntax migration needed for cython?

**Comment by CJ-Wright** [comment]
Ok, That should be doable, assuming that `update-cb3` is ok with no toolchain. We can have the filter include cython.

**Comment by mariusvniekerk** [comment]
We should make use of libcfgraph for this and just see if we have a shared object or similar in the files list.

**Comment by CJ-Wright** [comment]
For the time being can we just output as list of all "compiled" things from libcfgraph? I'd love to have automatic interopt but I'd settle for getting the wheels turning on this. I guess we can do the package->feedstock translation by hand?

**Comment by jakirkham** [comment]
It’s not that easy to do all manually. I did a few, but this just won’t scale. Especially if we want to switch to new compilers soon.

**Comment by jakirkham** [comment]
Should add would hope checking for `cython` would make it easier to catch some of these. Had a list of other ideas in issue ( https://github.com/regro/cf-scripts/issues/277 ).

**Comment by CJ-Wright** [comment]
I think this part is done (after a few hiccups).
