### ISSUE TITLE
Migrating things without toolchain

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#277]
There are quite a few things that were not using `toolchain`. How should we migrate them? Here are some thoughts...

* Detect if they used other build tools in `build` (e.g. `cmake`, `automake`, `autconf`, `libtool`, `m4`, `pkg-config`, `ninja`, `jom`, etc.)
* Look for `vc` anywhere.
* Search `build.sh`/`bld.bat` for `make`, `nmake`, etc.
* Check for `python` in `build` only for Windows.
* Check for explicit use of `gcc`.
* Check `run` for `libgcc` or `libgfortran`.

Other suggestions?

**Comment by CJ-Wright** [comment]
* `cython`
* ship any `.so` files?

**Comment by CJ-Wright** [comment]
I think many of these things are done, please feel free to PR more in!

**Comment by CJ-Wright** [comment]
@mariusvniekerk used [libcfgraph](https://github.com/regro/libcfgraph) to hunt those down I think

**Comment by jakirkham** [comment]
Did this include `.dylib`s?

**Comment by CJ-Wright** [comment]
I don't know.
