### ISSUE TITLE
Undocumented bot option `version_updates.skip` in conda-forge.yml

### ISSUE THREAD

**Issue by ytausch** [regro/cf-scripts#2816]
This PR: https://github.com/regro/cf-scripts/pull/2646 introduced a configuration option for the bot which is not documented and not reflected in the Pydantic model.

**Comment by ytausch** [comment]
xref: https://github.com/conda-forge/conda-smithy/pull/1969

**Comment by jakirkham** [comment]
Now that the aforementioned PR is merged, should we close?
