### ISSUE TITLE
Convert `{{ posix }}pkg-config` to `pkg-config`

### ISSUE THREAD

**Issue by mfansler** [regro/cf-scripts#2847]
Todo from R migration...

              This change should be in the mini migrator

_Originally posted by @isuruf in https://github.com/conda-forge/r-httpuv-feedstock/pull/43#discussion_r1676963561_

**Comment by isuruf** [comment]
Code is at https://github.com/regro/cf-scripts/blob/64fe89a89b90dc72f99c0aed0580cc85012e8653/conda_forge_tick/migrators/r_ucrt.py#L21

Do you want to send a PR? If not, I'll send one.
