### ISSUE TITLE
How to disambiguate `closed` from `paused` migrators?

### ISSUE THREAD

**Issue by jaimergp** [regro/cf-scripts#2885]
There's a feature request for the conda-forge.org/status page, where users would like to see "Paused migrators" separate from the actually "Closed ones". AFAIK, this information is not exposed in cf-graph-countyfair/status, so I'm looking into the necessary changes that would be needed.

My findings so far:

* `conda_forge_tick.status_report.main()` gathers the existing migrators from conda-forge-pinning and the payloads from cf-graph-countyfair.
* Then it diffs the old "total" list with the new "total" list. Anything not in the new total is considered closed and included in the "closed" JSON for two weeks.

So, if I manage to identify a `paused` migrator from [`mgconf` object here](https://github.com/regro/cf-scripts/blob/f6b95457760d93157f6cda751cbbfc2a3d7ef493/conda_forge_tick/status_report.py#L429-L433), then I can include it in a separate list and report it on its own section. Cool!

My question is how to better expose the `paused` boolean, because as far as I can tell, these are ignored in the [`migration_factory()`](https://github.com/regro/cf-scripts/blob/f6b95457760d93157f6cda751cbbfc2a3d7ef493/conda_forge_tick/make_migrators.py#L469-L470). What should I write in that hypothetical `else:` clause? Shall I add a `paused` boolean to the base `Migrator` class? Then what? 😬 

Any feedback or pointers will be welcome, thanks!

**Comment by jaimergp** [comment]
Still an issue. I think we'll need to dump the paused migrators too, maybe in this block:

https://github.com/regro/cf-scripts/blob/9ec83bb42ea67bc8d0d5f75a3b42f6993f8df96c/conda_forge_tick/make_migrators.py#L469-L487

**Comment by beckermr** [comment]
We'll need to add skips for them when loading in certain places. This should be straight forward.
