### ISSUE TITLE
How to deal with patches

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#29]
@CJ-Wright commented on [Sat Feb 24 2018](https://github.com/regro/cf-graph/issues/32)

Should we clear out patches on version bump?
@justcalamari 
@scopatz 
@isuruf 

---

@scopatz commented on [Mon Feb 26 2018](https://github.com/regro/cf-graph/issues/32#issuecomment-368614899)

What are you asking, precisely?

---

@CJ-Wright commented on [Mon Feb 26 2018](https://github.com/regro/cf-graph/issues/32#issuecomment-368660189)

If we version bump a package, most likely the patch won't work. Should we delete the patch or should we just leave it there for the maintainers to deal with?

**Comment by CJ-Wright** [comment]
Currently we keep the patches and let the maintainers deal with it.

**Comment by CJ-Wright** [comment]
I'm not certain if this was the right decision

**Comment by beckermr** [comment]
I think we let the maintainers deal with it.

**Comment by CJ-Wright** [comment]
So this is where having all the logs in hand would be helpful, how many PRs flounder because of a bad patch?

**Comment by beckermr** [comment]
For sure many do, but patches are very special things. Even if a PR passed without the patches, it would take a human to determine if that patches are correct. OTOH if a PR passes with the patches, it takes a human to determine if things are still correct post a version bump. 

I don't think there is anything automated we can actually do.

Having a person have to deal with a failure is a *feature* here, not a bug.

**Comment by CJ-Wright** [comment]
Fair
