### ISSUE TITLE
[idea] Filtering out GitHub/npm prereleases

### ISSUE THREAD

**Issue by bollwyvl** [regro/cf-scripts#291]
Greetings :robot: overlords! Thanks for all the helpful release updates!

On https://github.com/conda-forge/yarn-feedstock, we're getting a lot of false positives from https://github.com/yarnpkg/yarn. I assume the root cause is that project doesn't use distinguishing features like `rc` in their prereleases tags, which i guess is common in npm land :man_shrugging: . I actually merged the bot's `1.8.0` PR, which was also a dev release, as I didn't think to check. I'd like to avoid that in the future. Nobody has complained yet, I guess, so I guess we don't need to take it down!

> Note: Dev issues aside, we're presently doing a rather non-standard thing in the feedstock, just copying in the release contents directly into `bin` and `lib`, which is actually kinda broken on older windows `conda`s, but that aside, it would be nice to do the right thing to get it sorted out properly.

So the question: is there a...
- URL scheme we could use that would already carry the metadata?
- way to specify our install that would trigger using npm (if this, then we'll just do it!)
- new work to try and track this down

Here are some leads i tracked down:
- github:
  - i assume github api calls are precious. the best summary of approaches i've seen is something [along these lines](https://gist.github.com/lukechilds/a83e1d7127b78fef38c2914c4ececc3c), including some HTTP options that tracks the `302` of `https://github.com/yarnpkg/yarn/releases/latest`
- libraries.io
  - `https://libraries.io/api/github/yarnpkg/yarn/projects` says the `latest_stable_release` is `1.9.2`, as does the atom feed. haven't PRd there, as they definitely do distinguish between stable and pre, but i had trouble getting the dev env up (not a ruby guy)
- npm
  - `http://registry.npmjs.org/yarn` reports `"dist-tags":{"latest":"1.7.0","rc":"1.9.2"}`
  - `http://registry.npmjs.org/yarn/latest`

Thoughts? Happy to follow up one of those leads, if they sound fruitful...

**Comment by isuruf** [comment]
I would suggest writing a `NPM` class and use the `http://registry.npmjs.org/yarn/latest` url.

See how it is done for PyPI.
https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py#L98

**Comment by bollwyvl** [comment]
I ended up using `dist-tags.latest` off the main (larger) API call, because the `/latest` route doesn't apparently work for `@namespace/package`, which seem to be fairly widely used.

**Comment by bollwyvl** [comment]
Hey sorry I didn't get back on this. Much appreciated!
