### ISSUE TITLE
Dependency checker far from correct, or at least not helpful.

### ISSUE THREAD

**Issue by evonreis** [regro/cf-scripts#2929]
In this comment https://github.com/conda-forge/cds-crtools-feedstock/pull/83#issue-2456948976, the dependency checker complains about a large number of dependencies, most of which are produced in the package itself.   

The handful of flagged external packages, root_base and nds2_client in particular, are dependencies of at least some of the packages produced by the feedstock.

The feedstock creates a large number of packages.  Perhaps the bot is complaining that some of them don't have these dependencies, but if so, that isn't mentioned anywhere in the comment.

**Comment by beckermr** [comment]
Yeah I agree in general here and am ready to remove this feature from the bot, or at least make it opt-in.

**Comment by ytausch** [comment]
Otherwise, there is already today the option to opt-out: https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot
