### ISSUE TITLE
Migrator gets stuck on (false positive) "Very odd pinning"

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#2938]
It's been happening for a little while that some feedstocks in a migration run into a bot error of the sort:
```
Error running check-solvable in container - error ValueError raised:
"Very odd pinning: pin_compatible('numpy')! Package numpy not found in host {}!"
```

There are IMO two problems with this that exacerbate each other:
* I've only ever seen false positives. E.g. currently `hpp-fcl` is stuck in the boost migration with the above error, despite [clearly](https://github.com/conda-forge/hpp-fcl-feedstock/blob/a92ad961ea7cec99df0292ba24608992e1d46b61/recipe/meta.yaml#L40) having numpy in host
* Nothing else warns about this problems (linter etc.), so that it could be addressed without holding up migrators.

These migrator PRs should not fail over a weird pinning, and certainly not over a false positive.

**Comment by beckermr** [comment]
Yes I've seen this too. Smells like a bug and having the example here will help track it down. Thanks for making the issue!

**Comment by beckermr** [comment]
I tracked this down to a bug in conda-forge-feedstock-check-solvable. This has been fixed and so this error will eventually change to the actual solver error going on.

**Comment by h-vetinari** [comment]
Thank you very much! 🙏

**Comment by h-vetinari** [comment]
This still seems to exist in some form... `biopython` just failed 2h ago in the 3.13 migration with:
```
bot error (
[bot CI job](https://github.com/regro/cf-scripts/actions/runs/10673334796)
): main:
Error running 'conda-forge-tick-container check-solvable --timeout 600 --verbosity 2 --log-level info --build-platform {"linux_aarch64": "linux_64", "linux_ppc64le": "linux_64", "osx_arm64": "osx_64"}' in container - error ValueError raised:
"Very odd pinning: pin_compatible('numpy')! Package numpy not found in host {'libgcc': ['14.1.0', 'h77fa898_1'], '_libgcc_mutex': ['0.1', 'conda_forge'], '_openmp_mutex': ['4.5', '2_gnu'], 'libgomp': ['14.1.0', 'h77fa898_1'], '__glibc': ['2.50', '0'], 'python': ['3.10.14', 'hd12c33a_0_cpython'], 'xz': ['5.2.6', 'h166bdaf_0'], 'readline': ['8.2', 'h8228510_1'], 'libuuid': ['2.38.1', 'h0b41bf4_0'], 'libnsl': ['2.0.1', 'hd590300_0'], 'libgcc-ng': ['14.1.0', 'h69a702a_1'], 'libxcrypt': ['4.4.36', 'hd590300_1'], 'libsqlite': ['3.46.0', 'hde9e2c9_0'], 'ncurses': ['6.5', 'he02047a_1'], 'tk': ['8.6.13', 'noxft_h4845f30_101'], 'libffi': ['3.4.2', 'h7f98852_5'], 'libzlib': ['1.3.1', 'h4ab18f5_1'], 'bzip2': ['1.0.8', 'h4bc722e_7'], 'openssl': ['3.3.1', 'hb9d3cd8_3'], 'ld_impl_linux-64': ['2.40', 'hf3520f5_7'], 'tzdata': ['2024a', 'h8827d51_1'], 'ca-certificates': ['2024.8.30', 'hbcca054_0'], 'pip': ['24.2', 'pyh8b19718_1'], 'wheel': ['0.44.0', 'pyhd8ed1ab_0'], 'setuptools': ['72.2.0', 'pyhd8ed1ab_0']}!"
```

In this case it's actually justified - `biopython` is [missing](https://github.com/conda-forge/biopython-feedstock/blob/67fc7d7ebab33cc12671b8b5e7950baa2bbf6258/recipe/meta.yaml#L19-L30) the numpy host dep - but IMO this still shouldn't fail the migrator? That would be much better as a lint on the PR IMO (though acknowledging that that may not be feasible technically).

**Comment by beckermr** [comment]
We can't run the solver checks if the host package is missing since we don't know what to pin to. I don't understand how to special case this while still failing on real solver errors. It seems to me that the package should be fixed properly.

**Comment by h-vetinari** [comment]
Why do we have to pin something? Can't we just pull in the last one like the actual build of such a recipe does? I agree that this needs to be fixed in the recipe, my question is rather if we want to fail the migrator on such things. Assuming it's rare enough, I don't mind if the migrator fails, though I still don't think that's the right place to enforce that (i.e. better to open the PR with a warning, or have the linter do it).

**Comment by beckermr** [comment]
conda-build does not pull in the latest to make a pin. It actually ignores the pinning statement all together. This is the list of deps from the latest build on linux for one of the pythons

```
libgcc-ng >=12, numpy, python >=3.12,<3.13.0a0, python_abi 3.12.* *_cp312
```

This is a bug in conda-build and should be fixed there. We cannot run solver checks on malformed recipes.

**Comment by beckermr** [comment]
I've change the behavior of our checks until this bug gets fixed. See https://github.com/regro/conda-forge-feedstock-check-solvable/pull/56

**Comment by beckermr** [comment]
closing again! reopen if you see more that are not eventually fixed. the bot will take a while to circle back to ones that have already errored.

**Comment by h-vetinari** [comment]
Thank you very much! 🙏
