### ISSUE TITLE
Missing build number bump when suggesting a pin change

### ISSUE THREAD

**Issue by sdvillal** [regro/cf-scripts#294]
Example:
https://github.com/conda-forge/x264-feedstock/pull/20

Compare to a better suggested change (meta.yaml is modified and build number is incremented):
https://github.com/conda-forge/imagemagick-feedstock/pull/26/files

**Comment by sdvillal** [comment]
Here the offending lines:

https://github.com/regro/cf-scripts/blob/78ed0d408c432dd02fb61599f0adc97446b20309/conda_forge_tick/migrators.xsh#L614-L615

I do not know well this codebase. Is there an easy way to change that conditional to detect that there have been changes in rerendering even if no change has been made to ```meta.yaml``` and therefore proceed with the bump?

**Comment by CJ-Wright** [comment]
I think this for fixed in a recent commit, hence why the newer PRs have gotten version bumps. If the code fails to find a pinning removed it won't issue the PR now.

**Comment by sdvillal** [comment]
Perfect, closing then.
