### ISSUE TITLE
Migrate to Jinja2 syntax PR - tests fail because cannot find shared library

### ISSUE THREAD

**Issue by mtazzari** [regro/cf-scripts#298]
Hi, I am working on the PR opened by the bot https://github.com/conda-forge/galario-feedstock/pull/1
but I cannot get the CI tests to pass.
The Python package (`galario`) is built correctly but the tests fail because a shared library that should be compiled during build time is not found by the `run_test.py` script.
See comment in the PR with more details.

**Comment by CJ-Wright** [comment]
I think this is an issue with the feedstock, not the bot.
