### ISSUE TITLE
copy graph to https://github.com/regro/cf-graph2

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#299]
That way we have the data in the git-lfs graph when we fall over. Also this would help with the 3GB download.

**Comment by CJ-Wright** [comment]
How big is the limit for git-lfs? (We are currently at ~65MB)

**Comment by scopatz** [comment]
You get 1 GB of *bandwidth* free a month. https://help.github.com/articles/about-storage-and-bandwidth-usage/

**Comment by scopatz** [comment]
Both uploads and downloads count against the bandwidth limit

**Comment by CJ-Wright** [comment]
Ouch.

**Comment by CJ-Wright** [comment]
I guess we could try to atomize the graph. This would make the graph thin, just names of nodes and edges. The attribute data could be stored in their own files. This hopefully would reduce our file size (although not the repo size). This could negatively impact speed though as we will need to load the graph (although maybe async/futures magic will help).

**Comment by scopatz** [comment]
Well, isn't the graph being stored in conda-forge.json? is this not git-friendly enough?

**Comment by CJ-Wright** [comment]
I think the `conda-forge.json` graph in libcfgraph is the package graph rather than the feedstock graph.

**Comment by CJ-Wright** [comment]
Should we use [gitlab](https://about.gitlab.com/2015/04/08/gitlab-dot-com-storage-limit-raised-to-10gb-per-repo/)?

**Comment by CJ-Wright** [comment]
I'm going to close this for now, since I think we're ok. We should really consider moving most of the data to `LazyJson` with `ujson`.
