### ISSUE TITLE
Handling GitLab URLs

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#301]
Not sure whether this already exists yet or not. So please excuse my bumbling around in case I'm clueless.

Would be great to support GitLab URLs for the release bot either from [GitLab.com]( https://about.gitlab.com/ ) or self-hosted GitLab instances.

**Comment by CJ-Wright** [comment]
Does gitlab have an API for their tags?

**Comment by isuruf** [comment]
RawURL should take care of most uses

**Comment by jakirkham** [comment]
Looks like [yes]( https://docs.gitlab.com/ee/api/tags.html ). Haven't used it though. What things do you need from the API?

**Comment by CJ-Wright** [comment]
@jakirkham do you know of a recipe which uses a gitlab upstream?

**Comment by jakirkham** [comment]
CMake uses it. There are the other issues where we have discussed GitLab on, but I don't recall them off the top of my head.

ref: https://github.com/conda-forge/cmake-feedstock/blob/73e76931283850ce8c5bbd8663b4e395f2134fe7/recipe/meta.yaml#L8

**Comment by CJ-Wright** [comment]
Ah ok. CMake has gotten bot PRs in the past https://github.com/conda-forge/cmake-feedstock/pull/61

**Comment by isuruf** [comment]
It doesn't work at https://github.com/conda-forge/sympow-feedstock/pull/7

Created an issue https://github.com/regro/cf-scripts/issues/322
