### ISSUE TITLE
some piggybacks deactivated?

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#3012]
Just saw a migrator PR that failed to add `{{ stdlib("c") }}` to a recipe that doesn't have it: https://github.com/conda-forge/singlejar-feedstock/pull/89

This shouldn't happen unless we turned off the piggyback. Wanted to check if that happened either intentionally or by accident.

**Comment by beckermr** [comment]
possibly by accident...

**Comment by h-vetinari** [comment]
Noticed that https://github.com/conda-forge/cymem-feedstock/pull/31 didn't apply the `PyPIOrgMigrator` for reasons I don't understand. The regex
https://github.com/regro/cf-scripts/blob/04e272d9955960e72b581ff0e533eac75614b9b2/conda_forge_tick/migrators/pypi_org.py#L7-L8
applies to cymem (so it shouldn't trigger `.filter()`), and the piggyback itself continues to be applied to all migrations, c.f.
https://github.com/regro/cf-scripts/blob/04e272d9955960e72b581ff0e533eac75614b9b2/conda_forge_tick/make_migrators.py#L295

**Comment by beckermr** [comment]
That list is for rebuild prs. If you read the code, you should find a block that has a list of minimigrators that get applied to version prs. You'll need to add the minimigrator there for it to be applied.

**Comment by h-vetinari** [comment]
> That list is for rebuild prs. If you read the code, you should find a block that has a list of minimigrators that get applied to version prs. You'll need to add the minimigrator there for it to be applied.

Thanks, I missed that when we did #3084... Here's a fix: #3193

**Comment by beckermr** [comment]
xref: #3225
