### ISSUE TITLE
flang migration not starting?

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#3021]
We've merged https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1359 more than 24h ago, but the migration has not shown up on the status page or in any of the bot runs that I checked (neither `bot-bot` or `bot-make-migrators`) - in contrast to other migrations that were merged later and have shown up already.

Not sure if the [migration file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/flang19.yml) contains some error? I guess we haven't tested the `platform_allowlist` bit (#1655) anywhere else before this migration, so that would be a possible culprit?

I also don't know how to correctly write a migrator for a compiler pin - all the other compiler bumps I've seen were ABI-compatible and thus could just be bumped directly..,

**Comment by h-vetinari** [comment]
CC @beckermr, not sure how to debug this; it doesn't show up in `bot-make-migrators`, so where would I need to check?

**Comment by beckermr** [comment]
It is the file extension of `.yml` versus `.yaml`. I wish nobody ever thought of one or the other. `conda-forge` uses both which is a disaster.

**Comment by beckermr** [comment]
See https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6542

**Comment by beckermr** [comment]
OK. It should show up in a few hours.

**Comment by h-vetinari** [comment]
Thank you very much! That's the kind of magic detail that's hard to see if one doesn't know where to look - and yes I agree, the `.yml` vs.  `.yaml`  things is a disaster. 🙈
