### ISSUE TITLE
PyYAML is missing from the PyPI mappings

### ISSUE THREAD

**Issue by maresb** [regro/cf-scripts#3031]
Open the [raw mappings](https://raw.githubusercontent.com/regro/cf-graph-countyfair/refs/heads/master/mappings/pypi/grayskull_pypi_mapping.yaml) and search for `pyyaml`. I noticed this in https://github.com/conda/grayskull/issues/564#issuecomment-2432827349. Checking [the recipe](https://github.com/conda-forge/pyyaml-feedstock/blob/main/recipe/meta.yaml) the source is indeed PyPI. I should be able to come up with more examples, but this seems to be the biggest. Any ideas @beckermr what might be causing these to go missing?

**Comment by beckermr** [comment]
No sorry. Will require some debugging.

**Comment by maresb** [comment]
Cool, thanks so much for tracking this down!!!

BTW I just noticed your conda-lock GHA action, that's really cool!!!
