### ISSUE TITLE
Not super clear what's going on if only main package is being updated.

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#31]
@pkgw commented on [Sat Feb 24 2018](https://github.com/regro/cf-graph/issues/29)

I just got [this PR](https://github.com/conda-forge/bibtexparser-feedstock/pull/1) from the bot. I was able to figure out the intent, but the initial message that it posted was not super clear to me, due to the empty table of "pending dependencies" (I'm not sure what "pending" means here). If I'm understanding the purpose of the bot properly, I think it would be helpful to have some text in the PR message along these lines:

> This PR updates $PACKAGE to the latest version on PyPI, $VERSION, from $OLD_VERSION. It also updates the following dependencies in the meta.yaml file: $BLAH ...

---

@CJ-Wright commented on [Sat Feb 24 2018](https://github.com/regro/cf-graph/issues/29#issuecomment-368237922)

Thank you for reporting!

The purpose of the bot is to tick versions, we currently don't have a way to update which dependencies are in the recipe.  The pending dependencies are stated dependencies which also need to be version bumped (since one may want to wait for the deps to be updated before updating the downstream packages).

The pending dependencies table is being removed in #25 (if there are no pending deps).

We can add something to the effect of your statement, although we support more than pypi.
eg

>This PR updates $PACKAGE to $VERSION from $OLD_VERSION.

**Comment by jakirkham** [comment]
Does PR ( https://github.com/regro/cf-scripts/pull/111 ) help make this clearer @pkgw?

**Comment by pkgw** [comment]
Yeah I think this is fine now.

**Comment by jakirkham** [comment]
If other things occur to you, please don't hesitate to share. :)
