### ISSUE TITLE
glibmm-feedstock not getting compiler or pinning migrations

### ISSUE THREAD

**Issue by scopatz** [regro/cf-scripts#314]
There are some parts of this recipe's meta.yaml that are a little weird, but nothing that should have prevented these migrations. See https://github.com/conda-forge/glibmm-feedstock/blob/master/recipe/meta.yaml

**Comment by isuruf** [comment]
There's no `toolchain` or `gcc` there.

**Comment by scopatz** [comment]
Fair :).  But there is `pkg-config`.  There should probably also be autotools and make.
