### ISSUE TITLE
No updates if archive format of the source package changes

### ISSUE THREAD

**Issue by pkgw** [regro/cf-scripts#317]
The [pytoml feedstock](https://github.com/conda-forge/pytoml-feedstock/blob/master/recipe/meta.yaml) is currently at version 0.1.15. [PyPI](https://pypi.org/project/pytoml/) is at version 0.1.18, and it has been for a while. As far as I can tell, this project should be getting automatic bump PRs, but it seems like it isn't. Any way to figure out why?

**Comment by isuruf** [comment]
They switched to a .tar.gz format for the archive

**Comment by CJ-Wright** [comment]
If there are two source URLs (not modified by a selector) do we use both or the first one that connects? If it is the first one to connect, then maybe we should use tar and zip for all PyPI sources so we are more resistant to these issues?

**Comment by pkgw** [comment]
Good catch @isuruf . @CJ-Wright I tend to think that it would be kind of ugly to have both for all PyPI feedstocks "just in case", but I certainly don't know the relevant issues.

**Comment by CJ-Wright** [comment]
If you don't mind I'm going to close this, since I think this issue is mostly with upstream moving rather than the bot.
