### ISSUE TITLE
BUG: astropy --> astropy-base migration stuck

### ISSUE THREAD

**Issue by bsipocz** [regro/cf-scripts#3272]
I was checking on the migration on the status page and was surprised that hardly any PRs were made during the long weekend. Looking at the logs, it seems that the migration is stuck with the same 3 recipes that are classified either as not solvable or bot error. In the next bot run, they are picked up first again, and then the allocated time runs out. 

Is there a way to introduce some random shuffling of which repo is picked up for migration? There are still 200 in the "awaiting for PR" category; it would be nice to shuffle through those before going back to the problematic ones.

**Comment by beckermr** [comment]
Ah yes. This is a bug I fixed elsewhere. Let me put in a pr today. Sorry for the trouble and thanks for looking into this!

**Comment by bsipocz** [comment]
If I can do anything to help do let me know. And I really have to say, the more I look under the hood the more I'm amazed by the machinery. Thank you!

**Comment by bsipocz** [comment]
Thanks for the very fast fix!
