### ISSUE TITLE
Spoof different OSs

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#33]
@CJ-Wright commented on [Fri Feb 23 2018](https://github.com/regro/cf-graph/issues/21)

We may need to spoof different OSs for reading the meta.yaml (for packages which have different urls/sha for different OSs)

eg
https://github.com/conda-forge/git-lfs-feedstock/pull/6/files

---

@CJ-Wright commented on [Thu Mar 01 2018](https://github.com/regro/cf-graph/issues/21#issuecomment-369639965)

Also https://github.com/conda-forge/git-feedstock/pull/33

---

@jakirkham commented on [Thu Mar 01 2018](https://github.com/regro/cf-graph/issues/21#issuecomment-369687309)

IDK if you are using `conda-build` 2 or 3. If 2, I can point you to some code in `conda-smithy`/`conda-build-all` for this. If 3, there is a feature in `conda-build` that you can use.

---

@CJ-Wright commented on [Thu Mar 01 2018](https://github.com/regro/cf-graph/issues/21#issuecomment-369695225)

Currently we are using 2, but I don't think there is any reason we can't use 3, so which ever will be easier to implement.

---

@jakirkham commented on [Thu Mar 01 2018](https://github.com/regro/cf-graph/issues/21#issuecomment-369701648)

Probably both are easy. Will leave it up to you.

We use a function called [`fudge_subdir`]( https://github.com/conda-forge/conda-smithy/blob/v2.4.5/conda_smithy/configure_feedstock.py#L209 ) to do this in `conda-smithy` (though it will be gone in `conda-smithy` 3). In `conda-build` 3, there is a function called [`render`]( https://github.com/conda/conda-build/blob/3.6.0/conda_build/api.py#L29-L30 ).

**Comment by CJ-Wright** [comment]
see: https://github.com/conda-forge/embree-feedstock/pull/4

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/otmorris-feedstock/pull/10

**Comment by CJ-Wright** [comment]
I would also merge an intermediate version which just doesn't run PRs on things with multiple sources.

**Comment by jakirkham** [comment]
Since we are on `conda-build` 3 would just use [`render`]( https://github.com/conda/conda-build/blob/3.10.5/conda_build/api.py#L29-L30 ) to do this.

**Comment by justcalamari** [comment]
I'm not sure if `render` is the right way to go because we would need to render the meta for every platform, but we really just need to find the all the url lines and update the corresponding sha. I think we can just do a single Jinja render and leave in the selectors, then we can match urls and shas using regex to update correctly. This may take a bit more work than just using conda-build 3's render, but it should be more efficient.

**Comment by CJ-Wright** [comment]
I think this has been addressed by #177
