### ISSUE TITLE
bumping build number to 1000 ?

### ISSUE THREAD

**Issue by rvalieris** [regro/cf-scripts#333]
hello,

I received [this PR](https://github.com/conda-forge/datamash-feedstock/pull/3), and I noticed it bumped the build number from 1 to 1001, is this intentional ? if so why ?

**Comment by CJ-Wright** [comment]
Yes, the idea is that when we merge the gcc7 and main channels the gcc7 will take precedence.

**Comment by rvalieris** [comment]
oh I see, thanks. can you point me to where I can read more about this gcc7 rebuild ?

**Comment by CJ-Wright** [comment]
there is some information here: https://github.com/conda-forge/conda-forge-enhancement-proposals/pull/10

**Comment by rvalieris** [comment]
awesome, thanks.

**Comment by jdblischak** [comment]
@CJ-Wright Is the high build number only temporary? In other words, the next time it comes to bump the version, should the build number return to 0?

**Comment by CJ-Wright** [comment]
No it should stay at 1000 until the labels are merged.

**Comment by jdblischak** [comment]
@CJ-Wright Bumping to 1000 appears to have broken things. It's an R recipe, so I'm guessing that instead it should be bumped to 1001, as described in #378, to make sure openblas is installed correctly. Could you please confirm?

**Comment by CJ-Wright** [comment]
You can bump to 1001 if you want. I think the rational for not doing that was everything on gcc7 would be with the new openblas, then when we moved things over then the gcc7 packages would take precedence. @mariusvniekerk

**Comment by jdblischak** [comment]
We're getting the following [error on Travis](https://travis-ci.org/conda-forge/r-dplyr-feedstock/jobs/464357045#L526) for PR https://github.com/conda-forge/r-dplyr-feedstock/pull/10 when the build number is 1000 (the build passed when the build number was 0):

```
export SRC_DIR=/Users/travis/miniconda3/conda-bld/r-dplyr_1544107050667/work
dyld: Library not loaded: @rpath/libopenblas.dylib
  Referenced from: /Users/travis/miniconda3/conda-bld/r-dplyr_1544107050667/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/bin/exec/R
  Reason: image not found
/Users/travis/miniconda3/conda-bld/r-dplyr_1544107050667/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/R/bin/INSTALL: line 34:  3666 Done                    echo 'tools:::.install_packages()'
      3667 Trace/BPT trap: 5       | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Traceback (most recent call last):
  File "/Users/travis/miniconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 456, in main
    execute(sys.argv[1:])
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 447, in execute
    verify=args.verify, variants=args.variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/api.py", line 208, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 2311, in build_tree
    notest=notest,
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/build.py", line 1477, in build
    cwd=src_dir, stats=build_stats)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 374, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/Users/travis/miniconda3/lib/python3.6/site-packages/conda_build/utils.py", line 354, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda3/conda-bld/r-dplyr_1544107050667/work/conda_build.sh']' returned non-zero exit status 133.
The command "conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml" exited with 1.
```

**Comment by jdblischak** [comment]
Quick update. For another R recipe, the build fails on Travis because of the same openblas error, but this time it fails whether the build number is 0 or 1001: https://github.com/conda-forge/r-bfa-feedstock/pull/1

**Comment by jdblischak** [comment]
FYI the Travis failures were unrelated to the build number. It was due to an openblas issue with r-base that was resolved in https://github.com/conda-forge/r-base-feedstock/pull/63
