### ISSUE TITLE
CFEP-25 `noarch: python` syntax migrator opened for already migrated feedstock

### ISSUE THREAD

**Issue by jdblischak** [regro/cf-scripts#3415]
I am a big fan of the new `noarch: python` syntax specified in CFEP-25 because I have sent too many repodata patches to fix the minimal required python versions. Thus I have already started migrating feedstocks that I maintain.

Is there any way to prevent the bot from opening PRs on feedstocks I have already migrated? For example, this PR https://github.com/conda-forge/anndata-feedstock/pull/48 only bumped the build number, but I assume because rerendering had an effect, the PR was still opened.

**Comment by beckermr** [comment]
Yep I can try to include a skip in another spot.
