### ISSUE TITLE
Merge with `master` before updating

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#359]
Would be very useful if the migrators merged with `master` on the feedstock before updating PRs. This should avoid accidentally introducing merge conflicts when updating a PR for example. Though we should also think about how we want to handle merge conflicts. One option might be to prefer `master` changes in all cases and then reapply any migration changes after the merge. Another might be to close and replace with a new PR. There might be other options worth discussing too.

**Comment by CJ-Wright** [comment]
I think the current workflow for this is to put in the `bot-rerun` label and have the bot try again from scratch. This way we can make sure that master's changes are preferred and is more likely to give an easier merge.

**Comment by CJ-Wright** [comment]
@jakirkham does the new label driven workflow close this?
