### ISSUE TITLE
Use build number 1000 in update PRs

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#360]
When new and old compilers are in use, would be good to reset the build number to 1000 in update PRs. Expect the average maintainer may miss this detail. So would be good if we do it for them.

ref: https://github.com/conda-forge/oniguruma-feedstock/pull/23#pullrequestreview-151891610

**Comment by mariusvniekerk** [comment]
This has now been addressed.

**Comment by jakirkham** [comment]
Thanks @mariusvniekerk. FTR which PRs resolved this?
