### ISSUE TITLE
Check all versions of a dependency are satisfied before updating

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#367]
Currently AIUI dependency means simply the package. In the rebuild context, if all dependencies of a package get rebuilt, then that package is eligible for a rebuild. Though this also applies in the context of version updates. Similarly this may come up in other migration efforts pursued.

At a first approximation, this is fine. However there are a couple scenarios where this runs into issues.

1. Multiple versions of a dependency (e.g. `python`) are needed.
2. A specific older version of a dependency is needed (e.g. pinned in `host` or globally).

In these scenarios, as the versions of the dependency are not checked against the package being updated (please correct me if I'm wrong) we end up with PRs that are not viable because some versions are missing. This can result in PRs getting merged that have unintended consequences or PRs that fail outright. Not sure the right solution to this problem, but would like to raise it for discussion.

**Comment by scopatz** [comment]
In these cases we are going to have to do things manually for the moment.  

@mariusvniekerk has a method using soft resets that we could use (in conjunction with some special meta.yaml extras data) to increase the build matrix for specific repos that need to have multiple versions built.

**Comment by beckermr** [comment]
Is this issue related to the cases where update PRs are issued for a feedstock, but versions of packages like openmpi or hdf5 are missing?

**Comment by beckermr** [comment]
See the current gfortran migration for examples.

**Comment by CJ-Wright** [comment]
I think for explicitly pinned packages (see the boto ecosystem, or KDE) we can check that the packages exist via the conda command line. Although this might only be approx. since we need to handle the build matrix. For that we may need a store that know what packages *should* be available and compare that against what packages *are* available on the CDN.

**Comment by CJ-Wright** [comment]
Potential path forward
1. When it looks like a PR could be issued (eg all dep PRs have been merged) render the feedstock to produce the full build matrix.
2. Attempt to solve for each one's environment (maybe using `mamba` for speed) if all the entries in the matrix can be solved for issue PR.

@msarahan @forrestwaters I know we discussed this before, what is the exact setup for step 1? Also is there a command for step 2 or do we need to build something for that?

**Comment by CJ-Wright** [comment]
I think the path above could work, mostly we need to extract all the deps from the output of `render` and put them together in a file that can be fed to `conda/mamba create -n tmp --file file`. Then all this can go into the `filter` methods for the migrators.

How `conda render` picks the extra pins/packages it puts into the requirements?

**Comment by CJ-Wright** [comment]
This is provisionally handled, if you add
```yaml
bot:
  check_solvable: True
```
to the `conda-forge.yml` file then the bot will check that the recipe with the new version can be solved. This is still in beta.

**Comment by CJ-Wright** [comment]
mamba now handles this and `check_solvable` is out of beta!
