### ISSUE TITLE
Not processing bump for some feedstock

### ISSUE THREAD

**Issue by prusse-martin** [regro/cf-scripts#368]
A few days ago (2018-09-20) I updated the release version of two projects I am working and just one of the repos got it's feedstock's version updated.

I failed to locate the bot's CI history soo I could check for error messages.
Both are listed at names.txt:
- [conda-devenv](https://github.com/regro/cf-graph3/blob/master/names.txt#L1926);
- [deps](https://github.com/regro/cf-graph3/blob/master/names.txt#L5121);

But only [deps got a PR](https://github.com/conda-forge/deps-feedstock/pull/1) updating the version. After a quick look "[conda-devenv's meta.yaml](https://github.com/conda-forge/conda-devenv-feedstock/blob/master/recipe/meta.yaml)" and "[deps' meta.yaml](https://github.com/conda-forge/deps-feedstock/blob/master/recipe/meta.yaml)" I can't locate some drastic difference.

**Comment by prusse-martin** [comment]
@nicoddemus

**Comment by scopatz** [comment]
@prusse-martin - [you shouldn't use the git sources](https://conda-forge.org/docs/meta.html#build-from-tarballs-not-repos). [conda-devenv's meta.yaml uses this](https://github.com/conda-forge/conda-devenv-feedstock/blob/master/recipe/meta.yaml#L8). So I don't think that the bot does, should, or will support bumping version numbers from repo sources.

**Comment by nicoddemus** [comment]
@scopatz thanks, that makes sense. In our case we need to use the git sources because we use `setuptools_scm` for versioning, which needs version meta-data to work.

**Comment by scopatz** [comment]
Do you push to PyPI?  It might be worth pulling down from pypi instead

**Comment by nicoddemus** [comment]
Currently we don't because it doesn't make much sense to publish to PyPI because it needs to be installed via conda into the root environment (like `conda-build` for example).

**Comment by scopatz** [comment]
Ahh makes sense

**Comment by nicoddemus** [comment]
OK, thanks for the clarifications @scopatz!

**Comment by prusse-martin** [comment]
Thank you for the explanation =)
