### ISSUE TITLE
Migration PR when compilers not used?

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#369]
PR ( https://github.com/conda-forge/automake-feedstock/pull/16 ) attempts to migrate `automake` to the new compilers even though it doesn't use them. Have gone ahead and merged it in case it is blocking things. That said, I'm not totally sure it is needed. Though I'm probably missing something. Feedback from the migration team would be helpful here.

**Comment by scopatz** [comment]
I think this was needed to get the rerender and the new `gcc7` label.  Note that this is not needed for `noarch` packages, which have already had the new label applied.

**Comment by jakirkham** [comment]
Hmm...it does not seem to upload under the `gcc7`. 😕

**Comment by scopatz** [comment]
We can always label it manually. CC @mariusvniekerk

**Comment by jakirkham** [comment]
That probably works in this case as I don't think the package will change much.
