### ISSUE TITLE
Add defaults into graph

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#37]
@CJ-Wright commented on [Thu Feb 15 2018](https://github.com/regro/cf-graph/issues/9)

We can't tick the versions, but we could track the package name/version via calls to their gh page, I think.

**Comment by jakirkham** [comment]
How would you distinguish between our two graphs? Certainly there are name overlaps, which could be easy.

However there are some cases like the naming around Boost packages where we appear to have diverged. This already has caused some annoying problems, which are tricky to deal with when building packages. Not sure how they would impact the graph offhand, but it is worth giving some thought too.

**Comment by CJ-Wright** [comment]
Append something to the name? :man_shrugging: 

It would be good to have some mapping in the names somewhere.

**Comment by jakirkham** [comment]
Has this been solved somewhere?

**Comment by CJ-Wright** [comment]
I was thinking that this was more of a `wontfix`. I don't know if this is very doable, especially due to overlaps. I can re-open if you want.
