### ISSUE TITLE
Some recipes failed when trying to update-cb3

### ISSUE THREAD

**Issue by ocefpaf** [regro/cf-scripts#373]
Recipes that have this kind of jinja format never got update-cb3 updates:

https://github.com/conda-forge/pylama-feedstock/blob/b35de80e4531bb7bc84dc23ed01e6201de4c987e/recipe/meta.yaml

that is not a big deal in some cases. However, if we ever hit a block on downstream packages b/c of a recipe like that we need to fix them manually.

PS: @mariusvniekerk believe that ` {% set build = 0 %} ` is the culprit there.

**Comment by CJ-Wright** [comment]
I'm going to close this since this is mostly complete.
