### ISSUE TITLE
Distinguish build from host

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#381]
While it is true both `build` and `host` are needed to build a package, they serve different purposes. The `build` dependencies are CLI tools that are needed to perform the build, but they are not linked to or otherwise tied to the package later (with the exception of compiler runtime libraries). These `build` dependencies are not really dependencies needed for a compiler rebuild per se. OTOH `host` is linked to by a package and really needed first as part of a compiler rebuild before handling a package itself.

Case and point `cmake` really should not be a blocker for rebuilding anything as it should always be a `build` dependency (there may be a rare exception).

<img width="1552" alt="screen shot 2018-10-16 at 12 44 41" src="https://user-images.githubusercontent.com/3019665/47032813-45dd2380-d141-11e8-9d87-2bb1f95ef9a4.png">

**Comment by isuruf** [comment]
I think the issue is that these recipes haven't been updated to cb3 splitting of build and host.

**Comment by CJ-Wright** [comment]
I think this has been taken care of.
