### ISSUE TITLE
Support CRAN packages

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#39]
@CJ-Wright commented on [Wed Feb 14 2018](https://github.com/regro/cf-graph/issues/7)

**Comment by jakirkham** [comment]
@bgruening @jdblischak, might find this interesting. ;)

Basically this would be for helping to automate updates across the R stack. Though @CJ-Wright can provide more detail about what sort of things would need to be done on the bot end. Would be useful to know if there are any tricks of the trade that could be used by the bot to make this work smoothly and help you with your work.

**Comment by bgruening** [comment]
@CJ-Wright cool. Let us know what you need and how we can help. Have a look at https://github.com/bgruening/conda_r_skeleton_helper. This is what we use to automatically generate recipes, which work in 99% I would say.

**Comment by CJ-Wright** [comment]
What is the best way to find out if a new version is on CRAN?

My understanding of what needs to happen is:
1. A CRAN statement needs to be added to https://github.com/regro/cf-scripts/blob/master/02-graph_upstream.py#L10
1. We need a CRAN version of https://github.com/regro/cf-scripts/blob/master/02-graph_upstream.py#L28 to pull the upstream version from CRAN.
1. A CRAN entry needs to be added here https://github.com/regro/cf-scripts/blob/master/02-graph_upstream.py#L62

**Comment by jdblischak** [comment]
@CJ-Wright You can get the version from the DESCRIPTION file for a given package, e.g.:

https://cran.r-project.org/web/packages/ggplot2/DESCRIPTION

It's in Debian Control Format: https://cran.r-project.org/doc/manuals/r-release/R-exts.html#The-DESCRIPTION-file

See here for how `conda-build` downloads and parses this file: https://github.com/conda/conda-build/blob/53aaa0ff24de55d8b44aa9a8a366a549ce0a4636/conda_build/skeletons/cran.py#L483

**Comment by CJ-Wright** [comment]
I think this is mostly finished. We still have a few hicups left, mostly due to inconsistencies between r versions and pep440, which will be fixed in the near future by moving to `conda`'s version parser, see #123 if I'm missing something, feel free to reopen/comment.
