### ISSUE TITLE
Requests is not available.

### ISSUE THREAD

**Issue by henrykironde** [regro/cf-scripts#391]
The test seem to fail due to the package `requests` not available
https://circleci.com/gh/conda-forge/retriever-feedstock/19?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by dougalsutherland** [comment]
This looks like a problem with the `retriever` package, not with the bot. You should add `requests` to the `requirements/run` section.

**Comment by henrykironde** [comment]
@dougalsutherland, thanks I will add the rest.
