### ISSUE TITLE
Bot rerun not happening for pyutilib-feedstock

### ISSUE THREAD

**Issue by xhochy** [regro/cf-scripts#405]
The label `bot-rerun` has been applied a day ago to https://github.com/conda-forge/pyutilib-feedstock/pull/15#event-1977889812 but has still not happened. Normally this took less than an hour to happen.

**Comment by CJ-Wright** [comment]
The bot has been down for 10 hours running due to a bad meta.yaml. It should be up soon.

**Comment by whart222** [comment]
Any update on this?  Is the bot still down?

**Comment by CJ-Wright** [comment]
The bot's back up. However the `bot-rerun` label doesn't work after the PR has been closed.

**Comment by whart222** [comment]
But this PR has been re-opened.

**Comment by CJ-Wright** [comment]
Right, but it was closed which is the important part. To save space and time the bot doesn't keep track of PRs once they have been closed, so it has no way to know that the label was added (or that it was reopened).

**Comment by whart222** [comment]
So ... how do we re-apply the bot to this feedstock?

**Comment by CJ-Wright** [comment]
You could rebase the bot's changes onto master. All the important changes the bot made are in the first commit.

**Comment by CJ-Wright** [comment]
You could also take a poke at https://github.com/regro/cf-scripts/issues/407 if you wanted to work on a long term solution.

**Comment by CJ-Wright** [comment]
This commit is the only thing that the bot is giving in terms of value: https://github.com/conda-forge/pyutilib-feedstock/pull/15/commits/13131af084ac4e4f9fb40d49ff9515c2bb57b0cf

**Comment by CJ-Wright** [comment]
Can I close this issue?

**Comment by xhochy** [comment]
Yes, mystery has been solved.
