### ISSUE TITLE
Bot not able to rerender on my branches

### ISSUE THREAD

**Issue by xhochy** [regro/cf-scripts#406]
In the last 2-3 days I quite often see that the bot cannot push to my branch although the "Allow edits from maintainers" box is ticked, e.g. https://github.com/conda-forge/py_stringmatching-feedstock/pull/4

The special things about these branches are that possibly most of them were created through the GitHub web UI and most of them were on nearly unmaintened feedstocks (the latter is not always true). 

```
Hi! This is the friendly automated conda-forge-webservice.

I tried to patch-1 for you, but it looks like I wasn't able to push to the xhochy branch of py_stringmatching-feedstock/re-render. Did you check the "Allow edits from maintainers" box?
```

**Comment by xhochy** [comment]
Also these branches are started by forking from  the`regro-cf-autotick-bot` repo, not from the `conda-forge` one.

**Comment by CJ-Wright** [comment]
Is this an issue with the webservice bot? If so the repo for that is: https://github.com/conda-forge/conda-forge-webservices

**Comment by beckermr** [comment]
The webservice bot won't rerender outside of conda-forge for good reasons. I am closing this @xhochy. If you have more trouble or want to reopen, feel free to do so!
