### ISSUE TITLE
Move node attributes to json

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#407]
It would be nice to move all the node's attributes to `LazyJSON`. This would help with a bunch of things:
1. It would make the pickle of the graph (and the entire repo) much smaller
2. It would make the node attributes actually git trackable
3. It would make the node attributes changeable/PRable by people other than the core bot team (since the attributes wouldn't be steamrolled every time the bot runs)

The main difficulty of this is that we couldn't store the `PRed_json` values as pure `LazyJSON` themselves,  we would need some sort of loading protocol which would rehydrate the json from the filepath.

Context:
Currently the entire graph is stored in a pickle file using networkx. We wrote a lazy json class for the PR json information so that we didn't store that in the pickle. This class allows us to store the filepath to the json and have it load when we ask for the data (and rewrite the json file when we update it).

**Comment by mariusvniekerk** [comment]
So the easy approach would be to have a special json decoder/encoder. 

We can represent lazy json as 
{_type: Lazyjson, value: somefilename}

**Comment by CJ-Wright** [comment]
Note that this needs some special structure for the frozendicts as keys.
We can replace the dicts with frozendict keys with a list where each element is a dict eg
`{fz1: value1, fz2: value2}` -> `[{__frozendict_key__: dict(fz1), __frozendict_value__: value1}, {__frozendict_key__: dict(fz2), __frozendict_value__: value2}]`

This transformation needs to go into a custom dump/load for json.

**Comment by CJ-Wright** [comment]
Done
