### ISSUE TITLE
Rebuild with openssl 1.1.1

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#409]
Would be useful to have some migration help with rebuilding the stack using the latest `openssl` once we are ready.

From the OpenSSL team...

> The latest stable version is the 1.1.1 series. This is also our Long Term Support (LTS) version, supported until 11th September 2023. Our previous LTS version (1.0.2 series) will continue to be supported until 31st December 2019 (security fixes only during the last year of support).

ref: https://www.openssl.org/source/

**Comment by CJ-Wright** [comment]
Do you know when the new openssl will be pinned?

**Comment by jakirkham** [comment]
That is up for discussion I think.

We haven't built the new `openssl` yet, but `defaults` has as of 6 days ago.

**Comment by CJ-Wright** [comment]
Ah ok.

**Comment by CJ-Wright** [comment]
By my count that is 51 feedstocks

```python
['curl',
 'cyrus-sasl',
 'erlang',
 'ffmpeg',
 'freetds',
 'git',
 'go',
 'lftp',
 'libarchive',
 'libevent',
 'librdkafka',
 'libssh2',
 'lighttpd',
 'lynx',
 'm2crypto',
 'mosh',
 'mysql',
 'nginx',
 'octave',
 'opencv',
 'pari',
 'postgresql',
 'psycopg2',
 'pylibscrypt',
 'python',
 'qt',
 'r-git2r',
 'r-openssl',
 'ruby',
 'salt',
 'scrypt',
 'socat',
 'tectonic',
 'uwsgi',
 'w3m',
 'whitebox_tools',
 'postgres-xl',
 'thrift-cpp',
 'libgit2',
 'cryptography',
 'aws-sdk-cpp',
 'pypy3.5',
 'libpq',
 'sstp-client',
 'krb5',
 'r-base',
 'grpcio',
 'ldas-tools-al',
 'ldas-tools-framecpp',
 'gdal',
 'r-pki']
```

**Comment by jakirkham** [comment]
Should add I'm not sure if the `openssl` upgrade will result in different ABIs being exposed by downstream libraries like `curl` or `libssh2`. We should probably investigate this unless someone else already has.

**Comment by CJ-Wright** [comment]
Yeah. If we need to rebuild all descendants rather than just successors we are looking at a 3.5k package scope.

**Comment by msarahan** [comment]
We've been fine with rebuilding only direct descendants.  If anything breaks, it'll probably because a package needed an explicit openssl dependency (it was picking it up via transitive dependency).  Conda-build's "overlinking" detection is designed to catch this situation.  We use the ``--error-overlinking`` flag to treat any such warnings as errors on our build system.

**Comment by CJ-Wright** [comment]
Attn: @soapy1

**Comment by soapy1** [comment]
I started on an attempt to write a migrator for this https://github.com/regro/cf-scripts/pull/454.
Tests seems to pass when I run them locally but I'm not sure if there is a more thorough way to test this?

**Comment by CJ-Wright** [comment]
This is in flight now!
