### ISSUE TITLE
Make library

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#41]
@CJ-Wright commented on [Fri Mar 02 2018](https://github.com/regro/cf-auto-tick/issues/3)

@CJ-Wright commented on [Wed Feb 14 2018](https://github.com/regro/cf-graph/issues/6)

(there are some common funcs and such)

**Comment by CJ-Wright** [comment]
Still need `03-....xsh` moved in.

**Comment by justcalamari** [comment]
Solved by #186
