### ISSUE TITLE
Fix R licences

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#414]
A lot of good work for R licenses has gone in recently, but I'm afraid that we have already rebuilt a lot of R packages. Do we need to go back and fix licenses on thins which have already been rebuilt?
Attn: @jdblischak

**Comment by jdblischak** [comment]
> Do we need to go back and fix licenses on thins which have already been rebuilt?

I think it is a matter of resources. Do we have the CI time (and GitHub API requests) to make a pass through all the R packages to update broken licenses?

A slower option would be to enable to bot to update the license if necessary whenever it ticks the version number.

**Comment by CJ-Wright** [comment]
Hmm fair point. I like the version bump approach. I've been meaning to implement parasitic migrations which could piggy back on the version bumps.

**Comment by jdblischak** [comment]
@CJ-Wright Agreed. And "parasitic migrations" is a great name for the approach! :-)

And on the topic of R licenses, would you be able to review and merge #413?

**Comment by jdblischak** [comment]
> Composite migration?

I prefer "parasitic migration". It's more vivid. But really you can refer to it however you like. I don't have a strong opinion.

**Comment by jdblischak** [comment]
Also, this is related to Issue #51 about missing licenses.

**Comment by CJ-Wright** [comment]
I think this is mostly fixed
