### ISSUE TITLE
Rebuild libtiff stack

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#416]
Recently the Windows library names in `libtiff` changed to match its typical name and how it was named in `defaults`. This will cause a lot of breakage for downstream packages. It would be very helpful to trigger rebuilds for all these packages in topological order.

xref: https://github.com/conda-forge/libtiff-feedstock/issues/35

**Comment by CJ-Wright** [comment]
What is the status on this?

**Comment by jakirkham** [comment]
I think we can close.

We fixed the package to ship libraries under the legacy and new name. ( https://github.com/conda-forge/libtiff-feedstock/pull/36 ) So the breakage is fixed.

**Comment by CJ-Wright** [comment]
Great!
