### ISSUE TITLE
Auto-tick PR stopped working for tbb-feedstock

### ISSUE THREAD

**Issue by anton-malakhov** [regro/cf-scripts#418]
PR is not created automatically for https://github.com/01org/tbb/tree/2019_U3
Re-opened https://github.com/conda-forge/tbb-feedstock/issues/29

Thanks!

**Comment by CJ-Wright** [comment]
The error seems to be here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.xsh#L312

**Comment by CJ-Wright** [comment]
The problem is that tbb is in a cycle all of its own. So the cyclic topo sort balks.

**Comment by CJ-Wright** [comment]
This is happening now because only recently did we include sub-package deps in the graph so that the package and sub-packages can be rebuilt in one shot.

**Comment by CJ-Wright** [comment]
Yes. Some sub-packages depend on more than the main package. If we sent a rebuild to the feedstock when not all the sub-package dependencies were rebuilt the PR would have no hope of success.
