### ISSUE TITLE
weird PR issued for python-blosc rebuild

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#420]
It appears the bot would not properly update the python-blosc feedstock with the proper rebuild PR. 

The first [attempt](https://github.com/conda-forge/python-blosc-feedstock/commit/d8284a1807519901c9b78b2e7eb425e2ce86214b) didn't have any of the anaconda compilers or python 3.7.

I then asked the bot to [rerender](https://github.com/conda-forge/python-blosc-feedstock/commit/1aa00f466c7c03772ff98f825892353fdc42651c), which did not help and instead made a very strange change to the meta.yaml, putting compilers in the host section.

Finally, I pulled conda-smithy by hand and rerendered locally. This did the [trick](https://github.com/conda-forge/python-blosc-feedstock/commit/b68769d19f3e626637c50d8b4cf65a398d504e24).

**Comment by kmuehlbauer** [comment]
Similar here https://github.com/conda-forge/python-eccodes-feedstock/pull/41.

Tried to let the bot rerender to no avail. Rerendering locally worked, but displayed [error message](https://github.com/conda-forge/python-eccodes-feedstock/pull/41#issuecomment-444518564). The rerendering was technically successful since it created the needed files.

**Comment by CJ-Wright** [comment]
I think this might have just been patched in https://github.com/conda-forge/conda-smithy/pull/962/files
Maybe it's time to put out a smithy release?

**Comment by kmuehlbauer** [comment]
@CJ-Wright Any idea, why the bot did not rerender? I my case I just removed the `skip [py3k]`.

**Comment by jakirkham** [comment]
The re-rendering bot was rebuilt with `conda-build` 3.17.0 recently it appears. As it sounds like there have been some issues with that release, could that be part of the problem?

**Comment by jakirkham** [comment]
We just pinned the re-rendering bot to `conda-build` 3.16 in PR ( https://github.com/conda-forge/conda-forge-webservices/pull/247 ). There may be other issue here still (not sure personally), but trying the bot again would be a good first step. Please let us know how it goes.

**Comment by jakirkham** [comment]
That said, we should perform the same pinning here as well. Currently the bot is producing migration PRs that don't include a re-rendering and people need to add them manually. For example...

ref: https://github.com/conda-forge/mtspec-feedstock/pull/7
ref: https://github.com/conda-forge/hyperion-fortran-feedstock/pull/11

**Comment by beckermr** [comment]
Yep. I noticed the lack of rerendering in a new feedstock that just was added. :(

**Comment by beckermr** [comment]
Well I tried again [here](https://github.com/conda-forge/pypolyagamma-feedstock/pull/6) and it didn't seem to work.

**Comment by beckermr** [comment]
LOL. Now I cannot get the right rerendered feedstock locally, but the bot is doing great.

**Comment by jakirkham** [comment]
It's probably the same issue. Downgrading to conda-build 3.16 locally should address the issue. This will be fixed in the next conda-smithy release.

**Comment by beckermr** [comment]
Interestingly, I am using conda-build 3.16.3.

**Comment by jakirkham** [comment]
Maybe it's a different issue. Could you please raise an issue over at conda-smithy with an MRE?

**Comment by beckermr** [comment]
i'll try! I have this weird feeling that conda-smithy depends on the state of the local machine in ways I don't fully understand or can reproduce so I may not be able to come up with an MRE.

**Comment by jakirkham** [comment]
If it is, then there may be more things worth raising as issues over at conda-smithy. Ideally we'd like conda-smithy not to be dependent on the end-user's machine's state to avoid exactly these sorts of issues. Unfortunately those errors end up being much harder to debug and address.

**Comment by beckermr** [comment]
Done. https://github.com/conda-forge/conda-smithy/issues/964

**Comment by jakirkham** [comment]
I think this was resolved by the recent conda-smithy release. So should be good to close.
