### ISSUE TITLE
Removing archived repos from migration

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#422]
Would be good if there was a way to remove archived repos from migration. For instance, [this repo]( https://github.com/conda-forge/f90wrap-feedstock ) is still being listed as needing migration on the status page, but it is archived.

**Comment by CJ-Wright** [comment]
I think this is fixed now

**Comment by CJ-Wright** [comment]
https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.xsh#L358
