### ISSUE TITLE
Migrating python.app

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#423]
The [`python.app`]( https://github.com/conda-forge/python.app-feedstock ) package contains a shim script used to run GUI applications using Python on macOS. It appears it needs migrating according to the status page and is blocking a few things. There appears to be no PRs open for it currently and Python 3.7 was already added with PR ( https://github.com/conda-forge/python.app-feedstock/pull/1 ). What's the best way to address it?

**Comment by isuruf** [comment]
Add gcc7 label to the main channel packages.

**Comment by CJ-Wright** [comment]
The bot doesn't know this has been fixed yet. This is actually an issue with how we track "bad" recipes.

**Comment by jakirkham** [comment]
Ah ok. That makes sense of why it was missed. Thanks @CJ-Wright :)
