### ISSUE TITLE
Bot missed re-running PR

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#424]
Looks like PR ( https://github.com/conda-forge/pyutilib-feedstock/pull/15 ) was never re-run despite the label. Appears confusion about this led to the PR being closed, which has complicated matters further unfortunately.

**Comment by CJ-Wright** [comment]
If the PR is closed the bot doesn't keep track of it anymore so the label won't be recognized.

**Comment by CJ-Wright** [comment]
This is a duplicate of #405 I think
