### ISSUE TITLE
Duplicate noarch added

### ISSUE THREAD

**Issue by jdblischak** [regro/cf-scripts#425]
The feedstock for [r-esabcv](https://github.com/conda-forge/r-esabcv-feedstock) was created a few hours ago. It was built as a noarch recipe. The bot sent a PR that added a second [duplicate noarch field](https://github.com/conda-forge/r-esabcv-feedstock/pull/1/files#diff-e178b687b10a71a3348107ae3154e44cR16). Would it be possible for the bot to first check before adding a second noarch field?

Also, I noticed that `build.sh` was edited because it was a noarch recipe. The recipe was built with `conda skeleton cran --use-noarch-generic`. Do we need to send a PR upstream to change the behavior of `conda-build` for noarch support?

**Comment by CJ-Wright** [comment]
Maybe we should separate the r noarch migrator out. I think the issue is that we check for python noarch but not r in the add rebuild graph spec

**Comment by CJ-Wright** [comment]
I think we've stopped the noarch migrations so I'm going to close. Please reopen if you still think this need work.
