### ISSUE TITLE
Bot rebuild bumps build number but forgets to rerender

### ISSUE THREAD

**Issue by dbast** [regro/cf-scripts#427]
This happens as part of the rebuilds "Rebuild for Python 3.7, GCC 7, R 3.5.1, openBLAS 0.3.2"

See https://github.com/conda-forge/r-etm-feedstock/pull/1 ... first step is done, rerender did not happen. Also the appveyor files were not updated by a manual `rerender` request ...

Is the rerender just not happening or is it failing? 

Is it possible to somewhere see the log output of the bot run in that PR?

Thanks

**Comment by CJ-Wright** [comment]
The logs are here: https://circleci.com/gh/regro/circle_worker
You might need to cross reference the run times with when the PR was issued to find the right logs.
Usually when the PR is made without the rerender the rerender failed.
If the manual rerender did not work then most likely this is a conda-smithy bug or an issue with the recipe itself.

**Comment by dbast** [comment]
Ok. Thanks. Could be a conda-smithy bug, as local rerender fails with `KeyError: 'parent_recipe'`.

So two things to do: 1. figuring out / fixing the root cause. 2. Feedstocks with `buildnumber => 1000` where a uncomplete PR was merged and so the package is not yet fully migrated.

**Comment by CJ-Wright** [comment]
I think this error was a mismatch between conda-smithy and conda-build
