### ISSUE TITLE
Awesome data visualization

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#43]
We now have quite the treasure trove of data on how packages depend on one another. It would be awesome to have some cool visualization of this data.

**Comment by jakirkham** [comment]
Probably have already seen this, just linking it here as there might be some nice ideas to pull from.

xref: https://github.com/conda-forge/conda-forge.github.io/issues/79

**Comment by CJ-Wright** [comment]
Yes, sorry for the duplication.

**Comment by CJ-Wright** [comment]
I'm going to close this since @justcalamari produced a pretty good graph as part of GSOC

**Comment by jakirkham** [comment]
Do you have a link to that or the code used to generate it?

**Comment by CJ-Wright** [comment]
I don't know, at this point I would just make it from scratch and put the notebook into `by_the_numbers`
