### ISSUE TITLE
Check why the bot failed to handle multiple hashes with pre-processor selectors

### ISSUE THREAD

**Issue by ocefpaf** [regro/cf-scripts#430]
The bot failed to update the hashes properly in https://github.com/conda-forge/antlr-python-runtime-feedstock/pull/2

For more info see https://github.com/conda-forge/antlr-python-runtime-feedstock/pull/2#discussion_r243265221

**Comment by CJ-Wright** [comment]
I found the reason for the bug. We currently only handle this for platforms not for other selectors. This needs a modification to the version migrator.

**Comment by ocefpaf** [comment]
Thanks for looking into this @CJ-Wright!

**Comment by CJ-Wright** [comment]
It needs a bit more investigation though.

**Comment by jakirkham** [comment]
Here's another use case ( https://github.com/conda-forge/container-diff-feedstock/pull/9 ).

**Comment by CJ-Wright** [comment]
I think the main issue here is that we render the feedstock to figure out which url(s) to use, which may cut down on the number of OSs we see. Additionally we may not know which OS goes to which hash.

**Comment by ocefpaf** [comment]
> I think the main issue here is that we render the feedstock to figure out which url(s) to use, which may cut down on the number of OSs we see

So if we want to fix this we would need to improve `conda render` support for multiple platforms. Maybe it will be easier to compiler it from source :wink: 

Thanks @CJ-Wright!

**Comment by pkgw** [comment]
Also an issue for rust-feedstock, where the bot does very well but currently fails to update the hash Linux/x86_64 source file, e.g.: conda-forge/rust-feedstock#48.

**Comment by beckermr** [comment]
@pkgw I think there is a bug in the rust recipe causing this problem? 

https://github.com/conda-forge/rust-feedstock/pull/49

**Comment by pkgw** [comment]
@beckermr Seems so! Merged.
