### ISSUE TITLE
pysoundfile not getting version update auto-ticks

### ISSUE THREAD

**Issue by scopatz** [regro/cf-scripts#435]
This is likely because the PyPI name is different than the package name: https://github.com/conda-forge/pysoundfile-feedstock/blob/master/recipe/meta.yaml#L2

**Comment by scopatz** [comment]
Or maybe it just never got the cb3 migration, but that shouldn't have prevented version bumps.

**Comment by CJ-Wright** [comment]
How is it noarch with a compiler?

**Comment by CJ-Wright** [comment]
Maybe you could swap the name and pypi name Jinja and the bot might work.

**Comment by scopatz** [comment]
> How is it noarch with a compiler?

Because I wasn't thinking this morning  :)

> Maybe you could swap the name and pypi name Jinja and the bot might work.

Yeah, is there any way to test that?

**Comment by CJ-Wright** [comment]
You could put the new text into the cf-scripts test suite, you'd need to backdate the version number.

**Comment by isuruf** [comment]
> This is likely because the PyPI name is different than the package name

This is not an issue

**Comment by CJ-Wright** [comment]
I think this has been fixed
