### ISSUE TITLE
Multi package/source recipes

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#45]
With conda build 3 there is a capacity for multiple package/source recipes. This may create a whole bunch of issues for the bot.

1. Our whole replacement setup is based off of singular jinja2 variables and values for keys, this could break that a whole bunch. (this has come up with multi os checksums)
1. I'm not certain what this does to the structure of the graph.

**Comment by CJ-Wright** [comment]
@justcalamari does #177 address this (if so could you close?)

**Comment by justcalamari** [comment]
I don't think so. Looking at the conda-build docs, when there are multiple urls, they are a list in the form
```
source:
  - url: source1
  - url: source2
```
but the bot doesn't currently look for patterns of this form.

**Comment by justcalamari** [comment]
We still have problems with multiple sources and jinja variables, but this is solved otherwise.

**Comment by justcalamari** [comment]
We could handle jinja variables by solving #122, so I think can be closed.

**Comment by jakirkham** [comment]
We had an issue with this working in PR ( https://github.com/conda-forge/gosu-feedstock/pull/5 ). Should this be reopened or should we move it to a new issue?
