### ISSUE TITLE
Permissions needed for label adding

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#453]
We need permissions for the label adding. We might consider using the admin bot's credentials for this task. One worry would be causing the admin bot to run out of API tokens.

**Comment by scopatz** [comment]
Maybe the auto-tick bot could request labels and the admin bot would actually add them?

**Comment by CJ-Wright** [comment]
Maybe? There are two parts to this: just making the labels so they are accessible to maintainers and adding labels to PRs (eg for certain migrations)

**Comment by CJ-Wright** [comment]
Exactly. I guess we should open an issue against the webservice to add that capability.

**Comment by scopatz** [comment]
Yeah, I agree

**Comment by CJ-Wright** [comment]
That capability exists now
