### ISSUE TITLE
docs out of date?

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#457]
It appears the documentation in the README is out of date. It looks like these jobs have moved to a single circle cron job. Would be helpful to me to see an updated version as I am trying to add a migrator for gfortran on osx.

**Comment by CJ-Wright** [comment]
Yes, this is a major issue for this project, sorry! I'll try to put up some super basic docs for adding a migrator today.

**Comment by CJ-Wright** [comment]
I think the readme is fixed.
