### ISSUE TITLE
xgboost autoupdate doesn't work?

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#469]
Found this in Stage 2 of the linked log.

```
2019-02-28 18:22:46,288 WARNING  conda_forge_tick.update_upstream_versions || Error getting uptream version of xgboost: argument of type 'NoneType' is not iterable
```

ref: https://circleci.com/gh/regro/circle_worker/5852

**Comment by jakirkham** [comment]
cc @aldanor @beckermr

**Comment by beckermr** [comment]
@jakirkham Can you give some more details on this?

**Comment by jakirkham** [comment]
Unfortunately not. Let's see what @CJ-Wright thinks.

**Comment by CJ-Wright** [comment]
xgboost uses a git_url I don't think we support that.

**Comment by scopatz** [comment]
Yeah, nor should we :wink:

**Comment by beckermr** [comment]
Ahhhhhh. OK. I think this was inherited from changes to support R in the same recipe. I'm going to make an issue on the feedstock and then we can close this one.

**Comment by beckermr** [comment]
https://github.com/conda-forge/xgboost-feedstock/issues/22

**Comment by jakirkham** [comment]
Cool, thanks everyone. :)
