### ISSUE TITLE
Add conda-build to ppc64le migration

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#473]
conda-build is too old in ppc64le for a package I want to build.

**Comment by CJ-Wright** [comment]
You can add it to the set here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L894

And it will be included as a leaf of the graph to be rebuilt

**Comment by isuruf** [comment]
It's already included. Some packages depending on it are not yet built. Thanks for the pointer
