### ISSUE TITLE
python-spams gets incorrect PR updates

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#476]
We have had a few update PRs at `python-spams` that have been completely incorrect. For example they show major version bumps (with minor and patch release bumps included) that have not happened. Not entirely sure why this is, but am raising it here.

xref: https://github.com/conda-forge/python-spams-feedstock/pull/27
xref: https://github.com/conda-forge/python-spams-feedstock/pull/28
xref: https://github.com/conda-forge/python-spams-feedstock/pull/38

**Comment by CJ-Wright** [comment]
Hmm that is odd, maybe this is one of those places where it will respond affirmatively to any version number we ask for?

**Comment by jakirkham** [comment]
Maybe. Though how do we decide to request something like 4.1.2 instead of say 4.0.0?

**Comment by CJ-Wright** [comment]
I think the code for that is here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py#L32

**Comment by jakirkham** [comment]
Would it be possible to simply remove `python-spams` from the auto-tick bot? It seems to be getting this wrong more often than right unfortunately.

ref: https://github.com/conda-forge/python-spams-feedstock/pull/40
ref: https://github.com/conda-forge/python-spams-feedstock/pull/41
ref: https://github.com/conda-forge/python-spams-feedstock/pull/42
ref: https://github.com/conda-forge/python-spams-feedstock/pull/43

**Comment by scopatz** [comment]
There was talk of being able to have packages blacklist themselves.  I am not sure we ever implemented it, though

**Comment by jakirkham** [comment]
Do you know where that discussion was?

**Comment by scopatz** [comment]
It was just between @CJ-Wright and myself. I don't think we wrote anything semi-formal down
