### ISSUE TITLE
Migrate more packages for ppc64le?

### ISSUE THREAD

**Issue by jchodera** [regro/cf-scripts#494]
Now that the [Power9 architecture](https://en.wikipedia.org/wiki/POWER9) is available more widely in supercomputers such as [ORNL Summit](https://www.olcf.ornl.gov/summit/), it would be very useful to have more packages migrated for `ppc64le` builds. The current [`ArchRebuild`](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L889-L940) limits migration to a small number of target packages. Is there a plan for expanding this to larger package sets, or the full `conda-forge` set of recipes at some point?

**Comment by CJ-Wright** [comment]
If you have packages you would like to see, we'd be happy to accept PRs adding those packages!

Currently, I don't think there are plans for rebuilding the entire ecosystem for `ppc64le`. However, if there is a lot of interest we can certainly start discussing it. The current migration is aimed at understanding users' needs and assessing how much usage the new packages will get, so adding more packages and use cases would be great!

**Comment by mariusvniekerk** [comment]
Right now https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators.xsh#L898-L933 dictates what we are migrating

**Comment by jchodera** [comment]
Awesome! That makes this much easier---thanks!

**Comment by CJ-Wright** [comment]
Please feel free to open PRs with additional packages for ppc64le.
