### ISSUE TITLE
Migrators for boost-cpp/boost

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#505]
Many C++ libraries leverage Boost as it is a batteries included standard library for C++. That said, it updates every few months and breaks on minor versions (sometimes even on patch releases). Thus we need to rebuild a plethora of C++ libraries as a result. Given this, it would be very helpful to have a migrator for Boost. Due to the regular nature of these issues, we may want to automate the Boost migrator to some extent.

**Comment by CJ-Wright** [comment]
I think cfep-9 will help with the automation in the near future. For now I think the migrator system is pretty easy to add simple migrations to.
