### ISSUE TITLE
Find all the feedstocks without license

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#51]
See: https://github.com/conda-forge/staged-recipes/pull/5310

**Comment by CJ-Wright** [comment]
And also either issue an issue against the feedstock, or try to fix it (if it is an R library this may be possible)

**Comment by jakirkham** [comment]
We could actually do this with the canonical `conda-forge-maintenance` job. Given this is a bit of a one-off, that might be better than trying to kludge something together for the update bot.

**Comment by CJ-Wright** [comment]
Sure! I can provide a list comprehension of all the recipes which have license issues, if that helps/

**Comment by CJ-Wright** [comment]
I think this is addressed by #637 which finds all the unlicensed feedstocks and writes them to a file.
