### ISSUE TITLE
Try adding noarch

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#52]
`noarch` ~all~ most of the things!

In the process of bumping version numbers on many feedstocks I found that a lot of them may be good candidates for `noarch`. It would be good to have something that goes round and tries to build `noarch` version of feedstocks which match some criteria which make a project *likely* to be noarch friendly.
I expect that some of the criteria would be:
1. no selectors
1. no `toolchain` dep
1. python installed

I don't know if that is a comprehensive list, but it may be better to just put out the PRs and see if they work.

**Comment by CJ-Wright** [comment]
We now store both the parsed dict and the text, so it should be possible to hunt for the selectors, toolchain, and python.

**Comment by isuruf** [comment]
I remember somebody writing a script that downloaded the metadata of python packages and checked that they contained C/C++ libraries. Maybe @jakirkham remembers

**Comment by CJ-Wright** [comment]
Could we crawl through the tarball and look for files with C/C++ extensions?

**Comment by CJ-Wright** [comment]
We might also try loosening the selectors rule, since we can convert python version selectors over to python version constraints.

**Comment by CJ-Wright** [comment]
Might also consider putting up issues instead of PRs. I think that PRs may be easier for maintainers to work with, but it may produce broken packages if maintainers don't do their due diligence and we miss something and move to `noarch` incorrectly.

**Comment by CJ-Wright** [comment]
This might fit well in the new `Migrator` syntax (just have it listed as its own).

**Comment by scopatz** [comment]
Also note that setup.py can choose to install platform-specific code, too.  So not all pure python projects can be noarch

**Comment by CJ-Wright** [comment]
Can we compile a list of these issues and put them into the PR body as warnings?

**Comment by CJ-Wright** [comment]
xref: https://github.com/regro/cf-scripts/issues/183

**Comment by CJ-Wright** [comment]
I'm going to close this since we have issued almost all the currently available noarch PRs.
