### ISSUE TITLE
help with deid-feedstock

### ISSUE THREAD

**Issue by vsoch** [regro/cf-scripts#525]
Hi!

Some of the builds are failing here https://github.com/conda-forge/deid-feedstock/pull/2
and I'm not sure if this is expected (given the module isn't supported on windows) or if it's a bug. I have a few other feedstocks that aren't supported on windows, but I don't see the same build failures.

https://github.com/conda-forge/deid-feedstock/pull/2

Thanks!

**Comment by vsoch** [comment]
![image](https://user-images.githubusercontent.com/814322/60059033-97aa5600-969f-11e9-815b-15d6cd3ebe17.png)

**Comment by CJ-Wright** [comment]
This looks like it has been resolved. Please open if not.
