### ISSUE TITLE
regro-cf-autotick-bot not pulling pypi sha

### ISSUE THREAD

**Issue by michaelbilow** [regro/cf-scripts#529]
I'm not sure whether this is intended behavior or a bug, but it would be nice (at least for me) if the autotick-bot took the sha of the new version, for example:

https://github.com/conda-forge/issho-feedstock/pull/5/commits/fb6ef967685240e6f88ba55d306d1d457b748441 was pushed by the autotick-bot, but did not update the sha available at https://pypi.io/packages/source/i/issho/issho-0.5.1.tar.gz, the source url defined by the rendered meta.yaml.

**Comment by scopatz** [comment]
Normally it does update the sha256sum.  I wonder what went wrong.

**Comment by michaelbilow** [comment]
Thanks for the response; let me know if there's something I can do to pitch in.

**Comment by scopatz** [comment]
If you can find the job that this failed on in the `regro/circle_worker` repo, that'd be great!  It might be kind of a slog, though...

**Comment by chrisjsewell** [comment]
FYI, this just happened to me as well: conda-forge/pytest-notebook-feedstock@41ea768db4a8b029c538e09c4b0feea2edfd2d71

**Comment by scopatz** [comment]
hmm maybe this is because the sha value is in quotes.

**Comment by scopatz** [comment]
In the meta.yaml, that is

**Comment by scopatz** [comment]
Specifcally, https://github.com/regro/cf-scripts/blob/46008e51efc5add77adcf8aa108a3913f96b8ddd/conda_forge_tick/migrators.xsh#L265 and surrounding logic does not seem to capture quote characters.  PRs welcome!

**Comment by ericpre** [comment]
Another instance, where the sha256 was not updated by the bot: https://github.com/conda-forge/matplotlib-scalebar-feedstock/pull/1/commits/31815f64e192bcccc21438ffe7a3fdfd8ebc4ced.

> hmm maybe this is because the sha value is in quotes.

In this case (https://github.com/conda-forge/matplotlib-scalebar-feedstock/pull/1/commits/31815f64e192bcccc21438ffe7a3fdfd8ebc4ced), the sha256 is in quotes in the meta.yml file.

**Comment by CJ-Wright** [comment]
Yea it seems that quotes are a problem with our current regex.

**Comment by phil-blain** [comment]
I'm not sure if this is the same issue, but in the the recent PR for Git 2.24 the bot failed to update the hashes (in this case there are no quotes) : 
https://github.com/conda-forge/git-feedstock/pull/68/commits/9c03fb89c92c4e32ccc264f8d9ebd2b6cc8cf633#diff-e178b687b10a71a3348107ae3154e44cL1-L25

https://github.com/conda-forge/git-feedstock/pull/68

I'll open a new issue if people feel this is a separate issue.
