### ISSUE TITLE
How often to packages update their versions

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#53]
In aggregate this question is about how many PRs we should expect the bot to make in one day.

**Comment by CJ-Wright** [comment]
I don't think we can answer this until we are finished with bootstrap.

**Comment by CJ-Wright** [comment]
FYI, we have about ~280 feedstocks left to bump (of the ones we can bump, including the ones we currently can't upstream version numbers for we are missing about 1400 (mostly R recipes from what I can see))

**Comment by jakirkham** [comment]
Do you have a better idea now?

**Comment by CJ-Wright** [comment]
Not that often it seems (03 finished without timeout), so this seems ok so far. But we'll have another round of bootstrap soon so we'll see.

**Comment by CJ-Wright** [comment]
Going by GH contributions it seems that the bot makes 20-60 contributions a day.

**Comment by CJ-Wright** [comment]
I think this is pretty well solidified for now, we can look at the bot's contributions: https://github.com/regro-cf-autotick-bot
