### ISSUE TITLE
restart bad and bad upstream

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#56]
As we make enhancements to the code we should consider cleaning out bad and bad upstream. That way things that we couldn't process we can get another shot at.

**Comment by CJ-Wright** [comment]
I think this has been fixed by #171

**Comment by justcalamari** [comment]
I don't think this is completely fixed. While writing to upstream bad was removed in 03, it is still written to in update_upstream_versions.

**Comment by CJ-Wright** [comment]
Ah ok.
