### ISSUE TITLE
Updating wrong version

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#567]
Appears that the bot updates the wrong version number in PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/1 ). Namely it is updating the metapackage instead of the Jinja version used by the actual package.

**Comment by CJ-Wright** [comment]
I think the bot regexs for `version` so other things may trip it up.
Maybe put in a regex for something like `replace_me_bot_version` first and if it is found replace and break otherwise look for regular `version`?

**Comment by jakirkham** [comment]
We can reorder the split packages if that helps. I can't tell if that would help or hurt people reading the recipe yet, but we could give it a try. That would avoid changing the bot for this use case.

Alternatively, I'm curious if we move the source into the split package (as it is only needed for one of the outputs), how would the bot handle this case? Would it know how to update the recipe?

**Comment by CJ-Wright** [comment]
I don't know.

**Comment by isuruf** [comment]
You can change the jinja to,
```
{% set version = "1.5.1" %}
{% set ucx_prot_version = "1.0.0" %}
```

**Comment by jakirkham** [comment]
Thanks! I tried this change ( https://github.com/conda-forge/ucx-split-feedstock/pull/17 ).
