### ISSUE TITLE
Tighten timing between closing bot-rerun and opening new PR

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#578]
We could do this by moving the bot-rerun label things into the auto_tick section, reducing the ability of the system to fail in a bad state.

**Comment by mariusvniekerk** [comment]
Alternatively, we can just run another agent at a tighter timing interval that ONLY does bot-rerun

**Comment by CJ-Wright** [comment]
With the reduced thrashing and a new account they would be great!

**Comment by CJ-Wright** [comment]
I think this is mostly fixed now, since we close out bot-rerun labels first before updating. That way if we know about any bot-reruns then they go forward.

Ultimately this will be fixed by GH actions that report when the `bot-rerun` label has been added and modify the PR entry.
