### ISSUE TITLE
Failed Regex replacements

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#58]
https://github.com/conda-forge/reentry-feedstock/pull/1#issuecomment-370418527

**Comment by justcalamari** [comment]
I'm guessing this is happening because there is no space before the %}.

**Comment by CJ-Wright** [comment]
Yep

**Comment by scopatz** [comment]
Spaces are not required before %}

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/sortedcontainers-feedstock/pull/9

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/uritools-feedstock/pull/1

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/tinydb-feedstock/pull/8

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/cython-feedstock/pull/29

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/python-dateutil-feedstock/pull/11

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/kubernetes-feedstock/pull/2

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/tinydb-feedstock/pull/9#issuecomment-376309339

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/ipython-sql-feedstock/pull/7#issuecomment-379414969

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/sortedcontainers-feedstock/pull/11

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/datreant.data-feedstock/pull/5#issuecomment-387227925

**Comment by justcalamari** [comment]
This is mostly solved. Could still fail if a feedstock uses a variable name that we don't look for, but this case is captured by #122
