### ISSUE TITLE
version update bot should not propose updates for globally pinned packages in conda-forge pinnings repo

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#581]
Right now the bot will propose updates for packages which are pinned globally. It should not do that.

**Comment by beckermr** [comment]
The problem is that on subsequent migrations of some dep of the pinned package, the pinned version won't be rebuilt, just the latest version.

**Comment by isuruf** [comment]
How will they get updated then? Also, there are some deps like boost, which can be used as headers only.

**Comment by beckermr** [comment]
For globally pinned packages, someone will have to propose a pinning migration on the pinnings repo per CFEP-9.

**Comment by beckermr** [comment]
The case of header-only deps seems like something we should swallow. A few extra rebuilds is better than what I am doing now, which is going back and fixing a bunch of netcdf* pins that got out of sync.

**Comment by isuruf** [comment]
> For globally pinned packages, someone will have to propose a pinning migration on the pinnings repo per CFEP-9.

No, I mean the globally pinned package. Who would update that package? If the bot doesn't propose an update, that package will go stale.

**Comment by beckermr** [comment]
The bot will have to propose a migration then. Right now, the bot proposes an update to the feedstock (say libnetcdf 4.6.2 -> 4.7.0) without changing the global pinnings or doing a proper migration.

**Comment by beckermr** [comment]
Instead, for globally pinned packages, the bot should write the YAML pinnings migration snippet, put it in the pinnings feedstock, and migrate the full stack. 

However, usually, stuff is pinned globally for a reason. Having a human check might not be the worse thing.

**Comment by CJ-Wright** [comment]
Why are the downstream packages getting the newer version? If we haven't migrated the pin then they should be pinned to the prior version, right?

**Comment by beckermr** [comment]
It is the deps of the pinned package that matter. 

Imagine a pinned package named `foo` that depends on `hdf5`. Suppose the most recent build of that pinned package (say `foo` v1.0) used `hdf5` v10.4. Then the version migration bot moved the pinned package ahead of the global pin (so `foo` goes to v2 in the feedstock). Next someone bumps `hdf5` to 10.5 in the global pinnings and the bot proposes a rebuild. The rebuild will be on the current master of `foo`'s feedstock, which means the bot rebuilds `foo` v2 to work with `hdf5` v10.5. 

This sequence of events leaves the globally pinned version of `foo` (v1) with a dependence on hdf5 which is out of date (v10.4 instead of v10.5).

**Comment by beckermr** [comment]
So to finish this hypothetical situation out, what then happens is that some downstream package might depend on both `foo` and `hdf5`. In this case, we risk solver errors since we cannot satisfy both `hdf5` 10.5 and `foo` v1.

**Comment by CJ-Wright** [comment]
I do not think tying the bots hands in the manner will help us much as @isuruf noted many packages go stale quite quickly.

I think the better solution is outlined in https://github.com/regro/cf-scripts/issues/568
In your example if foo v1 is to be a long term supported library then it most likely should exist as it's own branch. 

PRs to the effect of #568 would be encouraged!

**Comment by beckermr** [comment]
I was not aware that branches for pinned package versions was preferred. I am skeptical others are aware too, but it is hard to say.

Putting all pinned packages in branches and addressing #568 doesn't solve the fact that the global pinnings will still be out of date since the bot is only updating the feedstock version, not the pinnings file.

OTOH, if we have the bot propose pinning migrations per CFEP-9 when a pinned package has a version change, then we get the best of both worlds. We get the automatic updates so that stuff does not go stale. We also get the semi-ordely migrations that CFEP-9 enables.

**Comment by CJ-Wright** [comment]
I think this issue needs to be raised on conda-forge.github.io, since this boils down to a policy decision about if we want to backport pins or if we want to have every version update to a pinned package result in a migration. @beckermr would you mind opening a new issue?

**Comment by beckermr** [comment]
Not at all! No time today but I’ll get to it later.

**Comment by CJ-Wright** [comment]
@msarahan @soapy1
