### ISSUE TITLE
Check CDN for packages in addition to PR status

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#595]
This way we don't face plant into not yet live packages.

**Comment by scopatz** [comment]
agreed

**Comment by CJ-Wright** [comment]
We could do this from libcfgraph, since that reads out repodata.json every hour. This requires some feedstock to package/artifact mapping.

**Comment by CJ-Wright** [comment]
The idea would to add something to the `MigrationYaml` migration class `filter` method to check `libcfgraph` if all the parent packages have been rebuilt with the new pin.

**Comment by CJ-Wright** [comment]
I think this has made some progress now that we have dynamo setup. We can put data from the feedstock CI into a dynamo table noting what the feedstocks think they have published and then compare it to the CDN. This is critical for wider use of the auto-merge functionality.

**Comment by CJ-Wright** [comment]
This is done via mamba for now, for migrations+feedstocks with automerge or feedstocks that request it.
