### ISSUE TITLE
handle multiple output recipes better

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#604]
Migrations currently do bad things when running into multiple output recipes, since we don't formally have a feedstock with that name, creating weird edges. 

I think a good fix would be to:
1. Track output names at the top level of the node attributes for easy access
2. Assemble a lookup table which maps output name to feedstock name
3. When building the edges look things up in the lookup table if they are not in the graph or are archived in the graph.

This should make the topo sorts work properly, we may need to also look at the migrators themselves to make certain they are walking the graph correctly.

**Comment by CJ-Wright** [comment]
@ocefpaf

**Comment by ocefpaf** [comment]
Thanks @CJ-Wright! I looked into the code and it does not seems simple to me what the best course of action is.

CJ and I discussed this a little bit yesterday. At the moment this is not a big deal but, as we split more recipes to output static and shared libraries using multiple outputs, this may cause headaches down the road.

**Comment by CJ-Wright** [comment]
I think this is fixed now. Scotch still runs into problems, but that is because we aren't handling the `conda_build_config` gracefully. xref: #664
