### ISSUE TITLE
azure pipelines build checks not using the latest versions in OSX and Python 3.7

### ISSUE THREAD

**Issue by martibosch** [regro/cf-scripts#610]
I am [trying to add the latest release of PyLandStats to conda forge](https://github.com/conda-forge/pylandstats-feedstock/pull/6), nevertheless the automated checks are failing for OSX and Python 3.7.

As pointed out [elsewhere](https://github.com/serge-sans-paille/pythran/issues/1363), this is because the automated build check uses pythran 0.9.3.post0 instead of 0.9.3.post1, which is already available at conda-forge and it is used in the rest of automated checks (which build successfully).

Is there anyway that I can force the automated checks to upgrade to pythran 0.9.3.post1?
Thank you in advance.

**Comment by CJ-Wright** [comment]
Would you be able to open this issue with the pythran feedstock? I don't think this is an error with the bot itself.

**Comment by martibosch** [comment]
I actually first opened [the issue in the Pythran main repository](https://github.com/serge-sans-paille/pythran/issues/1363), but it seems that the error is more related to dependencies that come from elsehwere (see [the logs in this answer](https://github.com/serge-sans-paille/pythran/issues/1363#issuecomment-532639668) for more details). But I do not know much about how the whole conda-forge stack works, so if you believe that pythran's feedstock is the appropriate repository to open this issue, I will do so.

Thank you,
Martí
