### ISSUE TITLE
skip win builds

### ISSUE THREAD

**Issue by sebastian-luna-valero** [regro/cf-scripts#611]
Hi,

**regro-cf-autotick-bot** generated a PR to update a feedstock where I am skipping Windows builds:
https://github.com/conda-forge/gstreamer-orc-feedstock/pull/1

However, AppVeyor keeps kicking in and failing with:
```
The build phase is set to "MSBuild" mode (default), but no Visual Studio project or solution files were found in the root directory. If you are not building Visual Studio project switch build mode to "Script" and provide your custom build command.
```

Is this expected?

Best regards,
Sebastian

**Comment by CJ-Wright** [comment]
I think this is a smithy issue rather than bot
xref: conda-forge/conda-smithy#1155
