### ISSUE TITLE
DOC: migration_ts meaning, usage, and generation of

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#636]
Currently `migration_ts` doesn't appear to be documented. Or at least can't be found when searching the docs. Would be good to document and index it. In particular would document what it means, how users generate it, and what role it plays in migrations.

**Comment by jakirkham** [comment]
Copying @CJ-Wright's ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/287#issuecomment-539141145 ) here:

> The timestamp of the migration, you can use your `time.time()` from python. It is there to make certain that the yaml files are applied in order.

**Comment by jakirkham** [comment]
Independently, would it make sense to automate generation of any fields like this? Or perhaps extract this info from git commit info? Just thinking this might be something the user doesn't need to interact with directly.

**Comment by CJ-Wright** [comment]
Note that this is commented in the example migration https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/example.exyaml#L1

Pulling from git might be a bit tricky since we may update the file along the way, but may be doable.

**Comment by jakirkham** [comment]
In either case, it would be nice to have a sentence or two in the docs.

Adding a link to the example seems simple and probably less error prone.

**Comment by jakirkham** [comment]
Fixed in PR ( https://github.com/regro/cf-scripts/pull/645 ).
