### ISSUE TITLE
More efficient use of Travis/API calls

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#64]
Currently we have split up the scripts over different repos, however that may not be the most efficient use of Travis or our API calls. We could consider back filling our current scripts with `03` to fill up the API calls and other status scripts (cycle checking, current PR/out-of-date, etc.) to fill up the time.

Current usage status:

| Script | API calls | time|
|:-------:|:------------:|:-----:|
|`00`| few | 4:12|
|`01` | 3756 (many) | 21:09 |
|`02` | few | 7:10 |
|`03` | few | 43:43 |

For example we could tack a run of `03` onto `00` to almost double our time creating PRs.

Note that the main changes required are:
1. Each worker needs to run a generic script which we can update to have subscripts
1. Each worker needs to keep track of their internal time better than we are doing currently, so we can stop before we get timed out (otherwise we may not write to the graph critical information back to the repo)

**Comment by jakirkham** [comment]
If you are able to operate through git more (e.g. clone repos and inspect files locally), that comes at no penalty.

More generally the biggest saver will be converting this into a web service. ( https://github.com/regro/cf-scripts/issues/54 ) 😉 Though we can discuss that over there.

**Comment by CJ-Wright** [comment]
I'm hoping that since we are finished with bootstrap we won't tax Travis as heavily, but we'll see.

**Comment by CJ-Wright** [comment]
I think we're pretty efficient now. If we weren't hitting a ton of migrations we can't do anything about the bot would take ~15 mins to run and has many API calls.
