### ISSUE TITLE
Find out if the CircleCI token is expired...

### ISSUE THREAD

**Issue by ocefpaf** [regro/cf-scripts#65]
...and issue the webservices command to update it.

**Comment by CJ-Wright** [comment]
What is the best way to find out iff the token of expired?

**Comment by ocefpaf** [comment]
I don't know. Maybe @isuruf knows how to do that.

**Comment by isuruf** [comment]
I'm not sure, but I think the number of ssh keys of a repo = 0 is a good indication. @ocefpaf, if you see a token issue, can you check?

**Comment by jakirkham** [comment]
Maybe it's cheaper to just always update the CircleCI SSH key when creating an update PR. ;)

**Comment by CJ-Wright** [comment]
Can I put a call to the web-service in every bot PR? :smile:

**Comment by ocefpaf** [comment]
> Can I put a call to the web-service in every bot PR? 

Please don't.

> I'm not sure, but I think the number of ssh keys of a repo = 0 is a good indication. @ocefpaf, if you see a token issue, can you check?

I'll look around. I'm sure there are some old feedstocks out there for us to play.

**Comment by CJ-Wright** [comment]
I think this is mostly taken care of (esp. we've moved to azure)?
