### ISSUE TITLE
move database to dynamodb

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#651]
GitHub is great for some things, especially when we migrate the database and need to keep undoing things. However, this can make life more difficult for other things we'd like to do, since one must have a complete copy of the entire repo to perform any non-read operations on the data. For instance if we want to have any other bots write to the graph then they need to have a complete copy of the graph. I think it would be much more efficient if they could write to node metadata themselves without the need for the complete database to be local.

Do we want to move?
Where should we move to?

**Comment by beckermr** [comment]
I think it has to be dynamodb due to cost.

**Comment by beckermr** [comment]
Rough, obvious plan: We run both systems in parallel until we can switch over.

1. standup dynamodb w/ proper permissions
2. implement code to write data to dynamdb
3. implement code to generate PRs etc from dynamodb
4. pull the switch

**Comment by CJ-Wright** [comment]
Would it be possible to keep the `LazyJson` API then we can do a 1 for 1 swap.

**Comment by beckermr** [comment]
I don’t know enough about either system to say.

**Comment by beckermr** [comment]
But I could imagine an object that fetches data on the fly lazily from the db

**Comment by CJ-Wright** [comment]
and has auto writing.

**Comment by beckermr** [comment]
Right. I don’t personally understand the transaction semantics supported well enough to know what is possible. 

More or less, when the bot is running, we want it to see a consistent state of the database, even when other processes are updating it. This is definitely possible for database systems but idk exactly what dynamodb supports.

**Comment by beckermr** [comment]
It appears that dynamodb supports transactions for reads and writes, but if we are doing a read and some other process starts to write, the read gets cancelled.

**Comment by beckermr** [comment]
https://stackoverflow.com/questions/54245599/mysterious-transactionconflict-in-transactioncanceledexception

**Comment by viniciusdc** [comment]
@beckermr I was wondering, as I have already created the new version function (just need to populate the folder) can we use DynamoDB or we will forget this ?

**Comment by beckermr** [comment]
I think we close this for now.
