### ISSUE TITLE
auto pin PRs

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#665]
It would be nice if the bot issued a migration PR if it issued a version bump PR for a pinned package that caused the version to move out of the `run_exports` supported range. This PR then could be accepted or rejected, without requiring a human to make the PR. This would also help shift control of the ABI compatibility ranges to the maintainers of the feedstocks themselves, as changes to the `run_exports` and versions would automatically result in a migration proposal. Finally this would help with pins that we are missing, for example `arrow-cpp` was missing a pin until recently despite declaring a `run_exports`.

Proposed design:
1. When doing a version bump regex the `raw_meta_yaml` for `max_pin=...`, extract the max_pin.
2. Determine if the new version is outside the max_pin range.
3. If so produce a migration PR and issue that PR into the pinning feedstock (after issuing the version bump PR). Include in this PR a link to the Version bump PR and the number of packages impacted/plot of the graph for the migration.

Attn: @regro/auto-tick @wolfv @beckermr

**Comment by beckermr** [comment]
Should this be a CFEP? It is very much related to issues on migrating pins we have been discussing.

**Comment by CJ-Wright** [comment]
Maybe? I think this issue is more along the lines of a bot capability, rather than a change in /expression of policy. My current view (although I'm happy to have my mind changed) is that this capability would perform tasks that humans are/should already doing; proposing migrations when a pinned package breaks its ABI (as defined by the `run_exports`).

**Comment by beckermr** [comment]
Ahhhh I see the distinction. I am not on core so this is not my call, but I get what you are saying.

**Comment by CJ-Wright** [comment]
BTW, this is why the automated pin moves discussion *would* need to be a CFEP. That is mostly a discussion around policy: "should we update pins every time an ABI break comes out". In this proposal we can reject the migration as we can now.
