### ISSUE TITLE
Handle node deletions

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#67]
Coming on the heels of our discussion earlier, it would make sense to figure out how to remove nodes from the graph as their feedstocks vanish. Though this may already be handled somehow.

**Comment by CJ-Wright** [comment]
This is not handled currently. One potential implementation would be to have a file in the cf-graph repo which lists the removed feedstocks and then have a script go and remove them from the graph and remove them from the file. Or we could have something directly remove nodes from the graph.

**Comment by CJ-Wright** [comment]
I guess some of this tooling exists to some extent now that we have an archived attribute for archived nodes. I guess I could make a similar cutout where the repo doesn't exist at all. Going forward are we going to delete feedstocks, or are we always going to archive them?

**Comment by CJ-Wright** [comment]
It seems archiving is the way to go so I'm going to close this. Feel free to reopen if needed.
