### ISSUE TITLE
Status 3.8 migration (some feedstock not touched)

### ISSUE THREAD

**Issue by h-vetinari** [regro/cf-scripts#688]
Is the 3.8 migration still ongoing? I can't see one on the CF [status page](https://conda-forge.org/status/), yet some of the feedstocks I'm involved in haven't seen a 3.8-PR yet (e.g. [1](https://github.com/conda-forge/imutils-feedstock) [2](https://github.com/conda-forge/osqp-feedstock) [3](https://github.com/conda-forge/podman-py-feedstock)).

**Comment by CJ-Wright** [comment]
Yes the migration is still ongoing

**Comment by ocefpaf** [comment]
Also, some of those have quotes on the URL and that breaks the bot.

**Comment by CJ-Wright** [comment]
You can see the graph of currently PRed and pending packages here: https://github.com/regro/cf-graph-countyfair/blob/master/status/python38.svg (you can open it up in a new tab/window and ctrl+f for searching)

**Comment by h-vetinari** [comment]
Thanks for the infos!

> @ocefpaf: Also, some of those have quotes on the URL and that breaks the bot.

Do you mean hyphens ("`-`")? Does this mean that all such feedstocks will have to be ported manually?

**Comment by h-vetinari** [comment]
> @CJ-Wright: You can see the graph of currently PRed and pending packages here: https://github.com/regro/cf-graph-countyfair/blob/master/status/python38.svg 

I wasn't able to load the svg, but the [json](https://github.com/regro/cf-graph-countyfair/blob/master/status/python38.json) works fine for me. :)

**Comment by ocefpaf** [comment]
> Do you mean hyphens ("`-`")? (I ask because I cannot see quotes in the url...)
 Nope. Quotes like your number 3, see   url: "https://pypi.io/packages/source/p/podman/podman-{{ version }}.tar.gz"

> In any case: does this mean that all feedstocks with affected URLs will have to be ported manually?

You'll need to remove the quotes. That was fixed in conda-build but a few recipes were created with them.

**Comment by CJ-Wright** [comment]
All of these are done or in PR
