### ISSUE TITLE
ENH add migrator to suggest dep on matplotlib-base instead of matplotlib

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#705]
Per the discussion here (https://github.com/conda-forge/conda-forge.github.io/issues/933), we might want to suggest via a migration that people use a dep on matplotlib-base instead of matplotlib. 

IDK how many a packages this might be, but it could be feasible to do this by hand if there are a small number of them.

**Comment by beckermr** [comment]
This is 503 packages so we need a migrator if we want to do this.

**Comment by CJ-Wright** [comment]
hmm ok, how would you know if to use matplotlib vs base?

**Comment by beckermr** [comment]
Whether or not you need pyqt.

**Comment by beckermr** [comment]
We might add this detail into the doc PR I have open on this.

**Comment by CJ-Wright** [comment]
ok
