### ISSUE TITLE
spaCy model updates do not get picked up by the bot

### ISSUE THREAD

**Issue by setu4993** [regro/cf-scripts#707]
One of the biggest differences for these, comparing with other libraries, is that [`spaCy models`](https://github.com/explosion/spacy-models) does not contain an `__init__.py` or `setup.py` that the bot can query for updates. Instead, the version updates are pushed using the json files in the `meta` directory, and are then available as releases.

What are alternatives that can be done to fix this behavior and set the bot to pick up the updates automatically?

Related: https://github.com/conda-forge/spacy-model-en_core_web-feedstock/issues/3

**Comment by CJ-Wright** [comment]
The code you need is in [here](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py) it handles the finding of upstream versions.

**Comment by setu4993** [comment]
Thank you for the quick response and getting me to the right source, @CJ-Wright.

I just looked over the code and there are a few things that I think might be going on, because of which the bot is unable to find the updates:
1. The repository releases include updates that should not be on the package (the package is limited to `en_core_web_` prefixed models). 
2. The `ver` [variable](https://github.com/regro/cf-scripts/blob/87d201866778d41a02b69c60bc517d3d42c5582b/conda_forge_tick/update_upstream_versions.py#L69), would include text from the release (example: `ver = 'pt_core_news_sm-2.2.5'` for the current latest item in the [feed](https://github.com/explosion/spacy-models/releases.atom)).

So, what I'm asking is, are there ways to:
1. Ask the bot to pick up only specific prefixed releases?
2. Filter `ver` to only pick numeric characters?

**Comment by CJ-Wright** [comment]
Sure, PRs welcome

**Comment by setu4993** [comment]
Thanks @CJ-Wright 

I tried creating and running a new test before adding any changes, and the current version of the script succeeds in the new [test](https://github.com/setu4993/cf-scripts/commit/2948649db3a53761fb983f58a8c360f18b94f6b9), suggesting it should've picked up the new version.

How else can I debug this?

**Comment by CJ-Wright** [comment]
I think the issue is not the migration part of the bot but the part that finds version updates. We don't have a test for that at the moment. I would suggest cloning the regro/cf-graph-countyfair repo and trying to run the update upstream version script and see if it gets your version.

**Comment by setu4993** [comment]
Thank you! That was the right direction.

I tested #711 locally and it correctly pulls the updated version.
