### ISSUE TITLE
Auto-tick PR stopped working for magics-feedstock

### ISSUE THREAD

**Issue by dtip** [regro/cf-scripts#722]
The regro-cf-autotick-bot seems to have missed the v4.2.3 of Magics. It worked fine for v4.2.0.

Manually opened PR here: https://github.com/conda-forge/magics-feedstock/pull/59

**Comment by ocefpaf** [comment]
The bot had some downtime this past week and that may have been the reason.

**Comment by CJ-Wright** [comment]
If you want to dig into the source code, I think the part causing problems is [here](https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py#L299(

**Comment by CJ-Wright** [comment]
I think this has been fixed now. Can you please reopen if this continues to be a problem.
