### ISSUE TITLE
make sure aarch migrator uses the parent class PR body

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#729]
I think the aarch migrator doesn't use the parent class PR body? It should.

**Comment by CJ-Wright** [comment]
Would you be interested in putting this into the mega refactor PR?

**Comment by beckermr** [comment]
I think keeping more commits out of that PR is best. We can make a smaller PR after that one is merged.

**Comment by beckermr** [comment]
Happy to oblige of course if you feel strongly though.

**Comment by CJ-Wright** [comment]
That's fine, we might have to wait a bit though, I expect that PR will cause a series of outages.
