### ISSUE TITLE
Better url for missing PRs

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#732]
Sometimes on the status page we have missing PRs, either due to error or the package was migrated manually. Currently we just send back to the current page. It might make sense to send people to the feedstock itself instead. https://github.com/regro/cf-scripts/pull/701#discussion_r362627235

**Comment by Prodyte** [comment]
@CJ-Wright I want to work on it

**Comment by CJ-Wright** [comment]
Great!

**Comment by Prodyte** [comment]
does this work, node_metadata["pr_url"] = pr_json["PR"].get("html_url", "") --> node_metadata["pr_url"] = pr_json["PR"].get(feedstock_url(), "") , by importing feedstock_url() from git-utils?

**Comment by beckermr** [comment]
Yep seems close. Make a pr!
