### ISSUE TITLE
distribute the bot w/ github actions

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#746]
We might use 

- https://github.com/pascalgn/automerge-action and have the bot add a label
- a custom action in python via Docker: https://alexwlchan.net/2019/03/creating-a-github-action-to-auto-merge-pull-requests/
- our own simpler custom action in javascript

To do/Notes:

- [ ] conda-smithy needs to enable this action on repos
- [x] version update PRs need to add the automerge label
- [x] write a docker action w/ whitelist 
- [x] figure out how github actions handle secrets or autosecrets (token is there)
- [x] opt-out on this
- [x] figure out what to do with failing lints (linter is not always accurate so we might want to merge anyways, ideally we should fix the linter)
- [x] figure out a way to quickly turn this off for all feedstocks if something goes wrong
- [ ] when making PRs for migrating the actions need to have `[ci skip] ***NO_CI*** ` in PR title

Proposal: 

- [x] Build a custom action in python based on the conda-forge docker container. This will allow us to expand and develop the functionality moving forward.
- [x] Create a (possibly separate) package that does the work of the action that is shipped and installed via conda for this action.
- [x] Use a `prod` tag on the repo and Docker image to control if the bot is on or off. By deleting this tag, the action should fail.
- [ ] Add the code needed to enable this action to conda smithy and migrate all feedstocks to use it with a mini-migrator. These migrations can skip rebuilds and be merged automatically. We could alternatively simply insert the code with the mini-migrator and skip rerendering. Note to self: we should randomize the time that each feedstock checks the web for instructions so that we do not overwhelm the server(s) with requests.

**Comment by CJ-Wright** [comment]
I think you don't need the label `When an empty string ("") is given, all pull requests will be merged.`

**Comment by CJ-Wright** [comment]
We might also not need a secret here if we don't mind the actions bot doing the committing. I think it will have commit rights to the repo it is running on.

**Comment by beckermr** [comment]
We don’t want to auto merge all prs though. So we should add the label.

**Comment by CJ-Wright** [comment]
Which PRs don't we want to merge? I think it will still check that the PR passes checks.

**Comment by beckermr** [comment]
Any other prs on the repo not made by the bot. Many times I am hacking on a recipe but don’t want to merge the PR yet.

**Comment by beckermr** [comment]
ack actually none of this will work. If we allow automerge via a label, then any one can add themselves to any feedstock

**Comment by CJ-Wright** [comment]
What do you mean?

**Comment by beckermr** [comment]
We need the auto merge action to have a whitelist if PR sources that it is allowed to work on. Otherwise someone could fork a feedstock, add themselves as a maintainer and then merge the result without a human.

**Comment by CJ-Wright** [comment]
I don't think non-maintainers can add their own labels. This is one of the issues with the bot as well. I'm happy to work with a whitelist as well

**Comment by beckermr** [comment]
Ahh yeah that is right.

**Comment by beckermr** [comment]
I think a whitelist is better since we would have to take an explicit action to change it.

**Comment by CJ-Wright** [comment]
I think I have seen versions of merge actions like that

**Comment by beckermr** [comment]
We can make an edit here to include a branch whitelist: https://github.com/pascalgn/automerge-action/blob/master/lib/merge.js#L67

**Comment by beckermr** [comment]
One more random thought. I'd rather have a simpler action that fails a lot versus one that will try and update PRs via merging etc. This failing for all but the simplest cases seems like a feature and not a bug.

**Comment by CJ-Wright** [comment]
You might also look at https://github.com/ppb/actions-bors which uses xonsh for gh actions

**Comment by beckermr** [comment]
Cool link! I was hoping to use a pure python package with an entrypoint so that we can write a full set of tests, both unit and integration. Basically the same logic for the current refactor here.
