### ISSUE TITLE
Add slug for PR merging bot

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#752]
We need to add a slug to the PRs so they can be identified and parsed by the merging bot. Maybe something in the initial comment with the information in the "data" key from the PR. 

@beckermr

**Comment by beckermr** [comment]
Sounds good. Can you point me to where that is defined? 

One side issue I just thought of is how to indicate to users that an automerge will happen. From this point of view, stuffing it in the PR title might be useful.

**Comment by CJ-Wright** [comment]
pr title is here:
https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/core.py#L346

the data itself is from here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/core.py#L364

You are welcome to override the pr title stuff (eg if you wanted to add things to version bumps). We may need some flags into the other migrators if we want it to be controllable, but I wouldn't worry about that for now.

**Comment by beckermr** [comment]
Ahhhh. We could simply have subclasses of migrator enable this by hand for now. Might be easiest to control. That would be an edit here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/core.py#L722

**Comment by CJ-Wright** [comment]
Yes, you could put it into there. You might also modify the title yourself if you have permissions if you wanted to test it by hand.
