### ISSUE TITLE
coordinate with automerge bot

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#755]
I thought this could be a place for handling coordination with the auto merge bot.

For instance we may decide that we want to increase the number of version bump PRs we issue once we start having people opt in. This way we can have feedstocks which need some merging help use the auto-merge functionality. This will in turn close out the old PRs and bring the feedstocks back into good standing.

Another issue that will need coordination is reducing the number of PRs that are opened with failing requirements (maybe by running a series of very fast solves during the filtering process to check that deps are available). Since my understanding is that the check will come back as failed and then won't be re-run unless a maintainer comes and fixes things. One issue with this is that it could mean that we **never** open a PR if the upstream dep doesn't get updated (for instance a python rebuild PR doesn't get merged). The failing PR could provide a good reason for upstream maintainers to merge things.

@beckermr

**Comment by beckermr** [comment]
closing in favor of #785
