### ISSUE TITLE
conda-forge.yml not always there

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#757]
Many feedstocks have a blank conda-forge.yml. This may not be an actual issue if it is empty I suppose.

**Comment by CJ-Wright** [comment]
We can put in an empty dict to represent that, the gets should work then.

**Comment by beckermr** [comment]
The issue appears to be that once I changed it, the bot did not get an update. The empty dicts are there. I guess I need to wait a few hours.

**Comment by CJ-Wright** [comment]
You could force the update to the bot's version of it. Although it should pick it up

**Comment by CJ-Wright** [comment]
I think the error is here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/make_graph.py#L104

**Comment by beckermr** [comment]
Ahhhhh. I need to add bot there. Doing it now.

**Comment by CJ-Wright** [comment]
I got it
