### ISSUE TITLE
bot fails to update hashes for multiple source recipes on version updates

### ISSUE THREAD

**Issue by phil-blain** [regro/cf-scripts#762]
The bot failed to update hashes for Git 2.25 in [git-feedstock](https://github.com/conda-forge/git-feedstock/pull/73)

The same thing happened for Git 2.24, which I mentioned here:
https://github.com/regro/cf-scripts/issues/529#issuecomment-558418920

**Comment by beckermr** [comment]
Thank you for the bug report. This is a known problem. I cannot find the issue (I thought) we had on it.

**Comment by CJ-Wright** [comment]
xref: https://github.com/regro/cf-scripts/issues/430
