### ISSUE TITLE
help w/ implementation of CFEP-08 ("Too big to fail")?

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#764]
Should we be putting in a migration to help w/ implementing CFEP-08?

We'd need a special bot w/ write permissions, but for sure our bot could propose PRs for adding core.

**Comment by isuruf** [comment]
CFEP 08 was not accepted.

**Comment by beckermr** [comment]
Ohhhhhh! I assumed since it was merged to master that it had been. I see the deferred label now. Closing this! Thanks @isuruf!
