### ISSUE TITLE
Cleanup `max_py_ver` and `max_r_ver`

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#770]
These are not used anymore.

**Comment by beckermr** [comment]
Do you mean these scripts are using them and they should not be?

**Comment by isuruf** [comment]
These are in `conda-forge.yml` and doesn't do anything anymore. Avoids the confusion.

**Comment by beckermr** [comment]
Ahhhhh. We should add migrator to remove them. Got it thank you!

**Comment by isuruf** [comment]
Not a full one. A migrator that piggybacks on others.

**Comment by beckermr** [comment]
yup ofc
