### ISSUE TITLE
Bot not updating hash in libprotobuf recipe with multiple sources

### ISSUE THREAD

**Issue by jjhelmus** [regro/cf-scripts#781]
The bot recently make a PR to the libprotobuf feedstock, conda-forge/libprotobuf-feedstock#45, which did not update the hash of the source file.  In the past the bot was able to do this, e.g. conda-forge/libprotobuf-feedstock#44.

Note that this recipe uses [multiple sources](https://github.com/conda-forge/libprotobuf-feedstock/blob/master/recipe/meta.yaml#L7-L19) which may be the cause of the issue.  Only the hash of the first tarball needs to be updated.

**Comment by beckermr** [comment]
Yes this is a known issue. I’m adding this issue to our version pr milestone.
