### ISSUE TITLE
Handle BLAS build number scheme

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#80]
The build numbers with BLAS don't actually get reset to `0`, but to some other value based on the formula [outlined in this doc]( https://conda-forge.org/docs/blas.html ). Would be good for the bot to learn about how to do this. In practice, this means if a dependency uses `openblas`, it gets a build number of `200`.

**Comment by CJ-Wright** [comment]
Ok, that should be reasonable. We need to fix up the `build` regex for some other things too (since we still don't do `{{ build_number }}`).

I guess we can do some graph introspection if BLAS is a req to find the current version and then go from there.

**Comment by jakirkham** [comment]
Should clarify, this only matters if a BLAS is at least a build req. If it’s some indirect requirement, we don’t need to do this.

**Comment by isuruf** [comment]
Can anybody remind me why we use this numbering scheme?

**Comment by CJ-Wright** [comment]
https://github.com/conda-forge/scikit-umfpack-feedstock/pull/15

**Comment by CJ-Wright** [comment]
I think a good way to handle this now would be:
```
{ set build_number = 0 }
{ set build_number = build_number + 200 }
```
I think I saw something like this somewhere else and it seemed nice. The bot properly would handle this syntax (updating the build number to 0 but not overwriting the addition).

**Comment by CJ-Wright** [comment]
Is this acceptable? Should we PR that into the docs?

**Comment by CJ-Wright** [comment]
At the very least maybe we put something into the PR comment about this being a blas enabled library and that maintainers need to check that the 200 is there somewhere.

**Comment by CJ-Wright** [comment]
Is this still relevant with the new blas handling system?
