### ISSUE TITLE
url fixes for github

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#827]
Looks like a recipe has this url

`https://github.com/stack-of-tasks/pinocchio/releases/download/v2.3.0/pinocchio-2.3.0.tar.gz`

The actual one is 

`https://github.com/stack-of-tasks/pinocchio/archive/v2.3.0.tar.gz`

We should try a transform

**Comment by CJ-Wright** [comment]
The download link is better, it has a stable hash

**Comment by beckermr** [comment]
Well it is failing to hash for this feedstock.
