### ISSUE TITLE
graph left in bad state when bot dies in stage 3

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#831]
When the bot dies in stage 3, something happens to the graph and it is left in a really bad state where the json won't load a large diff gets pushed to it. 

I'd be nice to figure out what is going on here.

**Comment by beckermr** [comment]
cc @CJ-Wright @mariusvniekerk

**Comment by CJ-Wright** [comment]
Can you give an example of where in the code it fails?

**Comment by CJ-Wright** [comment]
We could be leaving the file open longer than we should.

**Comment by beckermr** [comment]
Check out the latest commit I reverted on the data repo.

**Comment by CJ-Wright** [comment]
I think this is mostly fixed now
