### ISSUE TITLE
separate version updates to their own microservice

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#842]
It is time to split out the version update cron job to its own service. 

- For now, we will reuse the LazyJson infrastructure to build out a new version update table stored in a new cf-graph-version repo. (I had mentioned putting it in the cf-graph-countyfair repo, but then we have to deal with git pull and push issues, which we can punt on using a separate repo.)
- Eventually, this will be moved into dynamodb in another table.
- The JSON model will be a list of version blobs per feedstock.
- This list will be flattened by version string in the final dynamodb table.
- We will run it at half past the hour with the hope that it finishes by the time the bot starts, but it doesn't have to. 

cc @CJ-Wright @mariusvniekerk @scopatz

**Comment by beckermr** [comment]
The entire script is here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py

The key is to move the data structures to another repo with a separate process.

**Comment by viniciusdc** [comment]
I think I can do it, but it will take some time, cause I have to understand the operation of the entire structure that is specified in the script mentioned. And there is a big number of things that i still don't know, of course i may be able to learn it.

**Comment by beckermr** [comment]
I would start simpler. 

1. Read the graph (clone cf-graph-county-fair, use --depth=1, cd to that dir)
2. Load it (call gx = load_graph(), see the main function)
3. call the update versions function in main
4. Inside the update versions function, write the potentially new version for each package to some json in a dir

Once that works, post a PR with the code and then we can move on from there.

**Comment by viniciusdc** [comment]
Ok, I will try that.

**Comment by viniciusdc** [comment]
Ok, now should i work on the first code you sent , or continue with the simple tasks (3) "call the update versions function in main" ?

**Comment by beckermr** [comment]
continue on 3!

**Comment by CJ-Wright** [comment]
@beckermr is it worthwhile to put this into the same Circle system? I think we can have multiple cron jobs offset from each other.

**Comment by beckermr** [comment]
Yep that is fine by me! Great idea!

**Comment by viniciusdc** [comment]
well i got something, but i think that i missed something in the way...
`RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Task exception was never retrieved`

**Comment by viniciusdc** [comment]
in `load_graph.py` i call update`_upstream_versions(gx)` from `.\update_upstream_versions`, and i got the result above when running

**Comment by viniciusdc** [comment]
And i am not supposed to fork as cited cause i am running in a new dir for test right ?

**Comment by beckermr** [comment]
Try turning off dask. If you set the right environment variables it will run serially.

**Comment by viniciusdc** [comment]
Hi, sorry for the late response. I am still in the 3 step, but i have a question, once definied `gx = load graph()`, should i write something inside it before call `update_upstream_versions(gx)` ?

**Comment by beckermr** [comment]
Nope probably not.

**Comment by viniciusdc** [comment]
So, i think that the error that i am seeing is probable cause i am not defining a
source for `update_upstream_versions`.  Now my question, if i create a new archive called pck.json and use its dir as source, it will read ? (pck has a package and its version listed, as in cf-scripts/requirements/test)

**Comment by beckermr** [comment]
Idk sorry. Trace the control flow path through the main function in that file. That should help you figure it out.

**Comment by viniciusdc** [comment]
yes, i think that i discover the issue with my attempts, using the code you sent i have to insert something on `gx` to use `update_upstream_versions(gx)` right ? cause the `attrs` are LazyJson objects... right ?

And if it's the case, how exactly i can input the new data, i think that my doubts focus on this "Inside the update versions function, write the potentially new version for each package to some json in a dir". Just to see if it's right, create a new json file (as told) and call `update_upstream_versions(gx, 'json_dir')` ?

**Comment by viniciusdc** [comment]
and, the json file, must have some especial structure ? cause i saw some "verifications" on the source's structures inside some classes.
Thanks for everything until now, and sorry for so much trouble.

**Comment by beckermr** [comment]
I’m not sure I follow. The goal is to write the new versions to a separate data structure outside of the graph.

**Comment by viniciusdc** [comment]
yes as you cited here "The JSON model will be a list of version blobs per feedstock." right. 
But returning to the subject of `update_upstream_versions`, i am a litle bit confused with the process (4).Cause, as i see in the script you sended (https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/update_upstream_versions.py), when calling `update_upstream_versions` it asks for two inputs `gx, sources` as you said our goal it's to create a new file outside the gx. 
Here, enters my question, can i put a dir to the json file (with package and version information) as a source ?

**Comment by beckermr** [comment]
Ahhh. See what the code currently inputs for sources and follow that.

**Comment by viniciusdc** [comment]
Hi, if possible can you explain me a little bit about the function "main", 
`def main(args: Any = None) -> None:
    from .xonsh_utils import env

    debug = env.get("CONDA_FORGE_TICK_DEBUG", False)
    if debug:
        setup_logger(logger, level="debug")
    else:
        setup_logger(logger)

    logger.info("Reading graph")
    gx = load_graph()

    update_upstream_versions(gx)

    logger.info("writing out file")
    dump_graph(gx)`
and the `meta_yaml`.  ? Thanks

**Comment by viniciusdc** [comment]
The .JSON file can be something like this:
`{
"package": "package_name", 
"version": "package_version"
}`

**Comment by beckermr** [comment]
We can work on the json format later so go with that for now. 

What exactly is your question about the main function?

**Comment by viniciusdc** [comment]
What means 
`distributed.comm.tcp - WARNING - Could not set timeout on TCP stream: [Errno 92] Protocol not available` ?

**Comment by beckermr** [comment]
I have no idea. Usually the dask warnings are harmless and opaque. Maybe @CJ-Wright knows?

**Comment by viniciusdc** [comment]
This part i don't understand. "Inside the update versions function, write the potentially new version for each package to some json in a dir".
by now i have the following:
`from conda_forge_tick.utils import load_graph
from conda_forge_tick.update_upstream_versions import *
gx = load_graph()
update_upstream_versions(gx) `

may i add the dir to a json file inside the update function ?

**Comment by viniciusdc** [comment]
wait, i think i get it. I was thinking other thing. You want me to create a new function called "new update function" that reads the graph and then make an output with the potentially new versions right ?

**Comment by viniciusdc** [comment]
ok, one more question, how is organized the nodes os the graph ?
what was expected to "have" when running `gx.nodes['python']['payloads']` ?

**Comment by beckermr** [comment]
Yup, make a new outout.

For the payload stuff, try this

```python
with gx.nodes['python']['payload'] as attrs:
    print(attrs)
```

The context manager reads the data and any edits get pushed back to disk on exit.

**Comment by viniciusdc** [comment]
Oh thanks, i was realy understanding something completly off, sorry for that.
Yes, i already tried that, the result:
`<conda_forge_tick.utils.Lazy Json object at 0x7f3a5dc7c250>`
so, as i dont know the Json formats for the graph, i went to `graph.json` to see how they were saved.
Taking the "nodes-payload" as example:
`  {
   "id":"ad3-cpp",
   "payload":{
    "__lazy_json__":"node_attrs/ad3-cpp.json"
   }
  }`
Something like this correct ?

**Comment by viniciusdc** [comment]
What was expected to see with `attrs.data` ?

**Comment by beckermr** [comment]
You should get a dictionary with a bunch of information in it.

**Comment by viniciusdc** [comment]
So i should expect something like this ?
`PRed
bad
conda-forge.yml
feedstock_name
hash_type
meta_yaml
name
new_version
pinning_version
raw_meta_yaml
req
requirements
smithy_version
strong_exports
total_requirements
url
version`

**Comment by beckermr** [comment]
yup!

**Comment by viniciusdc** [comment]
and those informations comes for each "id" we have in graph, right ? (our `attrs` have all of them, right ?)

**Comment by beckermr** [comment]
Yeah most nodes have that info. Some nodes will have "archive: True" and so won't have the other info. Also, sometimes the info is not complete.

**Comment by viniciusdc** [comment]
all that info comes from the recipes right ?
if i put this:
`with gx.nodes['python']['payload'] as attrs:`
`   ...:     print(attrs.get("version"))`
i will get the first version from the "version" item in the dict of dicts right ?

**Comment by viniciusdc** [comment]
Sorry for this question, i know that i should get that by myself, but how do i access all the versions from the attrs, cause it's just taking one. (just give me a glimpse of the structure inside the `attrs`)

**Comment by beckermr** [comment]
The graph only has the latest version. The goal of this project is to move the code that generates the "new_version" entry to another process.

**Comment by viniciusdc** [comment]
uhm i see

**Comment by viniciusdc** [comment]
ok, but in looking to `graph.json` there is a bunch of versions for each "id" there, but when a run the `attrs.get("version")` i just get one (i think that's the first one), i would like to know how to access the others ?

**Comment by beckermr** [comment]
Can you send me a link to where you see this?

**Comment by viniciusdc** [comment]
inside `cf-graph-countyfair`  in graph.json

**Comment by beckermr** [comment]
Yeah but exactly where in the josn blob. I am confused about what part of the graph you mean.

**Comment by viniciusdc** [comment]
ok, sorry, i am looking at this section upward 
`"nodes":[
  {
   "id":"ad3-cpp",
   "payload":{
    "__lazy_json__":"node_attrs/ad3-cpp.json"
   }
  },
  {
   "id":"addict",
   "payload":{
    "__lazy_json__":"node_attrs/addict.json"
   }
  },`

**Comment by viniciusdc** [comment]
with my code (until now) 
`gx = load_graph()`

`with gx.nodes['python']['payload'] as attrs:
    print(attrs.get("version"))`

**Comment by beckermr** [comment]
Right, so in the snippet above, replace `python` with the id of another node, and you can see its attrs too.

**Comment by viniciusdc** [comment]
ah of course, sorry about that

**Comment by beckermr** [comment]
no worries!

**Comment by viniciusdc** [comment]
so, i should expet write something like this:
`for pack_id in gx.nodes:`
`    ...:     with gx.nodes["{}".format(pack_id)]["payload"] as attrs:`
 `   ...:         print(attrs.get("version"))`
in a .json file, right ?

**Comment by viniciusdc** [comment]
is there a way to access everything without the for ?, sorry im kind new with the json and yaml structures.

**Comment by viniciusdc** [comment]
Done, the result is something like this:
`{"packid_version": [{"id": "ad3-cpp", "version": "2.5.3"}, {"id": "addict", "version": "2.2.1"}, {"id": "adept", "version": "2.0.5"},..., ]}`

**Comment by beckermr** [comment]
You have to use a loop here. The goal is not to write the current version but to call the code that finds new versions and then write those.

**Comment by viniciusdc** [comment]
Something like this ?
`data = {}`
`data["pack_id-version"] = []`
`for pack_id in gx.nodes:`
`    with gx.nodes["{}".format(pack_id)]["payload"] as attrs:`
`        data["packid_version"].append({
            "id": str(pack_id),
            "version": str(attrs.get("version"))
        })`

`with open("new_version.json", 'w') as outfile:`
`    json.dump(data, outfile)`

But in our case, rather than append the current "version" inside the data, we are going to call the code that find the new versions right ?

**Comment by beckermr** [comment]
Yup something like that

**Comment by viniciusdc** [comment]
Thanks, should i use the `get_latest_version` arrangement inside the loop, or create something new with the same goal ?

**Comment by viniciusdc** [comment]
and what means the `""bad""` option that may appear in some packages ?

**Comment by beckermr** [comment]
Idk what the bad option is actually. And yes use the function in a loop

**Comment by CJ-Wright** [comment]
bad as a metadata element means that the feedstock failed one of the previous steps critically, meaning that none of the subsequent steps should operate on it. For instance we couldn't find the feedstock at all, or the url gave us a 404 (this is a bit of an exception, since we still issue PRs when we get 404s for pinning migrations)

**Comment by viniciusdc** [comment]
Oh thanks @beckermr @CJ-Wright

**Comment by viniciusdc** [comment]
Hi, sorry for the late response, i was working on the proposal for GSoC.
Should i make the pull request now ? -- Maybe changing the code inside the loop for the update function first, right ?

I've made a mini blog for the GSoC, can i put it here ?

**Comment by beckermr** [comment]
A pr is great!

**Comment by viniciusdc** [comment]
Hi again, a finished but not tested yet, the new version of the code (with the `get_new_version` function) . But when i was reading the code of that, i tried another attempt, that was something like this: (i've taken as a base the script you sended and the structure of the functions there)
```
gx = load_graph()
_all_nodes = [t for t in gx.nodes.items()]
random.shuffle(_all_nodes) # why we do this ?

# from here you can inspect the graph object, and what node will be updated:
to_update = []

for node, node_attrs in _all_nodes:
    attrs = node_attrs["payload"]
    # verify the actual situation of the package;
    if attrs.get("bad") or attrs.get("archived"):
        attrs["new_version"] = False
        continue
    to_update.append((node, attrs))

# get the latest version of packages that will be updated, or try
for name, node_attrs in to_update:
    with node_attrs as meta_yaml: # remember, we are already working with the payloads here.
        set_flag = 0
        for source in sources:
            url = source.get_url(meta_yaml)
            if url is None:
                continue
            if new_version:
                attrs["new_version"] = new_version or attrs["new_version"]
            else:
                set_flag = 1
                meta_yaml["bad"] = f"Upstream: Could not find version on {source.name}"
        if not meta_yaml.get("bad"):
            set_flag = 2
            meta_yaml["bad"] = "Upstream: unknown source"
        if set_flag != 0:
            attrs["new_version"] = False or attrs["new_version"]

with open("new_version.json", 'w') as outfile:
    json.dump(to_update, outfile)
```
But i will not use this, cause it will be necessary to import all the sources and the other stuff. What U think?

**Comment by beckermr** [comment]
I don’t know why the code is storing the new version in the graph. The goal is to put that in a separate data structure.

**Comment by viniciusdc** [comment]
Hello, i've finished the code, but when i was running it to verify the final json file, i received this error during the process:
```python
----------------------------------------------------------------SystemExit                     Traceback (most recent call last)~/cf-graph-countyfair/load_graph.py in <module>
     23         # new version request
     24         try:
---> 25             new_version = get_latest_version(node, attrsources)
     26             new_version = new_version or new_version_flag
     27         except Exception as e:

~/cf-scripts/conda_forge_tick/update_upstream_versions.py in get_latest_version(name, payload_meta_yaml, sources)
    468         for source in sources:
    469             logger.debug("source: %s", source.__class____name__)
--> 470             url = source.get_url(meta_yaml)
    471             logger.debug("url: %s", url)
    472             if url is None:

~/cf-scripts/conda_forge_tick/update_upstream_versions.py in get_url(self, meta_yaml)
    444                 count = count + 1
    445                 current_ver = next_ver
--> 446                 new_sha256 = get_sha256(url)
    447                 if new_sha256 == current_sha256 or new_sha256 in new_content:
    448                     return None

~/cf-scripts/conda_forge_tick/update_upstream_versions.py in get_sha256(url)
    362 def get_sha256(url: str) -> Optional[str]:
    363     try:
--> 364         return hash_url(url, timeout=120, hash_type="sha256")
    365     except Exception:
    366         return None

~/cf-scripts/conda_forge_tick/hashing.py in hash_url(url, timeout, progress, hash_type)
     80         kwargs={"progress": progress, "conn": child_con,     81     )
---> 82     p.start()
     83     if parent_conn.poll(timeout):
     84         _hash = parent_conn.recv()

~/miniconda3/lib/python3.7/multiprocessing/process.py in start(self)
    110                'daemonic processes are not allowed to have children'
    111         _cleanup()
--> 112         self._popen = self._Popen(self)
    113         self._sentinel = self._popen.sentinel
    114         # Avoid a refcycle if the target function holds an indirect

~/miniconda3/lib/python3.7/multiprocessing/context.py in _Popen(process_obj)
    221     @staticmethod
    222     def _Popen(process_obj):
--> 223         return _default_context.get_context().Process._Popen(process_obj)
    224
    225 class DefaultContext(BaseContext):

~/miniconda3/lib/python3.7/multiprocessing/context.py in _Popen(process_obj)
    275         def _Popen(process_obj):
    276             from .popen_fork import Popen
--> 277             return Popen(process_obj)
    278
    279     class SpawnProcess(process.BaseProcess):

~/miniconda3/lib/python3.7/multiprocessing/popen_fork.py in __init__(self, process_obj)
     18         self.returncode = None
     19         self.finalizer = None
---> 20         self._launch(process_obj)
     21
     22     def duplicate_for_child(self, fd):

~/miniconda3/lib/python3.7/multiprocessing/popen_fork.py in _launch(self, process_obj)
     74                 code = process_obj._bootstrap()
     75             finally:
---> 76                 os._exit(code)
     77         else:
     78             os.close(child_w)

~/miniconda3/lib/python3.7/site-packages/xonsh/__amalgam__.py in newh(s, frame)
  21704         signal.signal(sig, oldh)
  21705         if sig != 0:
> 21706             sys.exit(sig)
  21707
  21708     signal.signal(sig, newh)

SystemExit: Signals.SIGTERM
```
Any idea why it happened ? I will run again to see which package caused it.

**Comment by viniciusdc** [comment]
Solved, maybe i did something with the cf-graph dir, just needed to download it again and worked. I will make a PR as soon as it finishes.

**Comment by viniciusdc** [comment]
@beckermr is everything alright ?

**Comment by viniciusdc** [comment]
Hello there 👍  I saw this one in `update_upstream_version -- Class: RawURL -- get_url` function, 
`# TODO: pull this from the graph itself`
`        content = meta_yaml["raw_meta_yaml"]`
what exactly it means ?

**Comment by beckermr** [comment]
not sure - @CJ-Wright ?

**Comment by viniciusdc** [comment]
quick doubt, can I separate the class sources into another script and leave the new `update version` script just with the update stuff?

**Comment by beckermr** [comment]
yeah that is fine

**Comment by viniciusdc** [comment]
may put this in `auto-tick.utils` ?
```python
def get_sha256(url: str) -> Optional[str]:
    try:
        return hash_url(url, timeout=120, hash_type="sha256")
    except Exception as e:
        logger.debug("url hashing exception: %s", repr(e))
        return None


def url_exists(url: str) -> bool:
    try:
        output = subprocess.check_output(
            ["wget", "--spider", url], stderr=subprocess.STDOUT, timeout=1,
        )
    except Exception:
        return False
    # For FTP servers an exception is not thrown
    if "No such file" in output.decode("utf-8"):
        return False
    if "not retrieving" in output.decode("utf-8"):
        return False

    return True


def url_exists_swap_exts(url: str):
    if url_exists(url):
        return True, url

    # TODO this is too expensive
    # from conda_forge_tick.url_transforms import gen_transformed_urls
    # for new_url in gen_transformed_urls(url):
    #     if url_exists(new_url):
    #         return True, new_url

    return False, None
```

**Comment by viniciusdc** [comment]
Sorry for these questions, but where it especify this option `CONDA_FORGE_TICK_DEBUG` ?

**Comment by beckermr** [comment]
That is an env var. So on the command line on linux do something like `export CONDA_FORGE_TICK_DEBUG=1`

**Comment by viniciusdc** [comment]
Thanks :+1:

**Comment by viniciusdc** [comment]
I know that we are using the networkx to create the graph, so it's necessary to create the json output as a `nx.DiGraph` too ?

**Comment by beckermr** [comment]
I'd use a python dict in memory.

**Comment by viniciusdc** [comment]
"in memory" ?

**Comment by beckermr** [comment]
When coding in python, store the versions in a dictionary. Then id' dump that dictionary to disk, separating it out into different files for different nodes. There is no need for a graph here.

**Comment by viniciusdc** [comment]
Hi, I am separating the source classes to test... What this source class does ? 
```python
class AbstractSource(abc.ABC):
    name: str

    @abc.abstractmethod
    def get_version(self, url: str) -> Optional[str]:
        pass

    @abc.abstractmethod
    def get_url(self, url: str) -> Optional[str]:
        pass

```

**Comment by beckermr** [comment]
https://docs.python.org/3/library/abc.html

**Comment by viniciusdc** [comment]
thanks :)

**Comment by viniciusdc** [comment]
More one thing,  why we use a 'if' here ? It's not always `sources = none` ? 
```python
sources = (
        (PyPI(), CRAN(), NPM(), ROSDistro(), RawURL(), Github())
        if sources is None
        else sources
    )
```

**Comment by beckermr** [comment]
link to the source?

we have lots of residual code lying around so many things might just be old

**Comment by viniciusdc** [comment]
Here https://github.com/regro/cf-scripts/blob/5b9be3c675a178f77a31ac5200705bbd0c7600d3/conda_forge_tick/update_upstream_versions.py#L598, but if you look to `main` when it's called we use only `gx` as a parameter.

**Comment by beckermr** [comment]
Yeah so source is None by default, but this block of code lets us pass in other things if we want.

**Comment by viniciusdc** [comment]
yup, so... if we want to use the `update_upstream_version` separatly using another `source` it's possible, basically this what the block means right

**Comment by viniciusdc** [comment]
Now I understand why we use the Abstract Source class, very useful

**Comment by viniciusdc** [comment]
Hi, I've changed the code, now I only need to rebuild the `get_latest_version` function and its affiliates. Where I can put the new script ?

**Comment by viniciusdc** [comment]
I will put a link to my repo with the files

**Comment by CJ-Wright** [comment]
Why was that development not done in your fork of cf-scripts?

**Comment by viniciusdc** [comment]
I created a separate work space to test some ideas with the graph itself. Than when finished I will sendo to my fork and than create a PR. But this time I forgot this, haha

**Comment by viniciusdc** [comment]
One question, do I create a new PR with this or update the old one ?

**Comment by CJ-Wright** [comment]
Whichever is easiest for you

**Comment by viniciusdc** [comment]
OK, I added the new updates to the fork repo, and I will work on the `get_update_versions`. Sorry for any late response.

**Comment by viniciusdc** [comment]
When using logging, is there a way to set the same logger for a subscript ? e.g. I've separated the sources classes to another file (will... not entirely) but some of them gives debug info on our logger (but, it's currently defined in another script).  Is there a simple way to solve this ? Or just call (logging.getLogger) again ?

**Comment by viniciusdc** [comment]
Can I do something like: `logging.getLogger(conda_forge_tick.cs-graph_update_version.update_sources)` ? As a hierarchical logger for the `update sources` debug ?

**Comment by viniciusdc** [comment]
Hi, sorry for the late feedback. I was testing the pool version. It looks fine until now but I've received a strange output for the `get latest_version`. I saved the initial output to a file warnings.text, after that the code runs smoothly as before (but now just takes 4 min 😄 ).
[warnings.txt](https://github.com/regro/cf-scripts/files/4813421/warnings.txt)

**Comment by viniciusdc** [comment]
I think that with #1075  working, we can start discussing the next steps, right ?

**Comment by beckermr** [comment]
Yup. this issue is done!
