### ISSUE TITLE
Packages from recipes with multple outputs cannot be migrated

### ISSUE THREAD

**Issue by chrisburr** [regro/cf-scripts#852]
As shown in `root_base` wasn't being migrated. https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/415

It issue is that `root_base` isn't in `gx.nodes` so it gets removed here:

https://github.com/regro/cf-scripts/blob/077c79ecadbd77891f2e7d2e3ee1480e159ddd06/conda_forge_tick/auto_tick.py#L437-L440

I guess this is because it is one of the outputs in the ROOT recipe `root`

cc @beckermr @duncanmmacleod

**Comment by beckermr** [comment]
@CJ-Wright Ideas here? We probably need to map outputs back to their parent feedstocks before doing these checks.

**Comment by chrisburr** [comment]
I think it’s a simple fix and I’ve started implementing it, I’ll make a PR shortly.

**Comment by CJ-Wright** [comment]
There should be a map of feedstocks and outputs you can use.
