### ISSUE TITLE
rpcq-feedstock: bot-rerun closed existing PR but did not open a new one

### ISSUE THREAD

**Issue by appleby** [regro/cf-scripts#856]
The auto-tick bot closed my PR ~16 hours ago due to the `bot-rerun` label, but still has not opened a new PR. Should I keep waiting, or do I need to take some action to unwedge it?

https://github.com/regro/cf-scripts/issues/578 makes me think the maybe the re-opening should have happened during the same run that the issue was closed?

https://github.com/regro/cf-scripts/issues/786 makes me think the bot might have hit an error and will not recover.

https://github.com/regro/cf-scripts/issues/405 makes me think I might need to create a new PR and apply the bot's changes myself?

https://github.com/regro/cf-scripts/issues/428, however, makes me think I might just need to be patient :)

PR in question & cf-graph json file:

https://github.com/conda-forge/rpcq-feedstock/pull/24
https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/rpcq.json

Note that I was added to the recipe-maintainers list *after* the auto-tick bot created this PR, in case that is relevant.

Circle CI logs for the worker that closed the PR and the last completed run:

https://circleci.com/gh/regro/circle_worker/14844
https://circleci.com/gh/regro/circle_worker/14859

My project (rpcq) appears in the stage 2 logs, but does not appear in later stages.

**Comment by beckermr** [comment]
This line of metadata is weird: https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/rpcq.json#L279

@CJ-Wright does this look right to you?

**Comment by appleby** [comment]
Just a guess, but possibly coming from this line in `make_graph.py`?

https://github.com/regro/cf-scripts/blob/25065365a18ad98a0ad3a2ae4cbe08771e46101b/conda_forge_tick/make_graph.py#L347

**Comment by beckermr** [comment]
So looking carefully at the data, I think the line above should be 

```
node["PRed"][i]["data"]["bot_rerun"] = time.time()
```

For the record, here is the json blob

```
...
   "bot_rerun":1583374335.206745,
   "data":{
    "bot_rerun":false,
    "migrator_name":"Version",
    "migrator_version":0,
    "version":"3.1.0"
   },
```

In the migrator, it is checked if the PR is already made here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/core.py#L275

and that uses the data part. So right now the code does not appear to be resetting the data properly.

**Comment by appleby** [comment]
Thanks for your help @beckermr

Any recommendation for what I should do on my end to resolve it? I assume it will take some time for a fix to be merged. Is there some way I can coax the bot into opening a new PR in the meantime, or should I open a new PR myself that includes the changes from conda-forge/rpcq-feedstock#24?

**Comment by beckermr** [comment]
Yeah here is another bot-rerun that looks correct: https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/synphot.json#L44

**Comment by beckermr** [comment]
and here: https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/toad.json#L8
