### ISSUE TITLE
Confused by Pypy rebuilds. 

### ISSUE THREAD

**Issue by Carreau** [regro/cf-scripts#863]
I'm confused by the two following suggested rebuilds that both fail with conda solving dependencies. 

I'm not sure if there is anything I should/could do to help. 

https://github.com/conda-forge/ipython-feedstock/pull/98
https://github.com/conda-forge/ipykernel-feedstock/pull/55

BTW is the "automerge" label new ?

**Comment by isuruf** [comment]
The bot shouldn't have made those PRs without https://github.com/conda-forge/traitlets-feedstock/pull/20

> BTW is the "automerge" label new ?

Yes, it was added last week.

**Comment by isuruf** [comment]
I think this was because of a cycle.
`jupyter_core->ipykernel (for testing)->jupyter_client->jupyter_core`

**Comment by beckermr** [comment]
this appears to be fixed
