### ISSUE TITLE
Discussion: Direct Pushing

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#87]
Is there any interest in having the bot push directly to some recipes?
This came up in a discussion of dev/alpha/rc releases, where releases may become too rapid for maintainers to actively keep track of, although it could be applied more broadly.

Attn:
@jakirkham

**Comment by msarahan** [comment]
only if they are going to a "testing" or "staging" channel of some sort.  IMHO, humans should always be in the loop for stuff that gets deployed to our primary channel.

**Comment by CJ-Wright** [comment]
automerge covers this
