### ISSUE TITLE
Rebuild for pypy removes [not win] selector

### ISSUE THREAD

**Issue by vtraag** [regro/cf-scripts#886]
The automated rebuild for PyPy in this [PR](https://github.com/conda-forge/python-igraph-feedstock/pull/24#event-3141450851) incorrectly removed the `# [not win]` selector for the build script. This feedstock uses a `bld.bat`, which was no longer properly executed and had to be addressed, after which it worked fine. Perhaps similar issues will appear in other feedstocks, perhaps this can be corrected?

**Comment by beckermr** [comment]
Ahhh found it sorry. This is the pip mini migrator. @CJ-Wright

**Comment by beckermr** [comment]
We need to move to a regex here I think: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/core.py#L130
