### ISSUE TITLE
Stale Feedstock Creation

### ISSUE THREAD

**Issue by hhslepicka** [regro/cf-scripts#888]
Following the guidance of @beckermr and opening an issue. (Sorry if this is not the right spot).

This PR (https://github.com/conda-forge/staged-recipes/pull/11078) to staged recipes was merged 5 hours ago and looks like the feedstock repos are stale:
- https://github.com/conda-forge/psdm_qs_cli-feedstock
- https://github.com/conda-forge/krtc-feedstock

Attn. @klauer

**Comment by beckermr** [comment]
This issue needs to be moved to conda-forge/staged-recipes

**Comment by beckermr** [comment]
I cannot move it between orgs, so you'll have to remake it.

**Comment by hhslepicka** [comment]
Sorry @beckermr I just saw it. Thank you for creating the issue there.

**Comment by beckermr** [comment]
closing here
