### ISSUE TITLE
autotick bot missed release

### ISSUE THREAD

**Issue by tacaswell** [regro/cf-scripts#889]
Following the guidance of @beckermr and opening an issue. (Sorry if this is not the right spot).

The bot missed Matplotilb 3.2.1 https://github.com/matplotlib/matplotlib/releases/tag/v3.2.1

**Comment by hhslepicka** [comment]
Adding to @tacaswell issue, it also missed PyDM 1.9.0 (https://github.com/slaclab/pydm/releases/tag/v1.9.0) and a couple of other project tags released this week.

**Comment by beckermr** [comment]
You guys found it! Thanks!

**Comment by beckermr** [comment]
Well that was timely autotick bot. It found it!

https://github.com/conda-forge/matplotlib-feedstock/pull/237

**Comment by beckermr** [comment]
i'm closing for now, but if this happens again, feel free to reopen

**Comment by danielhuppmann** [comment]
Referring https://github.com/conda-forge/pyam-feedstock/issues/19 per recommendation by @beckermr to this repo, seems to be a similar issue to the one described above.

Previously, a new PR was started by `regro-cf-autotick-bot` upon making a new release in the source repository https://github.com/IAMconsortium/pyam (as written in the [conda-forge docs](https://conda-forge.org/docs/maintainer/updating_pkgs.html?highlight=branch#pushing-to-regro-cf-autotick-bot-branch)).

This is not happening with the latest [release 0.7.0](https://github.com/IAMconsortium/pyam/releases/tag/v0.7.0). Did something intentionally change, is this a bug or is something wrong in our feedstock recipe (or related)?

**Comment by CJ-Wright** [comment]
It seems there was an error while getting the upstream version https://github.com/regro/cf-graph-countyfair/blame/master/node_attrs/pyam.json#L158

**Comment by CJ-Wright** [comment]
@danielhuppmann I think I found your issue. It seems that you have a list of length 1 as your source value. If you had a regular dictionary things might work properly.

I'd also happily accept a PR that fixes this corner case.

**Comment by beckermr** [comment]
Good work @CJ-Wright!

**Comment by danielhuppmann** [comment]
Thank you so much @CJ-Wright - will give this a try!
