### ISSUE TITLE
add orderedset back to the graph

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#893]
This feedstock was unarchived and the bot missed that.

https://github.com/conda-forge/orderedset-feedstock/pull/5

**Comment by CJ-Wright** [comment]
If you set `archived:True` to false in the graph itself the bot should pick it up

**Comment by beckermr** [comment]
Yup. Just a reminder to actually do it!

**Comment by beckermr** [comment]
https://github.com/regro/cf-graph-countyfair/pull/10
