### ISSUE TITLE
moved to chained jobs in circle worker

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#900]

**Comment by CJ-Wright** [comment]
One interesting thing we might need for this is a giant stop button.
We might consider putting a bool somewhere (maybe in GH?) that if set to false, the bot stops what it is doing, commits/pushes the data and exits. Currently the bot's capacity is limited to the cron, but if we have this cycle then there could be no limit to what it could do.

**Comment by beckermr** [comment]
Yep. We can have this in the circle_worker repo.

**Comment by beckermr** [comment]
Remove the min here: https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/auto_tick.py#L465

set a max of 50
