### ISSUE TITLE
Update PRs for `dask-core` and `dask` 2.13.0 missing

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#905]
Appears the bot updated `distributed` to 2.13.0, but missed `dask-core` and `dask`, which were also released at the same time.

cc @beckermr @jrbourbeau

**Comment by jrbourbeau** [comment]
Thanks for tracking this @jakirkham!

I see the [`distributed` PR](https://github.com/conda-forge/distributed-feedstock/pull/122) has updates to a bunch of files other than the recipe meta file. Should I manually open up PRs in `dask-core` and `dask`, or does the bot need to do this so other files are also updated?

**Comment by jakirkham** [comment]
Yeah we can do this manually. Re-rendering would address that for the other feedstocks.

**Comment by jrbourbeau** [comment]
Just for reference: https://github.com/conda-forge/dask-core-feedstock/pull/65, https://github.com/conda-forge/dask-feedstock/pull/106

**Comment by jakirkham** [comment]
We've finished manually migrating these. Not sure if you want to keep this issue or close/consolidate into some other issue, @beckermr. Happy whichever way 🙂

**Comment by beckermr** [comment]
Let’s keep it open for now. There are some things I want to check.

**Comment by beckermr** [comment]
Closing. Looks like recent updates were pushed by the bot. I checked the stuff I cared about.
