### ISSUE TITLE
pushd errors

### ISSUE THREAD

**Issue by beckermr** [regro/cf-scripts#910]
The bot is failing a lot on errors in pushd. This is basically stopping all migrations.

see the logs at the end: https://circleci.com/api/v1.1/project/github/regro/circle_worker/15361/output/108/0?file=true&allocation-id=5e7ca75d777ecd4a9eb7d6d5-0-build%2F7CDEE242

cc @CJ-Wright @scopatz Can you all look at this and push a fix?

**Comment by CJ-Wright** [comment]
It looks like somethign invalid is being passed into `with indir(cb_work_dir):` from the license(?) mini migrator?
