### ISSUE TITLE
Close out migrations

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#912]
It would be nice to send a PR that closes out a migration (removes or moves the migration yaml and updates the pinning) once a condition has been met. We can default the condition to being all PRs issued. But it might be good to have the condition be configurable.

**Comment by CJ-Wright** [comment]
Roadmap/random thoughts:

1. Cut the migration yaml into each of the keys and values needed (things that don't start with `_` or `migrator_rs`) For instance the pypy migrations would have a chunk for python and its versions, numpy and its versions etc.
2. read the `conda_forge_pinning.yaml` line by line, looking for the key line(s). Replace all the lines after that line (until the next key) with the information from the migration yaml.
3. Remove the migration yaml from the migrations dir
4. Issue PR

This could go into either the migration creator migrator or the migration migrator itself. I think it is a little better in the migration migrator, since that knows when all the other PRs have been issued/merged. Note that this doesn't stop us from closing out a migration before all the PRs have been merged.

**Comment by beckermr** [comment]
@CJ-Wright Let's use the variant merging stuff @mariusvniekerk put into conda-smithy. This is what the migrator does anyways.

**Comment by CJ-Wright** [comment]
That doesn't handle selectors

**Comment by beckermr** [comment]
Hmmmm. It must, but what I think you mean is that it renders them first and then does the merging.

**Comment by CJ-Wright** [comment]
Right, the `conda_forge_pinning.yaml` is not the output of a varient merge, since the merge happens after the selectors operate. We can't round trip a pinning/migration yaml if it has selectors.

**Comment by beckermr** [comment]
The zip keys and levels of indentation will need careful testing here. Ugh

**Comment by CJ-Wright** [comment]
I thinkn zip_keys is ok, we can just replace it wholesale (at least based on the current usage in pypy)

**Comment by beckermr** [comment]
Hmmmm. Is that the logic @mariusvniekerk used in the variant merging? I think we need to match that.

**Comment by CJ-Wright** [comment]
I think that's easier said than done xref: https://github.com/conda-forge/conda-smithy/blob/master/tests/test_variant_algebra.py#L213

Also I'm not certain we've ran into a use case that hits that.

**Comment by beckermr** [comment]
I get that it is hard, but IDK if a use case existing is a reason to not implement it.

**Comment by mariusvniekerk** [comment]
As long as we can come up with a good set of test cases and make them work it should be fine
