### ISSUE TITLE
pykerberos has not received krb51171 migration

### ISSUE THREAD

**Issue by duncanmmacleod** [regro/cf-scripts#931]
The krb51171 migration (e.g. [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/480)) has not triggered an update to the [pykerberos](https://github.com/conda-forge/pykerberos-feedstock) feedstock, which has `host` and `run` requirements on `krb5`.

cc @CJ-Wright

**Comment by CJ-Wright** [comment]
I think the resolution here is to change the graph metadata to restore pykerberos to good standing

**Comment by duncanmmacleod** [comment]
Thanks @CJ-Wright, I presume I can't help with that. I also presume that with that a PR will appear at some point, and I should preempt things by manually migrating pykerberos?

**Comment by CJ-Wright** [comment]
You can fix it, by putting up a PR into the graph to fix that, it is a GH repo after all.

**Comment by CJ-Wright** [comment]
I think this is fixed now!
