### ISSUE TITLE
Archived holiday

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#937]
We could run the `make_graph` update steps on archived packages once in a while (maybe every day?). This would slow us down a little but would make certain we catch feedstocks that were archived and have been revived or mistakenly archived.

CC: @duncanmmacleod

**Comment by beckermr** [comment]
On this note, I am finding stuff that is archived but not marked as such. Is that a bug?

**Comment by CJ-Wright** [comment]
Most likely, the way we do archived is if GH sends us the "archived repo" response during `make_graph`.

**Comment by CJ-Wright** [comment]
Sorry that was wrong, it is done in `auto_tick.py` https://github.com/regro/cf-scripts/blob/4eb1cff0127a8ce16685d7a2020f167f5fbe7c17/conda_forge_tick/auto_tick.py#L963

**Comment by beckermr** [comment]
The admin migration bot now pulls a correct list of archived feedstocks. We can pull the json here: https://raw.githubusercontent.com/conda-forge/admin-migrations/master/data/all_feedstocks.json

**Comment by beckermr** [comment]
This is updated every two hours.

**Comment by beckermr** [comment]
This should solve our issues with things being archived or not.
