### ISSUE TITLE
Missed version update for pari

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#943]
https://github.com/conda-forge/pari-feedstock

There was a version update 3 months ago, but no update PR

**Comment by beckermr** [comment]
Thanks! We’ll look into this.

**Comment by beckermr** [comment]
So the bot is not finding the upstream version. My guess is that it might be the list of URLs in the recipe. It looks like the first one is correct but the second one is no longer used.

**Comment by isuruf** [comment]
There were PRs before, so this might be a regression.
https://github.com/conda-forge/pari-feedstock/pulls?q=is%3Apr+is%3Aclosed

**Comment by CJ-Wright** [comment]
I think there is an issue with how the bot is handling generic urls (not pypi/cran)
