### ISSUE TITLE
Python 3.8 Migration Issue

### ISSUE THREAD

**Issue by rlizzo** [regro/cf-scripts#946]
HIi All, hope this is the right place to put this. 

I'm inquiring about a (potential?) bug in migrating to python 3.8 for https://github.com/conda-forge/hangar-feedstock. 

We just release a new version today and merged the [feedstock-pr](https://github.com/conda-forge/hangar-feedstock/pull/12), and py38 was not included in the build matrix. Since the project is showing as "done" under "python3.8 Migration Status" on the [Status Page](https://conda-forge.org/status/) i'm wondering how I can go about fixing this? 

Thanks!

**Comment by CJ-Wright** [comment]
Thank you for the bug report! You can issue a PR removing [this](https://github.com/regro/cf-graph-countyfair/blob/master/node_attrs/hangar.json#L37-L55) chunk of json (it's the bot's record of the PR) and then the bot should open a new PR.

**Comment by rlizzo** [comment]
Thanks for the quick reply! PR has been submitted as advised.

**Comment by rlizzo** [comment]
Thanks for all your help @CJ-Wright, the issue has been resolved as of https://github.com/conda-forge/hangar-feedstock/pull/13. Cheers!
