### ISSUE TITLE
Potential custom migration for regro/cf-scripts for terraform packages

### ISSUE THREAD

**Issue by oblute** [regro/cf-scripts#965]
After recent (and much needed) updates to the golang feedstock (https://github.com/conda-forge/go-feedstock), which is now updated to v1.13.x, there are many, many terraform feedstocks (70) that rely on the new version of Go in order to be updated to their most recent versions. All of these updates require a rerender for the new Go version, and an added line to the build script in the meta.yaml that exports GOBIN correctly given changes to new golang - - GOBIN=$(go env GOBIN) # [not win]

My team and I (cc @rluria14 @ndmaxar) were hoping there could be a custom migration made to automate and generate PRs for this on all terraform- packages. We have the bandwith to help on this in whatever way possible, while lacking experiencing on generating this on conda-forge.

Hoping to get this rolling soon :)

**Comment by CJ-Wright** [comment]
This was a migrator that was created for bad javascript build commands https://github.com/regro/cf-scripts/blob/master/conda_forge_tick/migrators/disabled/legacy.py#L22

**Comment by CJ-Wright** [comment]
Was this issue resolved?

**Comment by oblute** [comment]
@CJ-Wright yes, @sodre pushed a script early this weekend that made the necessary updates for the new go compiler for Terraform packages. thanks for pointing me in the right direction!
