### ISSUE TITLE
meta.yaml can be broken by linewrapping

### ISSUE THREAD

**Issue by pkgw** [regro/cf-scripts#973]
In [this regro commit](https://github.com/conda-forge/librsvg-feedstock/pull/48/commits/efc5d337c2fedbce8cbe0d37bd946f81ed9ab7bb) to the librsvg feedstock, a very long line in the `test:` section gets linewrapped inappropriately in a way that breaks the file. That shouldn't happen.

**Comment by beckermr** [comment]
this is ruamel.yaml doing the wrapping I can turn up the max line length

**Comment by beckermr** [comment]
This is fixed on master now. I doubled the line length limit.
