### ISSUE TITLE
Multiple PRs opened to update package

### ISSUE THREAD

**Issue by vtraag** [regro/cf-scripts#981]
There were 5 duplicate PRs being opened to update the `igraph` package:

- https://github.com/conda-forge/python-igraph-feedstock/pull/26
- https://github.com/conda-forge/python-igraph-feedstock/pull/27
- https://github.com/conda-forge/python-igraph-feedstock/pull/28
- https://github.com/conda-forge/python-igraph-feedstock/pull/29
- https://github.com/conda-forge/python-igraph-feedstock/pull/30

This seems a bit redundant, not sure why this has happened. Perhaps you can take a closer look?

P.S. Small spelling mistake: in the text it says `cf-regro-autotick-bot`, while the actual account is `regro-cf-autotick-bot`.

**Comment by beckermr** [comment]
This was a bug that should be fixed now. Use the most recent one (30) and close the rest. Sorry for the trouble and thanks for the issue!

**Comment by beckermr** [comment]
I've fixed the spelling error.
