### ISSUE TITLE
add `.*` to pinned packages

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#987]
Mamba would appreciate it if packages that pin on their own either pin exactly or have `.*` at the end. We might consider a minimigrator that fixes this.

**Comment by beckermr** [comment]
Do we need to put this in the mamba code we have now?

**Comment by CJ-Wright** [comment]
most likely, although conda build is also warning about this so we should fix it properly.

**Comment by beckermr** [comment]
Right. We need a fix in both spots
